



// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten

namespace Rathalos.Core.Protocol.Messages
{

    /// <summary>
    /// Error codes for tconnd internal logic disconnection
    /// </summary>

    public enum TPDU_STOP_REASON
    {
		/// <summary>
		/// Success
		/// </summary>
		TPDU_REASON_NONE = 0,
		/// <summary>
		/// Connection idle timeout close
		/// </summary>
		TPDU_REASON_IDLE_CLOSE = 1,
		/// <summary>
		/// Invalid request packet length
		/// </summary>
		TPDU_REASON_BAD_PKGLEN = 4,
		/// <summary>
		/// Client send rate exceeded limit
		/// </summary>
		TPDU_REASON_EXCEED_LIMIT = 5,
		/// <summary>
		/// Logic server initiated close
		/// </summary>
		TPDU_REASON_SELF_CLOSE = 7,
		/// <summary>
		/// Client connection signature verification failed
		/// </summary>
		TPDU_REASON_AUTH_FAIL = 8,
		/// <summary>
		/// Client three-way handshake verification failed
		/// </summary>
		TPDU_REASON_REASON_SYNACK_FAIL = 9,
		/// <summary>
		/// Invalid upstream packet sequence number
		/// </summary>
		TPDU_REASON_SEQUENCE_INVALID = 11,
		/// <summary>
		/// Client reconnection failed
		/// </summary>
		TPDU_REASON_RELAY_FAIL = 14,
		/// <summary>
		/// Security question processing failed
		/// </summary>
		TPDU_REASON_MBA_FAIL = 15,
		/// <summary>
		/// Security question response timeout
		/// </summary>
		TPDU_REASON_MBA_TIMEOUT = 16,
		/// <summary>
		/// Connection limit reached
		/// </summary>
		TPDU_REASON_REACH_LIMIT = 100
    }
}