using System.Text;
using Rathalos.CLI.CodeGeneration.Models;
using Rathalos.CLI.CodeGeneration.Templates;

namespace Rathalos.CLI.CodeGeneration.Services
{
    /// <summary>
    /// T4 template engine for generating code using actual T4 templates
    /// </summary>
    public class TemplateEngine
    {
        public string ProcessClassTemplate(GeneratedClass classModel, GeneratedCodeModel? codeModel = null)
        {
            try
            {
                var template = new ClassTemplate()
                {
                    Model = classModel,
                    CodeModel = codeModel
                };
                return template.TransformText();
            }
            catch (Exception ex)
            {
                // Fallback to manual generation if T4 fails
                Console.WriteLine($"T4 template failed, using fallback: {ex.Message}");
                return GenerateClassManually(classModel);
            }
        }

        public string ProcessEnumTemplate(GeneratedEnum enumModel)
        {
            try
            {
                var template = new EnumTemplate()
                {
                    Model = enumModel,
                };
                return template.TransformText();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"T4 template failed, using fallback: {ex.Message}");
                return GenerateEnumManually(enumModel);
            }
        }

        public string ProcessInterfaceTemplate(GeneratedInterface interfaceModel)
        {
            try
            {
                var template = new InterfaceTemplate()
                {
                    Model = interfaceModel,
                };
                return template.TransformText();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"T4 template failed, using fallback: {ex.Message}");
                return GenerateInterfaceManually(interfaceModel);
            }
        }

        public string ProcessConstantsTemplate(Dictionary<string, string> constants, string targetNamespace)
        {
            try
            {
                var template = new ConstantsTemplate()
                {
                    Constants = constants,
                    TargetNamespace = targetNamespace
                };
                return template.TransformText();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"T4 template failed, using fallback: {ex.Message}");
                return GenerateConstantsManually(constants, targetNamespace);
            }
        }

        // Fallback manual generation methods (existing logic)
        private string GenerateClassManually(GeneratedClass classModel)
        {
            var sb = new StringBuilder();
            
            // Start with header
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("// This file was generated from XML metalib definition");
            sb.AppendLine("// Do not modify this file manually as it will be overwritten");
            sb.AppendLine();

            // Using statements
            foreach (var usingStatement in classModel.UsingStatements.Where(u => !string.IsNullOrWhiteSpace(u)))
            {
                sb.AppendLine($"using {usingStatement};");
            }
            sb.AppendLine();

            // Namespace
            sb.AppendLine($"namespace {classModel.Namespace}");
            sb.AppendLine("{");

            // Class documentation
            if (!string.IsNullOrWhiteSpace(classModel.Description))
            {
                sb.AppendLine("    /// <summary>");
                sb.AppendLine($"    /// {classModel.Description}");
                sb.AppendLine("    /// </summary>");
            }

            // Class declaration
            sb.Append($"    public {(classModel.IsStruct ? "struct" : "class")} {classModel.Name}");
            
            var inheritanceList = new List<string>();
            if (!string.IsNullOrWhiteSpace(classModel.BaseClass))
            {
                inheritanceList.Add(classModel.BaseClass);
            }
            inheritanceList.AddRange(classModel.Interfaces);
            
            if (inheritanceList.Any())
            {
                sb.Append(" : " + string.Join(", ", inheritanceList));
            }
            
            sb.AppendLine();
            sb.AppendLine("    {");

            // Properties
            foreach (var property in classModel.Properties)
            {
                if (!string.IsNullOrWhiteSpace(property.Description))
                {
                    sb.AppendLine("        /// <summary>");
                    sb.AppendLine($"        /// {property.Description}");
                    sb.AppendLine("        /// </summary>");
                }

                foreach (var attribute in property.Attributes)
                {
                    sb.AppendLine($"        {attribute}");
                }

                if (property.IsProtocolId)
                {
                    sb.AppendLine($"        public const {property.Type} {property.Name} = {property.DefaultValue};");
                }
                else
                {
                    var arrayNotation = property.IsArray ? "[]" : "";
                    sb.Append($"        public {property.Type}{arrayNotation} {property.Name} {{ get; set; }}");

                    if (!string.IsNullOrWhiteSpace(property.DefaultValue))
                    {
                        sb.Append($" = {property.DefaultValue};");
                    }
                    else if (property.IsArray)
                    {
                        sb.Append($" = Array.Empty<{property.Type}>();");
                    }

                    sb.AppendLine();
                }

                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private string GenerateEnumManually(GeneratedEnum enumModel)
        {
            var sb = new StringBuilder();
            
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("// This file was generated from XML metalib definition");
            sb.AppendLine("// Do not modify this file manually as it will be overwritten");
            sb.AppendLine();
            sb.AppendLine($"namespace {enumModel.Namespace}");
            sb.AppendLine("{");

            if (!string.IsNullOrWhiteSpace(enumModel.Description))
            {
                sb.AppendLine("    /// <summary>");
                sb.AppendLine($"    /// {enumModel.Description}");
                sb.AppendLine("    /// </summary>");
            }

            sb.Append($"    public enum {enumModel.Name}");
            if (enumModel.UnderlyingType != "int")
            {
                sb.Append($" : {enumModel.UnderlyingType}");
            }
            sb.AppendLine();
            sb.AppendLine("    {");

            for (int i = 0; i < enumModel.Values.Count; i++)
            {
                var value = enumModel.Values[i];
                var isLast = i == enumModel.Values.Count - 1;

                if (!string.IsNullOrWhiteSpace(value.Description))
                {
                    sb.AppendLine("        /// <summary>");
                    sb.AppendLine($"        /// {value.Description}");
                    sb.AppendLine("        /// </summary>");
                }

                sb.Append($"        {value.Name} = {value.Value}");
                if (!isLast)
                {
                    sb.Append(",");
                }
                sb.AppendLine();

                if (!isLast)
                {
                    sb.AppendLine();
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private string GenerateInterfaceManually(GeneratedInterface interfaceModel)
        {
            var sb = new StringBuilder();
            
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("// This file was generated from XML metalib definition");
            sb.AppendLine("// Do not modify this file manually as it will be overwritten");
            sb.AppendLine();

            foreach (var usingStatement in interfaceModel.UsingStatements.Where(u => !string.IsNullOrWhiteSpace(u)))
            {
                sb.AppendLine($"using {usingStatement};");
            }
            sb.AppendLine();

            sb.AppendLine($"namespace {interfaceModel.Namespace}");
            sb.AppendLine("{");

            if (!string.IsNullOrWhiteSpace(interfaceModel.Description))
            {
                sb.AppendLine("    /// <summary>");
                sb.AppendLine($"    /// {interfaceModel.Description}");
                sb.AppendLine("    /// </summary>");
            }

            sb.AppendLine($"    public interface {interfaceModel.Name}");
            sb.AppendLine("    {");

            foreach (var property in interfaceModel.Properties)
            {
                if (!string.IsNullOrWhiteSpace(property.Description))
                {
                    sb.AppendLine("        /// <summary>");
                    sb.AppendLine($"        /// {property.Description}");
                    sb.AppendLine("        /// </summary>");
                }

                var arrayNotation = property.IsArray ? "[]" : "";
                sb.AppendLine($"        {property.Type}{arrayNotation} {property.Name} {{ get; set; }}");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private string GenerateConstantsManually(Dictionary<string, string> constants, string targetNamespace)
        {
            var sb = new StringBuilder();
            
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("// This file was generated from XML metalib definition");
            sb.AppendLine("// Do not modify this file manually as it will be overwritten");
            sb.AppendLine();
            sb.AppendLine($"namespace {targetNamespace}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Constants defined in the XML metalib");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class MetaLibConstants");
            sb.AppendLine("    {");

            foreach (var constant in constants)
            {
                sb.AppendLine($"        /// <summary>");
                sb.AppendLine($"        /// {constant.Key}");
                sb.AppendLine($"        /// </summary>");

                // Try to determine if it's a numeric constant
                if (int.TryParse(constant.Value, out int intValue))
                {
                    sb.AppendLine($"        public const int {constant.Key} = {intValue};");
                }
                else
                {
                    sb.AppendLine($"        public const string {constant.Key} = \"{constant.Value}\";");
                }
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}