




// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten

namespace Rathalos.Core.Protocol.Messages
{

    public enum TCONNSECENC
    {


        TCONNSECNONE = 0,


        TCONNSECTEA = 1,


        TCONNSECQQ = 2,


        TCONNSECAES = 3,


        /// <summary>
        /// 与TCONN_SEC_AES算法不同的是修改了数据填充算法
        /// </summary>

        TCONNSECAES2 = 4

    }
}