// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten

using System;
using System.Collections.Generic;
namespace Rathalos.Core.Protocol.Messages
{
    /// <summary>
    /// 重连请求包
    /// </summary>
    public class TPDUExtRelay : TPDUExt
    {

        /// <summary>
        /// Protocol identifier for this message type
        /// </summary>
        public const int ProtocolIdConst = (int)TPDU_CMD.TPDU_CMD_RELAY;
        public int ProtocolId => ProtocolIdConst;

        /// <summary>
        /// 通信加解密类型 (version:11)
        /// </summary>
        public int EncMethod { get; set; }
        /// <summary>
        /// 重连类型 (version:)
        /// </summary>
        public int RelayType { get; set; }
        /// <summary>
        /// 占位连接索引 (version:)
        /// </summary>
        public int OldPos { get; set; }
        /// <summary>
        /// 重连验证信息长度(密文) (version:)
        /// </summary>
        public int Len { get; set; }
        /// <summary>
        ///  (version:)
        /// </summary>
        public sbyte[] EncryptIdent { get; set; } = Array.Empty<sbyte>();
    }
}