// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten

using System;
using System.Collections.Generic;
namespace Rathalos.Core.Protocol.Messages
{
    /// <summary>
    /// 客户端真实地址信息
    /// </summary>
    public class TPDUExtClientAddr : TPDUExt
    {

        /// <summary>
        /// Protocol identifier for this message type
        /// </summary>
        public const int ProtocolIdConst = (int)TPDU_CMD.TPDU_CMD_CLIENT_ADDR;
        public int ProtocolId => ProtocolIdConst;

        /// <summary>
        /// Uin (version:)
        /// </summary>
        public uint Uin { get; set; }
        /// <summary>
        /// IP地址 (version:)
        /// </summary>
        public uint IP { get; set; }
        /// <summary>
        /// 端口 (version:)
        /// </summary>
        public ushort Port { get; set; }
        /// <summary>
        /// 附加信息 (version:)
        /// </summary>
        public char[] ExtInfo { get; set; } = Array.Empty<char>();
    }
}