




// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten


using System;


namespace Rathalos.Core.Protocol.Messages
{

    /// <summary>
    /// 签名数据
    /// </summary>

    public interface TPDUExtAuthData
    {

    }
}