// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten

using System;
using System.Collections.Generic;
namespace Rathalos.Core.Protocol.Messages
{
    public class TPDUExtSyn : TPDUExt
    {

        /// <summary>
        /// Protocol identifier for this message type
        /// </summary>
        public const int ProtocolIdConst = (int)TPDU_CMD.TPDU_CMD_SYN;
        public int ProtocolId => ProtocolIdConst;

        /// <summary>
        /// 连接握手信息长度(密文) (version:)
        /// </summary>
        public byte Len { get; set; }
        /// <summary>
        ///  (version:)
        /// </summary>
        public sbyte[] EncryptSynInfo { get; set; } = Array.Empty<sbyte>();
    }
}