// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten

using System;
using System.Collections.Generic;

namespace Rathalos.Core.Protocol.Messages
{
    /// <summary>
    /// version14之前的包头
    /// </summary>
    public class TPDUHeadOld
    {

        /// <summary>
        /// 基础信息 (version:)
        /// </summary>
        public TPDUBaseOld Base { get; set; }
        /// <summary>
        /// 扩展信息 (version:)
        /// </summary>
        public TPDUExt Ext { get; set; }
    }
}