// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten

using System;
using System.Collections.Generic;
namespace Rathalos.Core.Protocol.Messages
{
    /// <summary>
    /// CS通信包= 明文:包头(基础信息+扩展信息)+密文:包体(附加头部信息+应用包
    /// </summary>
    public class TPDUFrame
    {

        /// <summary>
        ///  (version:)
        /// </summary>
        public TPDUHead Head { get; set; }
        /// <summary>
        ///  (version:)
        /// </summary>
        public sbyte Body { get; set; }
    }
}