



// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten

namespace Rathalos.Core.Protocol.Messages
{

    public enum TPDU_CMD
    {
    /// <summary>
    /// 通信包
    /// </summary>
    TPDU_CMD_NONE = 0,
    /// <summary>
    /// 交换密钥(下行)
    /// </summary>
    TPDU_CMD_CHGSKEY = 1,
    /// <summary>
    /// 排队信息(下行)
    /// </summary>
    TPDU_CMD_QUEINFO = 2,
    /// <summary>
    /// 签名请求信息(上行)
    /// </summary>
    TPDU_CMD_AUTH = 3,
    /// <summary>
    /// 连接建立(下行)
    /// </summary>
    TPDU_CMD_IDENT = 4,
    /// <summary>
    /// 未加密通信包(下行)
    /// </summary>
    TPDU_CMD_PLAIN = 5,
    /// <summary>
    /// 重连请求信息(上行)
    /// </summary>
    TPDU_CMD_RELAY = 6,
    /// <summary>
    /// 服务器断开连接下发错误码
    /// </summary>
    TPDU_CMD_STOP = 7,
    /// <summary>
    /// 连接握手信息(下行)
    /// </summary>
    TPDU_CMD_SYN = 8,
    /// <summary>
    /// 三次握手请求(上行)
    /// </summary>
    TPDU_CMD_SYNACK = 9,
    /// <summary>
    /// 查询密保返回结果(下行)
    /// </summary>
    TPDU_CMD_MBA_QUERYRSP = 10,
    /// <summary>
    /// 验证密保请求(上行)
    /// </summary>
    TPDU_CMD_MBA_VERIFYREQ = 11,
    /// <summary>
    /// 下发密保问题检验结果(下行)
    /// </summary>
    TPDU_CMD_MBA_VERIFYRSP = 12,
    /// <summary>
    /// 客户端关闭连接通知消息(上行)
    /// </summary>
    TPDU_CMD_CLOSE = 13,
    /// <summary>
    /// TGC发送的客户端真实地址消息(上行)
    /// </summary>
    TPDU_CMD_CLIENT_ADDR = 210,

    }
}