// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten

using System;
using System.Collections.Generic;
namespace Rathalos.Core.Protocol.Messages
{
    /// <summary>
    /// 密保相关透传buffer,密文
    /// </summary>
    public class TPDUExtMiBao : TPDUExt, TPDUExt, TPDUExt
    {

        /// <summary>
        /// Protocol identifier for this message type
        /// </summary>
        public const int ProtocolIdConst = (int)TPDU_CMD.TPDU_CMD_MBA_VERIFYRSP;
        public int ProtocolId => ProtocolIdConst;

        /// <summary>
        /// Protocol identifier for this message type
        /// </summary>
        public const int ProtocolIdConst = (int)TPDU_CMD.TPDU_CMD_MBA_VERIFYREQ;
        public int ProtocolId => ProtocolIdConst;

        /// <summary>
        /// Protocol identifier for this message type
        /// </summary>
        public const int ProtocolIdConst = (int)TPDU_CMD.TPDU_CMD_MBA_QUERYRSP;
        public int ProtocolId => ProtocolIdConst;

        /// <summary>
        /// buffer长度 (version:)
        /// </summary>
        public ushort Len { get; set; }
        /// <summary>
        ///  (version:)
        /// </summary>
        public byte[] MiBaoBuffer { get; set; } = Array.Empty<byte>();
    }
}