// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten

using System;
using System.Collections.Generic;
namespace Rathalos.Core.Protocol.Messages
{
    /// <summary>
    /// 0x82签名第一段
    /// </summary>
    public class TQQGameSig
    {

        /// <summary>
        ///  (version:)
        /// </summary>
        public char[] GameKey { get; set; } = Array.Empty<char>();
        /// <summary>
        ///  (version:)
        /// </summary>
        public char[] SvcBitmap { get; set; } = Array.Empty<char>();
        /// <summary>
        ///  (version:)
        /// </summary>
        public char[] SvcBitmapExt { get; set; } = Array.Empty<char>();
        /// <summary>
        ///  (version:)
        /// </summary>
        public uint ValidateBitmap { get; set; }
        /// <summary>
        ///  (version:)
        /// </summary>
        public uint Uin { get; set; }
        /// <summary>
        ///  (version:)
        /// </summary>
        public uint Time { get; set; }
        /// <summary>
        ///  (version:)
        /// </summary>
        public uint UinFlag { get; set; }
        /// <summary>
        /// 客户端IP (version:12)
        /// </summary>
        public uint ClientIP { get; set; }
    }
}