// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Modify note
    /// </summary>
    public class C2SGuilderNoteSetting : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.C2S_CMD_GUILD_GUILDERNOTESETTING;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Member
		/// </summary>
		public ulong Guilder { get; set; }
		/// <summary>
		/// Note
		/// </summary>
		public string Note { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteULong(Guilder);
			if (Note.Length != CsprotoConstants.CS_MAX_GUILD_NOTE_LEN)
			{
				throw new InvalidOperationException($"Array length of 'Note' should be of length of {CsprotoConstants.CS_MAX_GUILD_NOTE_LEN} but was {Note.Length}.");
			}

			writer.WriteUTF(Note);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Guilder = reader.ReadULong();
			Note = reader.ReadUTF();
		}

    }
}