// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Client->Server: Execute data operation request
    /// </summary>
    public class C2SScriptActivityDataExecReq : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.C2S_CMD_SACTIVITY_DATA_EXEC_REQ;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Activity ID
		/// </summary>
		public uint ID { get; set; } = 0;
		/// <summary>
		/// ID
		/// </summary>
		public byte DataEntryID { get; set; } = 0;
		/// <summary>
		/// Parameter 1
		/// </summary>
		public int Param1 { get; set; } = 0;
		/// <summary>
		/// Parameter 2
		/// </summary>
		public int Param2 { get; set; } = 0;

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteUInt(ID);
			writer.WriteByte(DataEntryID);
			writer.WriteInt(Param1);
			writer.WriteInt(Param2);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			ID = reader.ReadUInt();
			DataEntryID = reader.ReadByte();
			Param1 = reader.ReadInt();
			Param2 = reader.ReadInt();
		}

    }
}