// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Set custom speak
    /// </summary>
    public class C2SSpeakSetSelfDef : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.C2S_CMD_SPEAK_SETSELFDEF;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// ID
		/// </summary>
		public int Id { get; set; }
		/// <summary>
		/// Custom speak content
		/// </summary>
		public string Content { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(Id);
			if (Content.Length != CsprotoConstants.CS_SPEAK_SELF_DEFINE_LENGTH)
			{
				throw new InvalidOperationException($"Array length of 'Content' should be of length of {CsprotoConstants.CS_SPEAK_SELF_DEFINE_LENGTH} but was {Content.Length}.");
			}

			writer.WriteUTF(Content);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Id = reader.ReadInt();
			Content = reader.ReadUTF();
		}

    }
}