// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Set quick speak
    /// </summary>
    public class C2SSpeakSetQuick : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.C2S_CMD_SPEAK_SETQUICK;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Shortcut key
		/// </summary>
		public int Id { get; set; }
		/// <summary>
		/// Speak content
		/// </summary>
		public int Speak { get; set; }
		/// <summary>
		/// Type
		/// </summary>
		public byte Type { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(Id);
			writer.WriteInt(Speak);
			writer.WriteByte(Type);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Id = reader.ReadInt();
			Speak = reader.ReadInt();
			Type = reader.ReadByte();
		}

    }
}