// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Auto speak custom sentence
    /// </summary>
    public class C2SSpeakContent : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.C2S_CMD_SPEAK_CONTENT;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Text ID
		/// </summary>
		public int MsgId { get; set; }
		/// <summary>
		/// Custom speak content
		/// </summary>
		public string Content { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(MsgId);
			if (Content.Length > (CsprotoConstants.CS_SPEAK_SELF_DEFINE_LENGTH - 1))
			{
				throw new InvalidOperationException($"String length of 'Content' should be of length of {(CsprotoConstants.CS_SPEAK_SELF_DEFINE_LENGTH - 1)} but was {Content.Length}.");
			}

			writer.WriteUTF(Content);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			MsgId = reader.ReadInt();
			Content = reader.ReadUTF();
		}

    }
}