// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    public class C2SSoulBeastExpShift : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.C2S_CMD_SOULBEAST_EXP_SHIFT_REQ;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Source beast
		/// </summary>
		public int SrcBeast { get; set; }
		/// <summary>
		/// Target beast
		/// </summary>
		public int DstBeast { get; set; }
		/// <summary>
		/// 0: hunt coins/points; 1: free item
		/// </summary>
		public int UseItem { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(SrcBeast);
			writer.WriteInt(DstBeast);
			writer.WriteInt(UseItem);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			SrcBeast = reader.ReadInt();
			DstBeast = reader.ReadInt();
			UseItem = reader.ReadInt();
		}

    }
}