// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Track task
    /// </summary>
    public class C2STraceTask : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.C2S_CMD_TASK_TRACETASK;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Task
		/// </summary>
		public int Task { get; set; }
		/// <summary>
		/// Whether to track
		/// </summary>
		public byte Trace { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(Task);
			writer.WriteByte(Trace);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Task = reader.ReadInt();
			Trace = reader.ReadByte();
		}

    }
}