// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Search player
    /// </summary>
    public class C2STournamentsSearchPlayer : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.C2S_CMD_TOURNAMENTS_SEARCHPLAYER;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Column ID
		/// </summary>
		public int Id { get; set; }
		/// <summary>
		/// Name
		/// </summary>
		public string Name { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(Id);
			if (Name.Length > (CsprotoConstants.CS_MAX_ROLE_NAME - 1))
			{
				throw new InvalidOperationException($"String length of 'Name' should be of length of {(CsprotoConstants.CS_MAX_ROLE_NAME - 1)} but was {Name.Length}.");
			}

			writer.WriteUTF(Name);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Id = reader.ReadInt();
			Name = reader.ReadUTF();
		}

    }
}