// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    public class CRole
    {
		public ulong Gid { get; set; }
		public string Str { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteULong(Gid);
			if (Str.Length > (CsprotoConstants.CS_MAIL_NAME_MAX_LEN - 1))
			{
				throw new InvalidOperationException($"String length of 'Str' should be of length of {(CsprotoConstants.CS_MAIL_NAME_MAX_LEN - 1)} but was {Str.Length}.");
			}

			writer.WriteUTF(Str);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Gid = reader.ReadULong();
			Str = reader.ReadUTF();
		}

    }
}