// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Start move message
    /// </summary>
    public class CSActorBeginmoveNtf : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_BATTLE_ACTOR_BEGINMOVE_NTF;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// NetObjId of Actor to sync
		/// </summary>
		public uint NetObjId { get; set; }
		/// <summary>
		/// Start move message
		/// </summary>
		public CSActorBeginmove ActorBeginmove { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteUInt(NetObjId);
			ActorBeginmove?.Serialize(writer);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			NetObjId = reader.ReadUInt();
			ActorBeginmove = new CSActorBeginmove();
			ActorBeginmove.Deserialize(reader);
		}

    }
}