// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Activity base reward
    /// </summary>
    public class CSActivityBaseReward
    {
		/// <summary>
		/// Experience
		/// </summary>
		public int AddExp { get; set; }
		/// <summary>
		/// Bound silver
		/// </summary>
		public int AddBindGold { get; set; }
		/// <summary>
		/// Gold coins
		/// </summary>
		public int AddUnBindGold { get; set; }
		/// <summary>
		/// Farm calculation points
		/// </summary>
		public int AddFarmPoint { get; set; }
		/// <summary>
		/// Guild arena points
		/// </summary>
		public int GuildAthPoint { get; set; }
		/// <summary>
		/// Pet experience
		/// </summary>
		public int AddPetExp { get; set; }
		/// <summary>
		/// Pet affection
		/// </summary>
		public int PetRoyalPoint { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(AddExp);
			writer.WriteInt(AddBindGold);
			writer.WriteInt(AddUnBindGold);
			writer.WriteInt(AddFarmPoint);
			writer.WriteInt(GuildAthPoint);
			writer.WriteInt(AddPetExp);
			writer.WriteInt(PetRoyalPoint);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			AddExp = reader.ReadInt();
			AddBindGold = reader.ReadInt();
			AddUnBindGold = reader.ReadInt();
			AddFarmPoint = reader.ReadInt();
			GuildAthPoint = reader.ReadInt();
			AddPetExp = reader.ReadInt();
			PetRoyalPoint = reader.ReadInt();
		}

    }
}