// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Skill position sync message
    /// </summary>
    public class CSActorSkillPos : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_BATTLE_ACTOR_SKILLPOS;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// NetObjId
		/// </summary>
		public uint NetObjId { get; set; }
		/// <summary>
		/// Current state ID
		/// </summary>
		public uint StateID { get; set; }
		/// <summary>
		/// Skill time
		/// </summary>
		public float CurTime { get; set; }
		/// <summary>
		/// Position in world coordinates
		/// </summary>
		public CSVec3 Location { get; set; }
		/// <summary>
		/// Flag
		/// </summary>
		public ushort Flag { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteUInt(NetObjId);
			writer.WriteUInt(StateID);
			writer.WriteFloat(CurTime);
			Location?.Serialize(writer);
			writer.WriteUShort(Flag);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			NetObjId = reader.ReadUInt();
			StateID = reader.ReadUInt();
			CurTime = reader.ReadFloat();
			Location = new CSVec3();
			Location.Deserialize(reader);
			Flag = reader.ReadUShort();
		}

    }
}