// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// AG sync info
    /// </summary>
    public class CSAGSyncInfo : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_BATTLE_ACTOR_AG_SYNC;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// EntityId of Actor to sync
		/// </summary>
		public uint EntityId { get; set; }
		/// <summary>
		/// AGLayerID
		/// </summary>
		public byte Layer { get; set; }
		/// <summary>
		/// AGInput type, 0-int, 1-float
		/// </summary>
		public byte InputType { get; set; }
		/// <summary>
		/// AGInput
		/// </summary>
		public byte Input { get; set; }
		/// <summary>
		/// AGInput value
		/// </summary>
		public uint Value { get; set; }
		/// <summary>
		/// Current state ID
		/// </summary>
		public uint StateID { get; set; }
		/// <summary>
		/// Current state ratio
		/// </summary>
		public float Ratio { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteUInt(EntityId);
			writer.WriteByte(Layer);
			writer.WriteByte(InputType);
			writer.WriteByte(Input);
			writer.WriteUInt(Value);
			writer.WriteUInt(StateID);
			writer.WriteFloat(Ratio);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			EntityId = reader.ReadUInt();
			Layer = reader.ReadByte();
			InputType = reader.ReadByte();
			Input = reader.ReadByte();
			Value = reader.ReadUInt();
			StateID = reader.ReadUInt();
			Ratio = reader.ReadFloat();
		}

    }
}