// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Entrust level list response
    /// </summary>
    public class CSAllEntrustLevelListRsp : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_ALL_ENTRUST_LEVEL_LIST_RSP;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Error code
		/// </summary>
		public int ErrCode { get; set; }
		public CSEnGroupInfo[] GroupInfos { get; set; } = Array.Empty<CSEnGroupInfo>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(ErrCode);
			// Write length for array: GroupInfos
			var GroupCount = (short)(GroupInfos?.Length ?? 0);
			if (GroupCount > CsprotoConstants.CS_MAX_EN_LEVEL_GROUP_COUNT)
			{
				throw new InvalidOperationException($"Array length of 'GroupInfos' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_EN_LEVEL_GROUP_COUNT} but was {GroupCount}.");
			}

			writer.WriteShort(GroupCount);
			for (var i = 0; i < GroupCount; i++)
			{
				GroupInfos[i]?.Serialize(writer);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			ErrCode = reader.ReadInt();
			// Read length for array: GroupInfos
			var GroupCount = reader.ReadShort();
			// Read array: GroupInfos
			GroupInfos = new CSEnGroupInfo[Math.Min((int)GroupCount, CsprotoConstants.CS_MAX_EN_LEVEL_GROUP_COUNT)];
			for (var i = 0; i < GroupInfos.Length; i++)
			{
				GroupInfos[i] = new CSEnGroupInfo();
				GroupInfos[i].Deserialize(reader);
			}
		}

    }
}