// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// ammo info
    /// </summary>
    public class CSAmmoInfo
    {
		/// <summary>
		/// logic entity id
		/// </summary>
		public int NetID { get; set; }
		/// <summary>
		/// ammo type id
		/// </summary>
		public int TypeID { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(NetID);
			writer.WriteInt(TypeID);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			NetID = reader.ReadInt();
			TypeID = reader.ReadInt();
		}

    }
}