// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Attribute info
    /// </summary>
    public class CSAttrInitInfo : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_ATTR_INIT_NTF;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		public byte[] Attr { get; set; } = Array.Empty<byte>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			// Write length for array: Attr
			var AttrSize = (ushort)(Attr?.Length ?? 0);
			if (AttrSize > CsprotoConstants.CS_MAX_ATTR_DATA_LEN)
			{
				throw new InvalidOperationException($"Array length of 'Attr' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_ATTR_DATA_LEN} but was {AttrSize}.");
			}

			writer.WriteUShort(AttrSize);
			for (var i = 0; i < AttrSize; i++)
			{
				writer.WriteByte(Attr[i]);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			// Read length for array: Attr
			var AttrSize = reader.ReadUShort();
			// Read array: Attr
			Attr = new byte[Math.Min((int)AttrSize, CsprotoConstants.CS_MAX_ATTR_DATA_LEN)];
			for (var i = 0; i < Attr.Length; i++)
			{
				Attr[i] = reader.ReadByte();
			}
		}

    }
}