// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    public class CSAttrSyncList : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_ATTR_SYNC_LIST_NTF;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Variable value
		/// </summary>
		public CSAttrSync[] Attr { get; set; } = Array.Empty<CSAttrSync>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			// Write length for array: Attr
			var Count = (int)(Attr?.Length ?? 0);
			if (Count > CsprotoConstants.CS_ATTR_SYNC_LIST_MAX)
			{
				throw new InvalidOperationException($"Array length of 'Attr' exceeds maximum allowed length of {CsprotoConstants.CS_ATTR_SYNC_LIST_MAX} but was {Count}.");
			}

			writer.WriteInt(Count);
			for (var i = 0; i < Count; i++)
			{
				Attr[i]?.Serialize(writer);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			// Read length for array: Attr
			var Count = reader.ReadInt();
			// Read array: Attr
			Attr = new CSAttrSync[Math.Min((int)Count, CsprotoConstants.CS_ATTR_SYNC_LIST_MAX)];
			for (var i = 0; i < Attr.Length; i++)
			{
				Attr[i] = new CSAttrSync();
				Attr[i].Deserialize(reader);
			}
		}

    }
}