// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Bidding request
    /// </summary>
    public class CSAuctionBiddingReq : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_AUCTION_BIDDING_REQ;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Record ID
		/// </summary>
		public ulong RecordId { get; set; }
		/// <summary>
		/// Price
		/// </summary>
		public uint Price { get; set; }
		/// <summary>
		/// Item ID
		/// </summary>
		public uint Itemid { get; set; }
		/// <summary>
		/// Item count
		/// </summary>
		public uint Itemnum { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteULong(RecordId);
			writer.WriteUInt(Price);
			writer.WriteUInt(Itemid);
			writer.WriteUInt(Itemnum);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			RecordId = reader.ReadULong();
			Price = reader.ReadUInt();
			Itemid = reader.ReadUInt();
			Itemnum = reader.ReadUInt();
		}

    }
}