// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Role equipment display item
    /// </summary>
    public class CSAvatarItem
    {
		/// <summary>
		/// Item type
		/// </summary>
		public int ItemType { get; set; }
		/// <summary>
		/// Item position row
		/// </summary>
		public ushort PosIndex { get; set; }
		/// <summary>
		/// Rank level
		/// </summary>
		public uint Rank { get; set; }
		/// <summary>
		/// Enhance rule
		/// </summary>
		public byte EnhanceRule { get; set; }
		/// <summary>
		/// Enhance data
		/// </summary>
		public byte EnhanceLevel { get; set; }
		/// <summary>
		/// Socket count
		/// </summary>
		public byte SoltCount { get; set; }
		/// <summary>
		/// Socket gem item
		/// </summary>
		public uint GemID { get; set; }
		/// <summary>
		/// Breakthrough level
		/// </summary>
		public byte BreakLevel { get; set; }
		/// <summary>
		/// Dye effect
		/// </summary>
		public byte ColorIndex { get; set; }
		/// <summary>
		/// Transmog effect
		/// </summary>
		public uint FakeShow { get; set; }
		/// <summary>
		/// Awakening tier
		/// </summary>
		public byte WakeLevel { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(ItemType);
			writer.WriteUShort(PosIndex);
			writer.WriteUInt(Rank);
			writer.WriteByte(EnhanceRule);
			writer.WriteByte(EnhanceLevel);
			writer.WriteByte(SoltCount);
			writer.WriteUInt(GemID);
			writer.WriteByte(BreakLevel);
			writer.WriteByte(ColorIndex);
			writer.WriteUInt(FakeShow);
			writer.WriteByte(WakeLevel);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			ItemType = reader.ReadInt();
			PosIndex = reader.ReadUShort();
			Rank = reader.ReadUInt();
			EnhanceRule = reader.ReadByte();
			EnhanceLevel = reader.ReadByte();
			SoltCount = reader.ReadByte();
			GemID = reader.ReadUInt();
			BreakLevel = reader.ReadByte();
			ColorIndex = reader.ReadByte();
			FakeShow = reader.ReadUInt();
			WakeLevel = reader.ReadByte();
		}

    }
}