// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Battle damage message
    /// </summary>
    public class CSBattlePVPDMG : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_BATTLE_PVP_DMG;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Sync time
		/// </summary>
		public long SyncTime { get; set; }
		/// <summary>
		/// Sequence
		/// </summary>
		public long Sequence { get; set; }
		/// <summary>
		/// Hit info
		/// </summary>
		public CSBattleDMG HitInfo { get; set; }
		/// <summary>
		/// Hit result
		/// </summary>
		public CSDMGResult DamageResult { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteLong(SyncTime);
			writer.WriteLong(Sequence);
			HitInfo?.Serialize(writer);
			DamageResult?.Serialize(writer);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			SyncTime = reader.ReadLong();
			Sequence = reader.ReadLong();
			HitInfo = new CSBattleDMG();
			HitInfo.Deserialize(reader);
			DamageResult = new CSDMGResult();
			DamageResult.Deserialize(reader);
		}

    }
}