// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Level target info
    /// </summary>
    public class CSBattleTargetInfo
    {
		/// <summary>
		/// Target ID
		/// </summary>
		public int TargetID { get; set; }
		/// <summary>
		/// Sub condition ID
		/// </summary>
		public int ConditionID { get; set; }
		/// <summary>
		/// Current completed count
		/// </summary>
		public int CurCount { get; set; }
		/// <summary>
		/// State
		/// </summary>
		public int State { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(TargetID);
			writer.WriteInt(ConditionID);
			writer.WriteInt(CurCount);
			writer.WriteInt(State);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			TargetID = reader.ReadInt();
			ConditionID = reader.ReadInt();
			CurCount = reader.ReadInt();
			State = reader.ReadInt();
		}

    }
}