// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    public class CSBattlePunishNtf : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_BATTLE_PUNISH_NTF;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Player info
		/// </summary>
		public CSBattlePunishInfo[] PlayereInfo { get; set; } = Array.Empty<CSBattlePunishInfo>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			// Write length for array: PlayereInfo
			var PlayerNum = (int)(PlayereInfo?.Length ?? 0);
			if (PlayerNum > CsprotoConstants.CS_MAX_PVE_PLAYER_COUNT)
			{
				throw new InvalidOperationException($"Array length of 'PlayereInfo' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_PVE_PLAYER_COUNT} but was {PlayerNum}.");
			}

			writer.WriteInt(PlayerNum);
			for (var i = 0; i < PlayerNum; i++)
			{
				PlayereInfo[i]?.Serialize(writer);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			// Read length for array: PlayereInfo
			var PlayerNum = reader.ReadInt();
			// Read array: PlayereInfo
			PlayereInfo = new CSBattlePunishInfo[Math.Min((int)PlayerNum, CsprotoConstants.CS_MAX_PVE_PLAYER_COUNT)];
			for (var i = 0; i < PlayereInfo.Length; i++)
			{
				PlayereInfo[i] = new CSBattlePunishInfo();
				PlayereInfo[i].Deserialize(reader);
			}
		}

    }
}