// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Level target info list
    /// </summary>
    public class CSBattleTargetList : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_BATTLE_TARGET_LIST_NTF;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Target info
		/// </summary>
		public CSBattleTargetInfo[] TargetInfos { get; set; } = Array.Empty<CSBattleTargetInfo>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			// Write length for array: TargetInfos
			var InfoCount = (short)(TargetInfos?.Length ?? 0);
			if (InfoCount > CsprotoConstants.CS_MAX_BATTLE_TARGET_COUNT)
			{
				throw new InvalidOperationException($"Array length of 'TargetInfos' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_BATTLE_TARGET_COUNT} but was {InfoCount}.");
			}

			writer.WriteShort(InfoCount);
			for (var i = 0; i < InfoCount; i++)
			{
				TargetInfos[i]?.Serialize(writer);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			// Read length for array: TargetInfos
			var InfoCount = reader.ReadShort();
			// Read array: TargetInfos
			TargetInfos = new CSBattleTargetInfo[Math.Min((int)InfoCount, CsprotoConstants.CS_MAX_BATTLE_TARGET_COUNT)];
			for (var i = 0; i < TargetInfos.Length; i++)
			{
				TargetInfos[i] = new CSBattleTargetInfo();
				TargetInfos[i].Deserialize(reader);
			}
		}

    }
}