// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Blackboard variable
    /// </summary>
    public class CSBBVar
    {
		/// <summary>
		/// Type enum
		/// </summary>
		public CS_BBVALUE_TYPE Type { get; set; }
		/// <summary>
		/// Variable name
		/// </summary>
		public string Name { get; set; }
		/// <summary>
		/// Variable value
		/// </summary>
		public CSBBVariable Value { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteUShort((ushort)Type);
			if (Name.Length > (CsprotoConstants.CS_MAX_LENGTH_FOR_OBJ_STATENAME - 1))
			{
				throw new InvalidOperationException($"String length of 'Name' should be of length of {(CsprotoConstants.CS_MAX_LENGTH_FOR_OBJ_STATENAME - 1)} but was {Name.Length}.");
			}

			writer.WriteUTF(Name);
			// Selected by: Type
			Value?.Serialize(writer);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Type = (CS_BBVALUE_TYPE)reader.ReadUShort();
			Name = reader.ReadUTF();
			// Selected by: Type
			Value = ProtocolTypeManager.Get<CSBBVariable>(Type);
			Value.Deserialize(reader);
		}

    }
}