// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Gathering loot result
    /// </summary>
    public class CSBeginLootResult : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_LOOT_BEGINLOOTRESULT;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Gathering result
		/// </summary>
		public uint Result { get; set; }
		/// <summary>
		/// Entity ID
		/// </summary>
		public uint LogicEntityId { get; set; }
		/// <summary>
		/// Remaining gather count
		/// </summary>
		public int LootTimesRemain { get; set; }
		/// <summary>
		/// Item ID
		/// </summary>
		public CSInstanceItemLootInfo[] Item { get; set; } = Array.Empty<CSInstanceItemLootInfo>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteUInt(Result);
			writer.WriteUInt(LogicEntityId);
			writer.WriteInt(LootTimesRemain);
			// Write length for array: Item
			var ItemCount = (int)(Item?.Length ?? 0);
			if (ItemCount > CsprotoConstants.CS_MAX_LOOT_ITEMS)
			{
				throw new InvalidOperationException($"Array length of 'Item' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_LOOT_ITEMS} but was {ItemCount}.");
			}

			writer.WriteInt(ItemCount);
			for (var i = 0; i < ItemCount; i++)
			{
				Item[i]?.Serialize(writer);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Result = reader.ReadUInt();
			LogicEntityId = reader.ReadUInt();
			LootTimesRemain = reader.ReadInt();
			// Read length for array: Item
			var ItemCount = reader.ReadInt();
			// Read array: Item
			Item = new CSInstanceItemLootInfo[Math.Min((int)ItemCount, CsprotoConstants.CS_MAX_LOOT_ITEMS)];
			for (var i = 0; i < Item.Length; i++)
			{
				Item[i] = new CSInstanceItemLootInfo();
				Item[i].Deserialize(reader);
			}
		}

    }
}