// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    public class CSBTDebugBSListReq : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_DEBUGSERVICE_BS_LIST_REQ;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		public uint Index { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteUInt(Index);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Index = reader.ReadUInt();
		}

    }
}