// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Server notify condition
    /// </summary>
    public class CSBuffCondition : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_BUFF_CONDITION_CHG;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Entity ID
		/// </summary>
		public uint EntityId { get; set; }
		/// <summary>
		/// Unique ID
		/// </summary>
		public int UniqueID { get; set; }
		/// <summary>
		/// Whether effective
		/// </summary>
		public char Enable { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteUInt(EntityId);
			writer.WriteInt(UniqueID);
			writer.WriteChar(Enable);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			EntityId = reader.ReadUInt();
			UniqueID = reader.ReadInt();
			Enable = reader.ReadChar();
		}

    }
}