// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    public class CSCatCuisineUnlockStateChangeRsp : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_CATCUISINE_UNLOCK_CHANGE_STATE_RSP;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Error code
		/// </summary>
		public int ErrCode { get; set; }
		/// <summary>
		/// Cat cuisine ID
		/// </summary>
		public int Id { get; set; }
		/// <summary>
		/// Cat cuisine unlock state
		/// </summary>
		public int State { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(ErrCode);
			writer.WriteInt(Id);
			writer.WriteInt(State);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			ErrCode = reader.ReadInt();
			Id = reader.ReadInt();
			State = reader.ReadInt();
		}

    }
}