// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Check version response
    /// </summary>
    public class CSCheckVersionRsp : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_CHECK_VERSION_RSP;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Error code
		/// </summary>
		public int ErrNo { get; set; }
		/// <summary>
		/// Server major version, for testing, may remove in production to prevent cheating
		/// </summary>
		public int MajorVerNo { get; set; }
		/// <summary>
		/// Server minor version, for testing, may remove in production to prevent cheating
		/// </summary>
		public int MinorVerNo { get; set; }
		/// <summary>
		/// Server revision version, for testing, may remove in production to prevent cheating
		/// </summary>
		public int RevisVerNo { get; set; }
		/// <summary>
		/// Server build version, for testing, may remove in production to prevent cheating
		/// </summary>
		public int BuildVerNo { get; set; }
		/// <summary>
		/// Feature
		/// </summary>
		public CSFeatureInfo Feature { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(ErrNo);
			writer.WriteInt(MajorVerNo);
			writer.WriteInt(MinorVerNo);
			writer.WriteInt(RevisVerNo);
			writer.WriteInt(BuildVerNo);
			Feature?.Serialize(writer);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			ErrNo = reader.ReadInt();
			MajorVerNo = reader.ReadInt();
			MinorVerNo = reader.ReadInt();
			RevisVerNo = reader.ReadInt();
			BuildVerNo = reader.ReadInt();
			Feature = new CSFeatureInfo();
			Feature.Deserialize(reader);
		}

    }
}