// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Charm smelting request
    /// </summary>
    public class CSCharmRebuildReq : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.C2S_CMD_ITEMREBUILD_CHARM_REBUILD_REQ;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Material list
		/// </summary>
		public CSItemArgs[] Items { get; set; } = Array.Empty<CSItemArgs>();
		/// <summary>
		/// Whether bound, 0 uses gold 1 uses silver
		/// </summary>
		public byte BBind { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			// Write length for array: Items
			var ItemCount = (int)(Items?.Length ?? 0);
			if (ItemCount > CsprotoConstants.CS_ITEM_REBUILD_CHARM_MAX)
			{
				throw new InvalidOperationException($"Array length of 'Items' exceeds maximum allowed length of {CsprotoConstants.CS_ITEM_REBUILD_CHARM_MAX} but was {ItemCount}.");
			}

			writer.WriteInt(ItemCount);
			for (var i = 0; i < ItemCount; i++)
			{
				Items[i]?.Serialize(writer);
			}
			writer.WriteByte(BBind);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			// Read length for array: Items
			var ItemCount = reader.ReadInt();
			// Read array: Items
			Items = new CSItemArgs[Math.Min((int)ItemCount, CsprotoConstants.CS_ITEM_REBUILD_CHARM_MAX)];
			for (var i = 0; i < Items.Length; i++)
			{
				Items[i] = new CSItemArgs();
				Items[i].Deserialize(reader);
			}
			BBind = reader.ReadByte();
		}

    }
}