// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Client chat query target player info response
    /// </summary>
    public class CSChatTargetQueryRsp : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_CHAT_TARGET_QUERY_RSP;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Player role name
		/// </summary>
		public string Name { get; set; }
		/// <summary>
		/// Player normal level
		/// </summary>
		public int Level { get; set; }
		/// <summary>
		/// Player guild name
		/// </summary>
		public string GuildName { get; set; }
		/// <summary>
		/// Player hunter star level
		/// </summary>
		public string HunterStar { get; set; }
		/// <summary>
		/// Player HR level
		/// </summary>
		public int HRLevel { get; set; }
		/// <summary>
		/// Target player line ID
		/// </summary>
		public int LineID { get; set; }
		/// <summary>
		/// VIP level
		/// </summary>
		public byte VipLevel { get; set; }
		/// <summary>
		/// VIP available
		/// </summary>
		public byte VipCanUse { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			if (Name.Length > (CsprotoConstants.CS_MAX_ROLE_NAME - 1))
			{
				throw new InvalidOperationException($"String length of 'Name' should be of length of {(CsprotoConstants.CS_MAX_ROLE_NAME - 1)} but was {Name.Length}.");
			}

			writer.WriteUTF(Name);
			writer.WriteInt(Level);
			if (GuildName.Length > (CsprotoConstants.CS_MAX_GUILD_NAME_LEN - 1))
			{
				throw new InvalidOperationException($"String length of 'GuildName' should be of length of {(CsprotoConstants.CS_MAX_GUILD_NAME_LEN - 1)} but was {GuildName.Length}.");
			}

			writer.WriteUTF(GuildName);
			if (HunterStar.Length > (CsprotoConstants.CS_MAX_GUILD_HUNTERSTAR_LEN - 1))
			{
				throw new InvalidOperationException($"String length of 'HunterStar' should be of length of {(CsprotoConstants.CS_MAX_GUILD_HUNTERSTAR_LEN - 1)} but was {HunterStar.Length}.");
			}

			writer.WriteUTF(HunterStar);
			writer.WriteInt(HRLevel);
			writer.WriteInt(LineID);
			writer.WriteByte(VipLevel);
			writer.WriteByte(VipCanUse);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Name = reader.ReadUTF();
			Level = reader.ReadInt();
			GuildName = reader.ReadUTF();
			HunterStar = reader.ReadUTF();
			HRLevel = reader.ReadInt();
			LineID = reader.ReadInt();
			VipLevel = reader.ReadByte();
			VipCanUse = reader.ReadByte();
		}

    }
}