// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// System prompt request
    /// </summary>
    public class CSChatSystemMsgReq : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_CHAT_SYSTEM_MSG_REQ;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// MessageList.xlsx config item
		/// </summary>
		public uint MsgType { get; set; }
		/// <summary>
		/// Notification area (personal/server-wide/...)
		/// </summary>
		public uint MsgArea { get; set; }
		/// <summary>
		/// Player dbid
		/// </summary>
		public ulong Dbid { get; set; }
		/// <summary>
		/// Parameter count
		/// </summary>
		public byte MsgParamNum { get; set; }
		/// <summary>
		/// Parameter list
		/// </summary>
		public CSMsgParam[] MsgPramList { get; set; } = Array.Empty<CSMsgParam>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteUInt(MsgType);
			writer.WriteUInt(MsgArea);
			writer.WriteULong(Dbid);
			writer.WriteByte(MsgParamNum);
			if ((MsgPramList?.Length ?? 0) != CsprotoConstants.CS_CHAT_SYSTEM_MSG_PARAM_NUM)
			{
				throw new InvalidOperationException($"Array length of 'MsgPramList' should be of length of {CsprotoConstants.CS_CHAT_SYSTEM_MSG_PARAM_NUM} but was {(MsgPramList?.Length ?? 0)}.");
			}

			for (var i = 0; i < CsprotoConstants.CS_CHAT_SYSTEM_MSG_PARAM_NUM; i++)
			{
				MsgPramList[i]?.Serialize(writer);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			MsgType = reader.ReadUInt();
			MsgArea = reader.ReadUInt();
			Dbid = reader.ReadULong();
			MsgParamNum = reader.ReadByte();
			// Read array: MsgPramList
			MsgPramList = new CSMsgParam[CsprotoConstants.CS_CHAT_SYSTEM_MSG_PARAM_NUM];
			for (var i = 0; i < MsgPramList.Length; i++)
			{
				MsgPramList[i] = new CSMsgParam();
				MsgPramList[i].Deserialize(reader);
			}
		}

    }
}