// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Daily
    /// </summary>
    public class CSDaily
    {
		/// <summary>
		/// Refresh time
		/// </summary>
		public uint RefreshTime { get; set; }
		/// <summary>
		/// Library
		/// </summary>
		public int Lib { get; set; }
		/// <summary>
		/// Task set
		/// </summary>
		public short[] Task { get; set; } = Array.Empty<short>();
		/// <summary>
		/// Complete count
		/// </summary>
		public int CompleteCount { get; set; }
		/// <summary>
		/// Remaining completable count
		/// </summary>
		public int RemainCount { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteUInt(RefreshTime);
			writer.WriteInt(Lib);
			// Write length for array: Task
			var TaskCount = (short)(Task?.Length ?? 0);
			if (TaskCount > CsprotoConstants.CS_MAX_TASK_LIB_DAILY_TASK_LEN)
			{
				throw new InvalidOperationException($"Array length of 'Task' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_TASK_LIB_DAILY_TASK_LEN} but was {TaskCount}.");
			}

			writer.WriteShort(TaskCount);
			for (var i = 0; i < TaskCount; i++)
			{
				writer.WriteShort(Task[i]);
			}
			writer.WriteInt(CompleteCount);
			writer.WriteInt(RemainCount);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			RefreshTime = reader.ReadUInt();
			Lib = reader.ReadInt();
			// Read length for array: Task
			var TaskCount = reader.ReadShort();
			// Read array: Task
			Task = new short[Math.Min((int)TaskCount, CsprotoConstants.CS_MAX_TASK_LIB_DAILY_TASK_LEN)];
			for (var i = 0; i < Task.Length; i++)
			{
				Task[i] = reader.ReadShort();
			}
			CompleteCount = reader.ReadInt();
			RemainCount = reader.ReadInt();
		}

    }
}