// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Client to server hit behavior verify context
    /// </summary>
    public class CSDMGVerifyContext : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_BATTLE_DMG_VERIFY;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Sync time
		/// </summary>
		public long SyncTime { get; set; }
		/// <summary>
		/// Sequence
		/// </summary>
		public long Sequence { get; set; }
		/// <summary>
		/// Attacker position and rotation when hit occurs
		/// </summary>
		public CSQuatT AttackerEntityPos { get; set; }
		/// <summary>
		/// Attacker animation queue group
		/// </summary>
		public CSTransitionQueue[] AttackerLayers { get; set; } = Array.Empty<CSTransitionQueue>();
		/// <summary>
		/// Target position and rotation when hit occurs
		/// </summary>
		public CSQuatT AttackeeEntityPos { get; set; }
		/// <summary>
		/// Target animation queue group
		/// </summary>
		public CSTransitionQueue[] AttackeeLayers { get; set; } = Array.Empty<CSTransitionQueue>();
		/// <summary>
		/// Hit info
		/// </summary>
		public CSBattleDMG HitInfo { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteLong(SyncTime);
			writer.WriteLong(Sequence);
			AttackerEntityPos?.Serialize(writer);
			// Write length for array: AttackerLayers
			var AttackerLayersCount = (short)(AttackerLayers?.Length ?? 0);
			if (AttackerLayersCount > CsprotoConstants.CS_MAX_ANIM_LAYERS)
			{
				throw new InvalidOperationException($"Array length of 'AttackerLayers' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_ANIM_LAYERS} but was {AttackerLayersCount}.");
			}

			writer.WriteShort(AttackerLayersCount);
			for (var i = 0; i < AttackerLayersCount; i++)
			{
				AttackerLayers[i]?.Serialize(writer);
			}
			AttackeeEntityPos?.Serialize(writer);
			// Write length for array: AttackeeLayers
			var AttackeeLayersCount = (short)(AttackeeLayers?.Length ?? 0);
			if (AttackeeLayersCount > CsprotoConstants.CS_MAX_ANIM_LAYERS)
			{
				throw new InvalidOperationException($"Array length of 'AttackeeLayers' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_ANIM_LAYERS} but was {AttackeeLayersCount}.");
			}

			writer.WriteShort(AttackeeLayersCount);
			for (var i = 0; i < AttackeeLayersCount; i++)
			{
				AttackeeLayers[i]?.Serialize(writer);
			}
			HitInfo?.Serialize(writer);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			SyncTime = reader.ReadLong();
			Sequence = reader.ReadLong();
			AttackerEntityPos = new CSQuatT();
			AttackerEntityPos.Deserialize(reader);
			// Read length for array: AttackerLayers
			var AttackerLayersCount = reader.ReadShort();
			// Read array: AttackerLayers
			AttackerLayers = new CSTransitionQueue[Math.Min((int)AttackerLayersCount, CsprotoConstants.CS_MAX_ANIM_LAYERS)];
			for (var i = 0; i < AttackerLayers.Length; i++)
			{
				AttackerLayers[i] = new CSTransitionQueue();
				AttackerLayers[i].Deserialize(reader);
			}
			AttackeeEntityPos = new CSQuatT();
			AttackeeEntityPos.Deserialize(reader);
			// Read length for array: AttackeeLayers
			var AttackeeLayersCount = reader.ReadShort();
			// Read array: AttackeeLayers
			AttackeeLayers = new CSTransitionQueue[Math.Min((int)AttackeeLayersCount, CsprotoConstants.CS_MAX_ANIM_LAYERS)];
			for (var i = 0; i < AttackeeLayers.Length; i++)
			{
				AttackeeLayers[i] = new CSTransitionQueue();
				AttackeeLayers[i].Deserialize(reader);
			}
			HitInfo = new CSBattleDMG();
			HitInfo.Deserialize(reader);
		}

    }
}