// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Small shop buy request
    /// </summary>
    public class CSDragonBoxBuyReq : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_DRAGONBOX_BUY_REQ;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Box type
		/// </summary>
		public int BoxID { get; set; }
		/// <summary>
		/// Purchase item list
		/// </summary>
		public CSItemBoxItemEntry[] ItemList { get; set; } = Array.Empty<CSItemBoxItemEntry>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(BoxID);
			// Write length for array: ItemList
			var ItemCount = (int)(ItemList?.Length ?? 0);
			if (ItemCount > CsprotoConstants.CS_MAX_DRAGON_BOX_SHOPITEM_LEN)
			{
				throw new InvalidOperationException($"Array length of 'ItemList' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_DRAGON_BOX_SHOPITEM_LEN} but was {ItemCount}.");
			}

			writer.WriteInt(ItemCount);
			for (var i = 0; i < ItemCount; i++)
			{
				ItemList[i]?.Serialize(writer);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			BoxID = reader.ReadInt();
			// Read length for array: ItemList
			var ItemCount = reader.ReadInt();
			// Read array: ItemList
			ItemList = new CSItemBoxItemEntry[Math.Min((int)ItemCount, CsprotoConstants.CS_MAX_DRAGON_BOX_SHOPITEM_LEN)];
			for (var i = 0; i < ItemList.Length; i++)
			{
				ItemList[i] = new CSItemBoxItemEntry();
				ItemList[i].Deserialize(reader);
			}
		}

    }
}