// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Dragon treasure open box request
    /// </summary>
    public class CSDragonBoxOpenReq : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_DRAGONBOX_OPEN_BOX_REQ;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Treasure ID
		/// </summary>
		public int Id { get; set; }
		/// <summary>
		/// Open box key
		/// </summary>
		public int Key { get; set; }
		/// <summary>
		/// Open box count
		/// </summary>
		public int Num { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(Id);
			writer.WriteInt(Key);
			writer.WriteInt(Num);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Id = reader.ReadInt();
			Key = reader.ReadInt();
			Num = reader.ReadInt();
		}

    }
}