// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Refresh number confirm
    /// </summary>
    public class CSDragonBoxNumOKRsp : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_DRAGONBOX_NUM_OK_RSP;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Box ID
		/// </summary>
		public int BoxID { get; set; }
		/// <summary>
		/// 0 success 1 failed
		/// </summary>
		public int Sucess { get; set; }
		/// <summary>
		/// Number
		/// </summary>
		public int Number { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(BoxID);
			writer.WriteInt(Sucess);
			writer.WriteInt(Number);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			BoxID = reader.ReadInt();
			Sucess = reader.ReadInt();
			Number = reader.ReadInt();
		}

    }
}