// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Effect sync
    /// </summary>
    public class CSEffectSYNC : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_EFFECT_SYNC;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Attached Entity net ID
		/// </summary>
		public uint AttachToNetObjId { get; set; }
		/// <summary>
		/// Effect scale
		/// </summary>
		public float Scale { get; set; }
		/// <summary>
		/// Effect path
		/// </summary>
		public string Effect { get; set; }
		/// <summary>
		/// Direction in local space
		/// </summary>
		public CSVec3 LocalDir { get; set; }
		/// <summary>
		/// Position offset from attachment point
		/// </summary>
		public CSVec3 Offset { get; set; }
		/// <summary>
		/// Attachment bone name (optional)
		/// </summary>
		public string BoneName { get; set; }
		/// <summary>
		/// Remove or add
		/// </summary>
		public byte BRemove { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteUInt(AttachToNetObjId);
			writer.WriteFloat(Scale);
			if (Effect.Length > (CsprotoConstants.CS_MAX_EFFECT_NAME_LEN - 1))
			{
				throw new InvalidOperationException($"String length of 'Effect' should be of length of {(CsprotoConstants.CS_MAX_EFFECT_NAME_LEN - 1)} but was {Effect.Length}.");
			}

			writer.WriteUTF(Effect);
			LocalDir?.Serialize(writer);
			Offset?.Serialize(writer);
			if (BoneName.Length > (CsprotoConstants.CS_MAX_PART_NAME - 1))
			{
				throw new InvalidOperationException($"String length of 'BoneName' should be of length of {(CsprotoConstants.CS_MAX_PART_NAME - 1)} but was {BoneName.Length}.");
			}

			writer.WriteUTF(BoneName);
			writer.WriteByte(BRemove);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			AttachToNetObjId = reader.ReadUInt();
			Scale = reader.ReadFloat();
			Effect = reader.ReadUTF();
			LocalDir = new CSVec3();
			LocalDir.Deserialize(reader);
			Offset = new CSVec3();
			Offset.Deserialize(reader);
			BoneName = reader.ReadUTF();
			BRemove = reader.ReadByte();
		}

    }
}