// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Equipment transmog request
    /// </summary>
    public class CSEquipFakeShowReq : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.C2S_CMD_ITEM_EQUIP_FAKESHOW_REQ;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Equipment ID
		/// </summary>
		public int[] EquipCol { get; set; } = Array.Empty<int>();
		/// <summary>
		/// Column
		/// </summary>
		public int[] EquipGrid { get; set; } = Array.Empty<int>();
		/// <summary>
		/// Whether to clear
		/// </summary>
		public ushort[] ReSetFlag { get; set; } = Array.Empty<ushort>();
		/// <summary>
		/// Target column
		/// </summary>
		public int[] TargetCol { get; set; } = Array.Empty<int>();
		/// <summary>
		/// Target grid
		/// </summary>
		public int[] TargetGrid { get; set; } = Array.Empty<int>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			// Write length for array: EquipCol
			var FakeCnt = (int)(EquipCol?.Length ?? 0);
			if (FakeCnt > CsprotoConstants.CS_EQUIP_FAKESHOW_MAX)
			{
				throw new InvalidOperationException($"Array length of 'EquipCol' exceeds maximum allowed length of {CsprotoConstants.CS_EQUIP_FAKESHOW_MAX} but was {FakeCnt}.");
			}

			writer.WriteInt(FakeCnt);
			for (var i = 0; i < FakeCnt; i++)
			{
				writer.WriteInt(EquipCol[i]);
			}
			for (var i = 0; i < FakeCnt; i++)
			{
				writer.WriteInt(EquipGrid[i]);
			}
			for (var i = 0; i < FakeCnt; i++)
			{
				writer.WriteUShort(ReSetFlag[i]);
			}
			for (var i = 0; i < FakeCnt; i++)
			{
				writer.WriteInt(TargetCol[i]);
			}
			for (var i = 0; i < FakeCnt; i++)
			{
				writer.WriteInt(TargetGrid[i]);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			// Read length for array: EquipCol
			var FakeCnt = reader.ReadInt();
			// Read array: EquipCol
			EquipCol = new int[Math.Min((int)FakeCnt, CsprotoConstants.CS_EQUIP_FAKESHOW_MAX)];
			for (var i = 0; i < EquipCol.Length; i++)
			{
				EquipCol[i] = reader.ReadInt();
			}
			// Read array: EquipGrid
			EquipGrid = new int[Math.Min((int)FakeCnt, CsprotoConstants.CS_EQUIP_FAKESHOW_MAX)];
			for (var i = 0; i < EquipGrid.Length; i++)
			{
				EquipGrid[i] = reader.ReadInt();
			}
			// Read array: ReSetFlag
			ReSetFlag = new ushort[Math.Min((int)FakeCnt, CsprotoConstants.CS_EQUIP_FAKESHOW_MAX)];
			for (var i = 0; i < ReSetFlag.Length; i++)
			{
				ReSetFlag[i] = reader.ReadUShort();
			}
			// Read array: TargetCol
			TargetCol = new int[Math.Min((int)FakeCnt, CsprotoConstants.CS_EQUIP_FAKESHOW_MAX)];
			for (var i = 0; i < TargetCol.Length; i++)
			{
				TargetCol[i] = reader.ReadInt();
			}
			// Read array: TargetGrid
			TargetGrid = new int[Math.Min((int)FakeCnt, CsprotoConstants.CS_EQUIP_FAKESHOW_MAX)];
			for (var i = 0; i < TargetGrid.Length; i++)
			{
				TargetGrid[i] = reader.ReadInt();
			}
		}

    }
}