// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Essence response
    /// </summary>
    public class CSEquipQuenchRsp : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.C2S_CND_ITEMREBUILD_EQUIPQUENCH_RSP;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Status code
		/// </summary>
		public int RetCode { get; set; }
		/// <summary>
		/// Equipment unique ID
		/// </summary>
		public long ItemUid { get; set; }
		/// <summary>
		/// Pre level
		/// </summary>
		public int QuenchLv { get; set; }
		/// <summary>
		/// Essence attribute type
		/// </summary>
		public int[] AttrType { get; set; } = Array.Empty<int>();
		/// <summary>
		/// Essence attribute value
		/// </summary>
		public byte[] AttrValue { get; set; } = Array.Empty<byte>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(RetCode);
			writer.WriteLong(ItemUid);
			writer.WriteInt(QuenchLv);
			// Write length for array: AttrType
			var AttrDataCnt = (int)(AttrType?.Length ?? 0);
			if (AttrDataCnt > CsprotoConstants.CS_MAX_QUENCH_ATTR)
			{
				throw new InvalidOperationException($"Array length of 'AttrType' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_QUENCH_ATTR} but was {AttrDataCnt}.");
			}

			writer.WriteInt(AttrDataCnt);
			for (var i = 0; i < AttrDataCnt; i++)
			{
				writer.WriteInt(AttrType[i]);
			}
			for (var i = 0; i < AttrDataCnt; i++)
			{
				writer.WriteByte(AttrValue[i]);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			RetCode = reader.ReadInt();
			ItemUid = reader.ReadLong();
			QuenchLv = reader.ReadInt();
			// Read length for array: AttrType
			var AttrDataCnt = reader.ReadInt();
			// Read array: AttrType
			AttrType = new int[Math.Min((int)AttrDataCnt, CsprotoConstants.CS_MAX_QUENCH_ATTR)];
			for (var i = 0; i < AttrType.Length; i++)
			{
				AttrType[i] = reader.ReadInt();
			}
			// Read array: AttrValue
			AttrValue = new byte[Math.Min((int)AttrDataCnt, CsprotoConstants.CS_MAX_QUENCH_ATTR)];
			for (var i = 0; i < AttrValue.Length; i++)
			{
				AttrValue[i] = reader.ReadByte();
			}
		}

    }
}