// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    public class CSFarmFacilitySetGatherLevelReq : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_FARM_FACILITY_SET_GATHER_LEVEL_REQ;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Facility type
		/// </summary>
		public int FacilityType { get; set; }
		/// <summary>
		/// Facility index
		/// </summary>
		public int FacilityIndex { get; set; }
		/// <summary>
		/// Set level
		/// </summary>
		public int LevelSet { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(FacilityType);
			writer.WriteInt(FacilityIndex);
			writer.WriteInt(LevelSet);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			FacilityType = reader.ReadInt();
			FacilityIndex = reader.ReadInt();
			LevelSet = reader.ReadInt();
		}

    }
}