// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    public class CSFarmDataUpdateNtf : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_FARM_UPDATE_NTF;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Farm info
		/// </summary>
		public byte[] Farm { get; set; } = Array.Empty<byte>();
		/// <summary>
		/// Server time
		/// </summary>
		public uint ServerTime { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			if ((Farm?.Length ?? 0) != CsprotoConstants.CS_ROLE_FARMER_LEN)
			{
				throw new InvalidOperationException($"Array length of 'Farm' should be of length of {CsprotoConstants.CS_ROLE_FARMER_LEN} but was {(Farm?.Length ?? 0)}.");
			}

			for (var i = 0; i < CsprotoConstants.CS_ROLE_FARMER_LEN; i++)
			{
				writer.WriteByte(Farm[i]);
			}
			writer.WriteUInt(ServerTime);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			// Read array: Farm
			Farm = new byte[CsprotoConstants.CS_ROLE_FARMER_LEN];
			for (var i = 0; i < Farm.Length; i++)
			{
				Farm[i] = reader.ReadByte();
			}
			ServerTime = reader.ReadUInt();
		}

    }
}