// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// FIFO sync info
    /// </summary>
    public class CSFIFOSyncInfo : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_BATTLE_ACTOR_FIFO_SYNC;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Sync time
		/// </summary>
		public long SyncTime { get; set; }
		/// <summary>
		/// Current position
		/// </summary>
		public CSVec3 Pos { get; set; }
		/// <summary>
		/// Current rotation
		/// </summary>
		public CSQuat Rot { get; set; }
		/// <summary>
		/// Rotation 1
		/// </summary>
		public CSQuat Rot1 { get; set; }
		/// <summary>
		/// Rotation 2
		/// </summary>
		public CSQuat Rot2 { get; set; }
		/// <summary>
		/// Queue type
		/// </summary>
		public byte Type { get; set; }
		/// <summary>
		/// Extra info
		/// </summary>
		public byte Extension { get; set; }
		/// <summary>
		/// Player stance or FSM state
		/// </summary>
		public uint State1 { get; set; }
		/// <summary>
		/// Player stance or FSM state
		/// </summary>
		public uint State2 { get; set; }
		/// <summary>
		/// Player stance or FSM state
		/// </summary>
		public uint State3 { get; set; }
		/// <summary>
		/// Player stance or FSM state
		/// </summary>
		public uint State4 { get; set; }
		/// <summary>
		/// Player AG state
		/// </summary>
		public uint AGState { get; set; }
		/// <summary>
		/// Player SkillID
		/// </summary>
		public uint SkillID { get; set; }
		/// <summary>
		/// Player SkillLevel
		/// </summary>
		public uint SkillLevel { get; set; }
		/// <summary>
		/// Parameter info
		/// </summary>
		public int Param { get; set; }
		/// <summary>
		/// Float parameter info
		/// </summary>
		public float Paramf { get; set; }
		/// <summary>
		/// Attack rotation
		/// </summary>
		public float AttackRotation { get; set; }
		/// <summary>
		/// Player attribute
		/// </summary>
		public ushort Sp { get; set; }
		/// <summary>
		/// Player attribute
		/// </summary>
		public ushort Sta { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteLong(SyncTime);
			Pos?.Serialize(writer);
			Rot?.Serialize(writer);
			Rot1?.Serialize(writer);
			Rot2?.Serialize(writer);
			writer.WriteByte(Type);
			writer.WriteByte(Extension);
			writer.WriteUInt(State1);
			writer.WriteUInt(State2);
			writer.WriteUInt(State3);
			writer.WriteUInt(State4);
			writer.WriteUInt(AGState);
			writer.WriteUInt(SkillID);
			writer.WriteUInt(SkillLevel);
			writer.WriteInt(Param);
			writer.WriteFloat(Paramf);
			writer.WriteFloat(AttackRotation);
			writer.WriteUShort(Sp);
			writer.WriteUShort(Sta);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			SyncTime = reader.ReadLong();
			Pos = new CSVec3();
			Pos.Deserialize(reader);
			Rot = new CSQuat();
			Rot.Deserialize(reader);
			Rot1 = new CSQuat();
			Rot1.Deserialize(reader);
			Rot2 = new CSQuat();
			Rot2.Deserialize(reader);
			Type = reader.ReadByte();
			Extension = reader.ReadByte();
			State1 = reader.ReadUInt();
			State2 = reader.ReadUInt();
			State3 = reader.ReadUInt();
			State4 = reader.ReadUInt();
			AGState = reader.ReadUInt();
			SkillID = reader.ReadUInt();
			SkillLevel = reader.ReadUInt();
			Param = reader.ReadInt();
			Paramf = reader.ReadFloat();
			AttackRotation = reader.ReadFloat();
			Sp = reader.ReadUShort();
			Sta = reader.ReadUShort();
		}

    }
}