// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Been added as friend notification
    /// </summary>
    public class CSFriendBeAddNtf : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_FRIEND_BE_ADD_NTF;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Target role NetID
		/// </summary>
		public int NetID { get; set; }
		/// <summary>
		/// Target role name
		/// </summary>
		public string RoleName { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(NetID);
			if (RoleName.Length != CsprotoConstants.CS_MAX_ROLE_NAME)
			{
				throw new InvalidOperationException($"Array length of 'RoleName' should be of length of {CsprotoConstants.CS_MAX_ROLE_NAME} but was {RoleName.Length}.");
			}

			writer.WriteUTF(RoleName);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			NetID = reader.ReadInt();
			RoleName = reader.ReadUTF();
		}

    }
}