// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Set mood request
    /// </summary>
    public class CSFriendSetMoodReq : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_FRIEND_SET_MOOD_REQ;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Mood
		/// </summary>
		public string Mood { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			if (Mood.Length != CsprotoConstants.CS_MOOD_LEN)
			{
				throw new InvalidOperationException($"Array length of 'Mood' should be of length of {CsprotoConstants.CS_MOOD_LEN} but was {Mood.Length}.");
			}

			writer.WriteUTF(Mood);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Mood = reader.ReadUTF();
		}

    }
}