// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Add friend response
    /// </summary>
    public class CSFriendAddRsp : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_FRIEND_ADD_RSP;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		public byte Ret { get; set; }
		/// <summary>
		/// Friend data list
		/// </summary>
		public CSFriendInfo Friender { get; set; }
		/// <summary>
		/// Friend role DBID
		/// </summary>
		public ulong RoleDBID { get; set; }
		/// <summary>
		/// Friend role NetID
		/// </summary>
		public int NetID { get; set; }
		/// <summary>
		/// Friend role level
		/// </summary>
		public int Level { get; set; }
		/// <summary>
		/// Target role name
		/// </summary>
		public string RoleName { get; set; }
		/// <summary>
		/// Online status (0 or 1)
		/// </summary>
		public byte Online { get; set; }
		/// <summary>
		/// Farm points
		/// </summary>
		public int FarmPoint { get; set; }
		/// <summary>
		/// Remaining times player's farm can be gathered
		/// </summary>
		public int FarmCanBGatheredCount { get; set; }
		/// <summary>
		/// Friend's line
		/// </summary>
		public int LineId { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteByte(Ret);
			Friender?.Serialize(writer);
			writer.WriteULong(RoleDBID);
			writer.WriteInt(NetID);
			writer.WriteInt(Level);
			if (RoleName.Length != CsprotoConstants.CS_MAX_ROLE_NAME)
			{
				throw new InvalidOperationException($"Array length of 'RoleName' should be of length of {CsprotoConstants.CS_MAX_ROLE_NAME} but was {RoleName.Length}.");
			}

			writer.WriteUTF(RoleName);
			writer.WriteByte(Online);
			writer.WriteInt(FarmPoint);
			writer.WriteInt(FarmCanBGatheredCount);
			writer.WriteInt(LineId);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Ret = reader.ReadByte();
			Friender = new CSFriendInfo();
			Friender.Deserialize(reader);
			RoleDBID = reader.ReadULong();
			NetID = reader.ReadInt();
			Level = reader.ReadInt();
			RoleName = reader.ReadUTF();
			Online = reader.ReadByte();
			FarmPoint = reader.ReadInt();
			FarmCanBGatheredCount = reader.ReadInt();
			LineId = reader.ReadInt();
		}

    }
}