// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Group rename response
    /// </summary>
    public class CSFriendRenameGroupRsp : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_FRIEND_RENAME_GROUP_RSP;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Group ID
		/// </summary>
		public byte GroupID { get; set; }
		/// <summary>
		/// Group name
		/// </summary>
		public string GroupName { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteByte(GroupID);
			if (GroupName.Length != CsprotoConstants.CS_MAX_ROLE_NAME)
			{
				throw new InvalidOperationException($"Array length of 'GroupName' should be of length of {CsprotoConstants.CS_MAX_ROLE_NAME} but was {GroupName.Length}.");
			}

			writer.WriteUTF(GroupName);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			GroupID = reader.ReadByte();
			GroupName = reader.ReadUTF();
		}

    }
}