// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Friendliness change notification
    /// </summary>
    public class CSFriendFriendlyUpdateNtf : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_FRIEND_FRIENDLY_UPDATE_NTF;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Player DBID
		/// </summary>
		public ulong DBID { get; set; }
		/// <summary>
		/// New friendliness
		/// </summary>
		public uint Friendly { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteULong(DBID);
			writer.WriteUInt(Friendly);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			DBID = reader.ReadULong();
			Friendly = reader.ReadUInt();
		}

    }
}