// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Sensitive operation manage page URL response
    /// </summary>
    public class CSGetManageUrlRsp : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_GET_MANAGE_URL_RSP;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Manage page type
		/// </summary>
		public uint Type { get; set; }
		/// <summary>
		/// Result
		/// </summary>
		public uint Result { get; set; }
		/// <summary>
		/// Manage page URL
		/// </summary>
		public string Url { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteUInt(Type);
			writer.WriteUInt(Result);
			if (Url.Length > (CsprotoConstants.CS_MAX_SENSITIVE_VERIFY_URL_LEN - 1))
			{
				throw new InvalidOperationException($"String length of 'Url' should be of length of {(CsprotoConstants.CS_MAX_SENSITIVE_VERIFY_URL_LEN - 1)} but was {Url.Length}.");
			}

			writer.WriteUTF(Url);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Type = reader.ReadUInt();
			Result = reader.ReadUInt();
			Url = reader.ReadUTF();
		}

    }
}