// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Gift pack group state change notification
    /// </summary>
    public class CSGiftBagGroupStateNtf : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_GIFTBAGGROUP_STATE_NTF;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Gift pack group list
		/// </summary>
		public CSGiftGroupInfo[] GroupInfo { get; set; } = Array.Empty<CSGiftGroupInfo>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			// Write length for array: GroupInfo
			var Count = (byte)(GroupInfo?.Length ?? 0);
			if (Count > CsprotoConstants.CS_MAX_GIFTBAGGROUP_SUM)
			{
				throw new InvalidOperationException($"Array length of 'GroupInfo' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_GIFTBAGGROUP_SUM} but was {Count}.");
			}

			writer.WriteByte(Count);
			for (var i = 0; i < Count; i++)
			{
				GroupInfo[i]?.Serialize(writer);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			// Read length for array: GroupInfo
			var Count = reader.ReadByte();
			// Read array: GroupInfo
			GroupInfo = new CSGiftGroupInfo[Math.Min((int)Count, CsprotoConstants.CS_MAX_GIFTBAGGROUP_SUM)];
			for (var i = 0; i < GroupInfo.Length; i++)
			{
				GroupInfo[i] = new CSGiftGroupInfo();
				GroupInfo[i].Deserialize(reader);
			}
		}

    }
}