// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Attacking player info
    /// </summary>
    public class CSGrabInfo
    {
		/// <summary>
		/// Attacking players
		/// </summary>
		public ulong[] PlayerId { get; set; } = Array.Empty<ulong>();
		/// <summary>
		/// Occupying guild ID
		/// </summary>
		public ulong OwnGuildId { get; set; }
		/// <summary>
		/// Shortest time
		/// </summary>
		public uint MinTime { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			// Write length for array: PlayerId
			var PlayerCount = (uint)(PlayerId?.Length ?? 0);
			if (PlayerCount > CsprotoConstants.CS_MAX_GUILD_WAR_GRAB_COUNT)
			{
				throw new InvalidOperationException($"Array length of 'PlayerId' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_GUILD_WAR_GRAB_COUNT} but was {PlayerCount}.");
			}

			writer.WriteUInt(PlayerCount);
			for (var i = 0; i < PlayerCount; i++)
			{
				writer.WriteULong(PlayerId[i]);
			}
			writer.WriteULong(OwnGuildId);
			writer.WriteUInt(MinTime);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			// Read length for array: PlayerId
			var PlayerCount = reader.ReadUInt();
			// Read array: PlayerId
			PlayerId = new ulong[Math.Min((int)PlayerCount, CsprotoConstants.CS_MAX_GUILD_WAR_GRAB_COUNT)];
			for (var i = 0; i < PlayerId.Length; i++)
			{
				PlayerId[i] = reader.ReadULong();
			}
			OwnGuildId = reader.ReadULong();
			MinTime = reader.ReadUInt();
		}

    }
}