// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Guild application
    /// </summary>
    public class CSGuildApply
    {
		/// <summary>
		/// ID
		/// </summary>
		public int Id { get; set; }
		/// <summary>
		/// Name
		/// </summary>
		public string Name { get; set; }
		/// <summary>
		/// Level
		/// </summary>
		public int Level { get; set; }
		/// <summary>
		/// HRLevel
		/// </summary>
		public int HRLevel { get; set; }
		/// <summary>
		/// Hunter star level
		/// </summary>
		public string HunterStar { get; set; }
		/// <summary>
		/// Note
		/// </summary>
		public string Note { get; set; }
		/// <summary>
		/// Time
		/// </summary>
		public int Time { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(Id);
			if (Name.Length > (CsprotoConstants.CS_MAX_ROLE_NAME - 1))
			{
				throw new InvalidOperationException($"String length of 'Name' should be of length of {(CsprotoConstants.CS_MAX_ROLE_NAME - 1)} but was {Name.Length}.");
			}

			writer.WriteUTF(Name);
			writer.WriteInt(Level);
			writer.WriteInt(HRLevel);
			if (HunterStar.Length > (CsprotoConstants.CS_MAX_GUILD_HUNTERSTAR_LEN - 1))
			{
				throw new InvalidOperationException($"String length of 'HunterStar' should be of length of {(CsprotoConstants.CS_MAX_GUILD_HUNTERSTAR_LEN - 1)} but was {HunterStar.Length}.");
			}

			writer.WriteUTF(HunterStar);
			if (Note.Length > (CsprotoConstants.CS_MAX_GUILD_NOTE_LEN - 1))
			{
				throw new InvalidOperationException($"String length of 'Note' should be of length of {(CsprotoConstants.CS_MAX_GUILD_NOTE_LEN - 1)} but was {Note.Length}.");
			}

			writer.WriteUTF(Note);
			writer.WriteInt(Time);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Id = reader.ReadInt();
			Name = reader.ReadUTF();
			Level = reader.ReadInt();
			HRLevel = reader.ReadInt();
			HunterStar = reader.ReadUTF();
			Note = reader.ReadUTF();
			Time = reader.ReadInt();
		}

    }
}