// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    public class CSGuildBanGuilderReq : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_GUILDBANGUILDER_REQ;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Mute operation, 0 for mute 1 for unmute
		/// </summary>
		public int BanOperate { get; set; }
		/// <summary>
		/// Player DBID
		/// </summary>
		public ulong DBID { get; set; }
		/// <summary>
		/// Player NetID
		/// </summary>
		public int RoleID { get; set; }
		/// <summary>
		/// Player current dungeon/town map ID
		/// </summary>
		public uint LevelID { get; set; }
		/// <summary>
		/// Player current line
		/// </summary>
		public int LineId { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(BanOperate);
			writer.WriteULong(DBID);
			writer.WriteInt(RoleID);
			writer.WriteUInt(LevelID);
			writer.WriteInt(LineId);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			BanOperate = reader.ReadInt();
			DBID = reader.ReadULong();
			RoleID = reader.ReadInt();
			LevelID = reader.ReadUInt();
			LineId = reader.ReadInt();
		}

    }
}