// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Guild Quest
    /// </summary>
    public class CSGuildQuest
    {
		/// <summary>
		/// Prize set
		/// </summary>
		public int[] Prizes { get; set; } = Array.Empty<int>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			// Write length for array: Prizes
			var PrizeCount = (int)(Prizes?.Length ?? 0);
			if (PrizeCount > CsprotoConstants.CS_MAX_GUILD_QUEST_PRIZES_LEN)
			{
				throw new InvalidOperationException($"Array length of 'Prizes' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_GUILD_QUEST_PRIZES_LEN} but was {PrizeCount}.");
			}

			writer.WriteInt(PrizeCount);
			for (var i = 0; i < PrizeCount; i++)
			{
				writer.WriteInt(Prizes[i]);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			// Read length for array: Prizes
			var PrizeCount = reader.ReadInt();
			// Read array: Prizes
			Prizes = new int[Math.Min((int)PrizeCount, CsprotoConstants.CS_MAX_GUILD_QUEST_PRIZES_LEN)];
			for (var i = 0; i < Prizes.Length; i++)
			{
				Prizes[i] = reader.ReadInt();
			}
		}

    }
}