// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    public class CSGuildCommerceBoatStatusNtf : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_GUILD_COMERCE_BOAT_STATUS_NTF;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Commerce boat info list
		/// </summary>
		public GuildWarBoatStatus[] GuildWarBoatStatusList { get; set; } = Array.Empty<GuildWarBoatStatus>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			// Write length for array: GuildWarBoatStatusList
			var Count = (ushort)(GuildWarBoatStatusList?.Length ?? 0);
			if (Count > CsprotoConstants.CS_MAX_BOAT_INFO_COUNT)
			{
				throw new InvalidOperationException($"Array length of 'GuildWarBoatStatusList' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_BOAT_INFO_COUNT} but was {Count}.");
			}

			writer.WriteUShort(Count);
			for (var i = 0; i < Count; i++)
			{
				GuildWarBoatStatusList[i]?.Serialize(writer);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			// Read length for array: GuildWarBoatStatusList
			var Count = reader.ReadUShort();
			// Read array: GuildWarBoatStatusList
			GuildWarBoatStatusList = new GuildWarBoatStatus[Math.Min((int)Count, CsprotoConstants.CS_MAX_BOAT_INFO_COUNT)];
			for (var i = 0; i < GuildWarBoatStatusList.Length; i++)
			{
				GuildWarBoatStatusList[i] = new GuildWarBoatStatus();
				GuildWarBoatStatusList[i].Deserialize(reader);
			}
		}

    }
}