// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Guild summary set
    /// </summary>
    public class CSGuildOutlines
    {
		/// <summary>
		/// Guild set
		/// </summary>
		public CSGuildOutline[] Guilds { get; set; } = Array.Empty<CSGuildOutline>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			// Write length for array: Guilds
			var Count = (int)(Guilds?.Length ?? 0);
			if (Count > CsprotoConstants.CS_MAX_GUILD_PAGE_LEN)
			{
				throw new InvalidOperationException($"Array length of 'Guilds' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_GUILD_PAGE_LEN} but was {Count}.");
			}

			writer.WriteInt(Count);
			for (var i = 0; i < Count; i++)
			{
				Guilds[i]?.Serialize(writer);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			// Read length for array: Guilds
			var Count = reader.ReadInt();
			// Read array: Guilds
			Guilds = new CSGuildOutline[Math.Min((int)Count, CsprotoConstants.CS_MAX_GUILD_PAGE_LEN)];
			for (var i = 0; i < Guilds.Length; i++)
			{
				Guilds[i] = new CSGuildOutline();
				Guilds[i].Deserialize(reader);
			}
		}

    }
}