// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Guild title set
    /// </summary>
    public class CSGuildTitles
    {
		/// <summary>
		/// Title set
		/// </summary>
		public CSGuildTitle[] Titles { get; set; } = Array.Empty<CSGuildTitle>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			// Write length for array: Titles
			var Count = (int)(Titles?.Length ?? 0);
			if (Count > CsprotoConstants.CS_MAX_GUILD_TITLE_LEN)
			{
				throw new InvalidOperationException($"Array length of 'Titles' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_GUILD_TITLE_LEN} but was {Count}.");
			}

			writer.WriteInt(Count);
			for (var i = 0; i < Count; i++)
			{
				Titles[i]?.Serialize(writer);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			// Read length for array: Titles
			var Count = reader.ReadInt();
			// Read array: Titles
			Titles = new CSGuildTitle[Math.Min((int)Count, CsprotoConstants.CS_MAX_GUILD_TITLE_LEN)];
			for (var i = 0; i < Titles.Length; i++)
			{
				Titles[i] = new CSGuildTitle();
				Titles[i].Deserialize(reader);
			}
		}

    }
}