// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Guide book claim chapter reward request
    /// </summary>
    public class CSGuideBookGetChapterRewardReq : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.C2S_CMD_GUIDE_BOOK_GET_CHAPTER_REWARD_REQ;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Chapter Id
		/// </summary>
		public int ChapterId { get; set; }
		/// <summary>
		/// Reward index
		/// </summary>
		public int Index { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(ChapterId);
			writer.WriteInt(Index);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			ChapterId = reader.ReadInt();
			Index = reader.ReadInt();
		}

    }
}