// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Newbie guide notification
    /// </summary>
    public class CSGuideNotify : CSPlayerExtNotifyData
    {
		public const CS_PLAYER_EXT_TYPE ProtocolIdConst = CS_PLAYER_EXT_TYPE.CS_PLAYER_EXT_GUIDE;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Interact notification type
		/// </summary>
		public GUIDE_NOTIFY_TYPE NotifyType { get; set; }
		/// <summary>
		/// Notification data
		/// </summary>
		public CSGuideNotifyData Notify { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt((int)NotifyType);
			// Selected by: NotifyType
			Notify?.Serialize(writer);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			NotifyType = (GUIDE_NOTIFY_TYPE)reader.ReadInt();
			// Selected by: NotifyType
			Notify = ProtocolTypeManager.Get<CSGuideNotifyData>(NotifyType);
			Notify.Deserialize(reader);
		}

    }
}