// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Guild application set
    /// </summary>
    public class CSGuildApplys
    {
		/// <summary>
		/// Application set
		/// </summary>
		public CSGuildApply[] Applys { get; set; } = Array.Empty<CSGuildApply>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			// Write length for array: Applys
			var Count = (int)(Applys?.Length ?? 0);
			if (Count > CsprotoConstants.CS_MAX_GUILD_APPLY_LEN)
			{
				throw new InvalidOperationException($"Array length of 'Applys' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_GUILD_APPLY_LEN} but was {Count}.");
			}

			writer.WriteInt(Count);
			for (var i = 0; i < Count; i++)
			{
				Applys[i]?.Serialize(writer);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			// Read length for array: Applys
			var Count = reader.ReadInt();
			// Read array: Applys
			Applys = new CSGuildApply[Math.Min((int)Count, CsprotoConstants.CS_MAX_GUILD_APPLY_LEN)];
			for (var i = 0; i < Applys.Length; i++)
			{
				Applys[i] = new CSGuildApply();
				Applys[i].Deserialize(reader);
			}
		}

    }
}