// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Guild invitation
    /// </summary>
    public class CSGuildInvitation
    {
		/// <summary>
		/// ID
		/// </summary>
		public int Id { get; set; }
		/// <summary>
		/// Guild
		/// </summary>
		public ulong Guild { get; set; }
		/// <summary>
		/// Guild
		/// </summary>
		public string Name { get; set; }
		/// <summary>
		/// Sender
		/// </summary>
		public string Sender { get; set; }
		/// <summary>
		/// Time
		/// </summary>
		public int Time { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(Id);
			writer.WriteULong(Guild);
			if (Name.Length != CsprotoConstants.CS_MAX_GUILD_NAME_LEN)
			{
				throw new InvalidOperationException($"Array length of 'Name' should be of length of {CsprotoConstants.CS_MAX_GUILD_NAME_LEN} but was {Name.Length}.");
			}

			writer.WriteUTF(Name);
			if (Sender.Length != CsprotoConstants.CS_MAX_ROLE_NAME)
			{
				throw new InvalidOperationException($"Array length of 'Sender' should be of length of {CsprotoConstants.CS_MAX_ROLE_NAME} but was {Sender.Length}.");
			}

			writer.WriteUTF(Sender);
			writer.WriteInt(Time);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Id = reader.ReadInt();
			Guild = reader.ReadULong();
			Name = reader.ReadUTF();
			Sender = reader.ReadUTF();
			Time = reader.ReadInt();
		}

    }
}