// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    public class CSGuildWarGrabBoatRsp : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_GUILD_GRAB_BOAT_RSP;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Error code
		/// </summary>
		public uint ErrCode { get; set; }
		/// <summary>
		/// Player DBID with insufficient times
		/// </summary>
		public ulong[] PlayerIds { get; set; } = Array.Empty<ulong>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteUInt(ErrCode);
			// Write length for array: PlayerIds
			var Count = (ushort)(PlayerIds?.Length ?? 0);
			if (Count > CsprotoConstants.CS_MAX_ENTER_LEVEL_PLAYER_LEN)
			{
				throw new InvalidOperationException($"Array length of 'PlayerIds' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_ENTER_LEVEL_PLAYER_LEN} but was {Count}.");
			}

			writer.WriteUShort(Count);
			for (var i = 0; i < Count; i++)
			{
				writer.WriteULong(PlayerIds[i]);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			ErrCode = reader.ReadUInt();
			// Read length for array: PlayerIds
			var Count = reader.ReadUShort();
			// Read array: PlayerIds
			PlayerIds = new ulong[Math.Min((int)Count, CsprotoConstants.CS_MAX_ENTER_LEVEL_PLAYER_LEN)];
			for (var i = 0; i < PlayerIds.Length; i++)
			{
				PlayerIds[i] = reader.ReadULong();
			}
		}

    }
}