// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Star branch
    /// </summary>
    public class CSHunterStarBranch
    {
		/// <summary>
		/// Branch type
		/// </summary>
		public byte BranchType { get; set; }
		/// <summary>
		/// Branch score
		/// </summary>
		public uint BranchScore { get; set; }
		/// <summary>
		/// Branch level
		/// </summary>
		public ushort BranchLevel { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteByte(BranchType);
			writer.WriteUInt(BranchScore);
			writer.WriteUShort(BranchLevel);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			BranchType = reader.ReadByte();
			BranchScore = reader.ReadUInt();
			BranchLevel = reader.ReadUShort();
		}

    }
}