// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Instance unlock
    /// </summary>
    public class CSInstanceUnlockNotify : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_INSTANCE_UNLOCK_NTF;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Instance ID
		/// </summary>
		public int Level_id { get; set; }
		/// <summary>
		/// Hub tab
		/// </summary>
		public int HubEntryId { get; set; }
		/// <summary>
		/// Tab index
		/// </summary>
		public int PageIndex { get; set; }
		/// <summary>
		/// Star level
		/// </summary>
		public int StarLevel { get; set; }
		/// <summary>
		/// Unlock type
		/// </summary>
		public int Type { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(Level_id);
			writer.WriteInt(HubEntryId);
			writer.WriteInt(PageIndex);
			writer.WriteInt(StarLevel);
			writer.WriteInt(Type);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Level_id = reader.ReadInt();
			HubEntryId = reader.ReadInt();
			PageIndex = reader.ReadInt();
			StarLevel = reader.ReadInt();
			Type = reader.ReadInt();
		}

    }
}