// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Item decompose request
    /// </summary>
    public class CSItemRebuildItemDecomposeReq : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_ITEMREBUILD_ITEM_DECOMPOSE_REQ;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Upgrade target item
		/// </summary>
		public CSItemArgs[] Items { get; set; } = Array.Empty<CSItemArgs>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			// Write length for array: Items
			var ItemCount = (int)(Items?.Length ?? 0);
			if (ItemCount > CsprotoConstants.CS_ITEM_DECOMPOSE_ITEM_MAX)
			{
				throw new InvalidOperationException($"Array length of 'Items' exceeds maximum allowed length of {CsprotoConstants.CS_ITEM_DECOMPOSE_ITEM_MAX} but was {ItemCount}.");
			}

			writer.WriteInt(ItemCount);
			for (var i = 0; i < ItemCount; i++)
			{
				Items[i]?.Serialize(writer);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			// Read length for array: Items
			var ItemCount = reader.ReadInt();
			// Read array: Items
			Items = new CSItemArgs[Math.Min((int)ItemCount, CsprotoConstants.CS_ITEM_DECOMPOSE_ITEM_MAX)];
			for (var i = 0; i < Items.Length; i++)
			{
				Items[i] = new CSItemArgs();
				Items[i].Deserialize(reader);
			}
		}

    }
}