// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Request destroy item
    /// </summary>
    public class CSItemMgrDestroyItemReq : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_ITEMMGR_DESTROY_ITEM_REQ;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Item instance
		/// </summary>
		public ulong ItemID { get; set; }
		/// <summary>
		/// Slot
		/// </summary>
		public byte ItemColumn { get; set; }
		/// <summary>
		/// Grid
		/// </summary>
		public ushort ItemGrid { get; set; }
		/// <summary>
		/// Count
		/// </summary>
		public ushort ItemCount { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteULong(ItemID);
			writer.WriteByte(ItemColumn);
			writer.WriteUShort(ItemGrid);
			writer.WriteUShort(ItemCount);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			ItemID = reader.ReadULong();
			ItemColumn = reader.ReadByte();
			ItemGrid = reader.ReadUShort();
			ItemCount = reader.ReadUShort();
		}

    }
}