// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Item decompose item entry
    /// </summary>
    public class CSItemDecomposeItemEntry
    {
		/// <summary>
		/// Item config ID
		/// </summary>
		public uint ItemId { get; set; }
		/// <summary>
		/// Item count
		/// </summary>
		public uint ItemNum { get; set; }
		/// <summary>
		/// Bind type
		/// </summary>
		public byte BindType { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteUInt(ItemId);
			writer.WriteUInt(ItemNum);
			writer.WriteByte(BindType);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			ItemId = reader.ReadUInt();
			ItemNum = reader.ReadUInt();
			BindType = reader.ReadByte();
		}

    }
}