// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Equipment enhance count data
    /// </summary>
    public class CSItemRebuildLimitData
    {
		/// <summary>
		/// Type
		/// </summary>
		public int LimitType { get; set; }
		/// <summary>
		/// Count
		/// </summary>
		public ushort LimitCnt { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(LimitType);
			writer.WriteUShort(LimitCnt);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			LimitType = reader.ReadInt();
			LimitCnt = reader.ReadUShort();
		}

    }
}