// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Recasting request
    /// </summary>
    public class CSItemRebuildFoundRes : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_ITEMREBUILD_FOUND_RES;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Equipment column
		/// </summary>
		public byte EquipColumn { get; set; }
		/// <summary>
		/// Equipment grid
		/// </summary>
		public ushort EquipGrid { get; set; }
		/// <summary>
		/// Equipment instance ID
		/// </summary>
		public ulong EquipId { get; set; }
		/// <summary>
		/// Lock attribute
		/// </summary>
		public byte LockAttr { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteByte(EquipColumn);
			writer.WriteUShort(EquipGrid);
			writer.WriteULong(EquipId);
			writer.WriteByte(LockAttr);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			EquipColumn = reader.ReadByte();
			EquipGrid = reader.ReadUShort();
			EquipId = reader.ReadULong();
			LockAttr = reader.ReadByte();
		}

    }
}