// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Level gift box open
    /// </summary>
    public class CSItemLevelBoxOpenBoxNtf : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_ITEMLEVELBOX_OPEN_BOX_NTF;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Corresponding level ID
		/// </summary>
		public int LevelID { get; set; }
		/// <summary>
		/// Item list
		/// </summary>
		public CSItemBoxItemEntry[] ItemList { get; set; } = Array.Empty<CSItemBoxItemEntry>();
		/// <summary>
		/// Is bag full 1:full 0:not full
		/// </summary>
		public byte BagFull { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(LevelID);
			// Write length for array: ItemList
			var ItemCount = (byte)(ItemList?.Length ?? 0);
			if (ItemCount > CsprotoConstants.CS_MAX_LEVELBOX_ITEM_COUNT)
			{
				throw new InvalidOperationException($"Array length of 'ItemList' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_LEVELBOX_ITEM_COUNT} but was {ItemCount}.");
			}

			writer.WriteByte(ItemCount);
			for (var i = 0; i < ItemCount; i++)
			{
				ItemList[i]?.Serialize(writer);
			}
			writer.WriteByte(BagFull);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			LevelID = reader.ReadInt();
			// Read length for array: ItemList
			var ItemCount = reader.ReadByte();
			// Read array: ItemList
			ItemList = new CSItemBoxItemEntry[Math.Min((int)ItemCount, CsprotoConstants.CS_MAX_LEVELBOX_ITEM_COUNT)];
			for (var i = 0; i < ItemList.Length; i++)
			{
				ItemList[i] = new CSItemBoxItemEntry();
				ItemList[i].Deserialize(reader);
			}
			BagFull = reader.ReadByte();
		}

    }
}