// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Format period limit info
    /// </summary>
    public class CSLevelFormatPeriodLimitInfo
    {
		/// <summary>
		/// Merged format
		/// </summary>
		public int MergeID { get; set; }
		/// <summary>
		/// Subgroup
		/// </summary>
		public int SubGroupID { get; set; }
		/// <summary>
		/// Completion count
		/// </summary>
		public int FinishCount { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(MergeID);
			writer.WriteInt(SubGroupID);
			writer.WriteInt(FinishCount);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			MergeID = reader.ReadInt();
			SubGroupID = reader.ReadInt();
			FinishCount = reader.ReadInt();
		}

    }
}