// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Tournament period info clear
    /// </summary>
    public class CSLevelTournamentPeriodLimitClearNotify : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_LEVEL_TOURNAMENTS_LIMIT_CLEAR_NTF;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Season
		/// </summary>
		public int Season { get; set; }
		/// <summary>
		/// Round
		/// </summary>
		public int Round { get; set; }
		/// <summary>
		/// Sub group ID
		/// </summary>
		public int SubGroupID { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(Season);
			writer.WriteInt(Round);
			writer.WriteInt(SubGroupID);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Season = reader.ReadInt();
			Round = reader.ReadInt();
			SubGroupID = reader.ReadInt();
		}

    }
}