// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Instance cleared
    /// </summary>
    public class CSLevelIntegrateNtf : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_LEVEL_INTEGRATE_NTF;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Instance ID
		/// </summary>
		public int Level_id { get; set; }
		/// <summary>
		/// State
		/// </summary>
		public byte State { get; set; }
		/// <summary>
		/// Best historical score
		/// </summary>
		public int Best_final_rank { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(Level_id);
			writer.WriteByte(State);
			writer.WriteInt(Best_final_rank);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Level_id = reader.ReadInt();
			State = reader.ReadByte();
			Best_final_rank = reader.ReadInt();
		}

    }
}