// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Reward bonus info
    /// </summary>
    public class CSLevelRewardAffectInfo
    {
		/// <summary>
		/// Bonus type
		/// </summary>
		public short AffectType { get; set; }
		/// <summary>
		/// Reward value bonus type
		/// </summary>
		public short[] ValueAffectType { get; set; } = Array.Empty<short>();
		/// <summary>
		/// Reward value bonus
		/// </summary>
		public int[] ValueAffectValue { get; set; } = Array.Empty<int>();
		/// <summary>
		/// Percent bonus type
		/// </summary>
		public short[] PercentAffectType { get; set; } = Array.Empty<short>();
		/// <summary>
		/// Percent bonus value
		/// </summary>
		public int[] PercentAffectValue { get; set; } = Array.Empty<int>();
		/// <summary>
		/// Final percent reward
		/// </summary>
		public int FinalPercent { get; set; }
		/// <summary>
		/// Parameter 1
		/// </summary>
		public int Arg1 { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteShort(AffectType);
			// Write length for array: ValueAffectType
			var ValueAffectTypeCnt = (short)(ValueAffectType?.Length ?? 0);
			if (ValueAffectTypeCnt > CsprotoConstants.MAX_REWARD_PROP_TYPE)
			{
				throw new InvalidOperationException($"Array length of 'ValueAffectType' exceeds maximum allowed length of {CsprotoConstants.MAX_REWARD_PROP_TYPE} but was {ValueAffectTypeCnt}.");
			}

			writer.WriteShort(ValueAffectTypeCnt);
			for (var i = 0; i < ValueAffectTypeCnt; i++)
			{
				writer.WriteShort(ValueAffectType[i]);
			}
			for (var i = 0; i < ValueAffectTypeCnt; i++)
			{
				writer.WriteInt(ValueAffectValue[i]);
			}
			// Write length for array: PercentAffectType
			var PercentAffectTypeCnt = (short)(PercentAffectType?.Length ?? 0);
			if (PercentAffectTypeCnt > CsprotoConstants.MAX_REWARD_PROP_TYPE)
			{
				throw new InvalidOperationException($"Array length of 'PercentAffectType' exceeds maximum allowed length of {CsprotoConstants.MAX_REWARD_PROP_TYPE} but was {PercentAffectTypeCnt}.");
			}

			writer.WriteShort(PercentAffectTypeCnt);
			for (var i = 0; i < PercentAffectTypeCnt; i++)
			{
				writer.WriteShort(PercentAffectType[i]);
			}
			for (var i = 0; i < PercentAffectTypeCnt; i++)
			{
				writer.WriteInt(PercentAffectValue[i]);
			}
			writer.WriteInt(FinalPercent);
			writer.WriteInt(Arg1);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			AffectType = reader.ReadShort();
			// Read length for array: ValueAffectType
			var ValueAffectTypeCnt = reader.ReadShort();
			// Read array: ValueAffectType
			ValueAffectType = new short[Math.Min((int)ValueAffectTypeCnt, CsprotoConstants.MAX_REWARD_PROP_TYPE)];
			for (var i = 0; i < ValueAffectType.Length; i++)
			{
				ValueAffectType[i] = reader.ReadShort();
			}
			// Read array: ValueAffectValue
			ValueAffectValue = new int[Math.Min((int)ValueAffectTypeCnt, CsprotoConstants.MAX_REWARD_PROP_TYPE)];
			for (var i = 0; i < ValueAffectValue.Length; i++)
			{
				ValueAffectValue[i] = reader.ReadInt();
			}
			// Read length for array: PercentAffectType
			var PercentAffectTypeCnt = reader.ReadShort();
			// Read array: PercentAffectType
			PercentAffectType = new short[Math.Min((int)PercentAffectTypeCnt, CsprotoConstants.MAX_REWARD_PROP_TYPE)];
			for (var i = 0; i < PercentAffectType.Length; i++)
			{
				PercentAffectType[i] = reader.ReadShort();
			}
			// Read array: PercentAffectValue
			PercentAffectValue = new int[Math.Min((int)PercentAffectTypeCnt, CsprotoConstants.MAX_REWARD_PROP_TYPE)];
			for (var i = 0; i < PercentAffectValue.Length; i++)
			{
				PercentAffectValue[i] = reader.ReadInt();
			}
			FinalPercent = reader.ReadInt();
			Arg1 = reader.ReadInt();
		}

    }
}