// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// LOOKAT sync
    /// </summary>
    public class CSLookAtSYNC : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_LOOK_AT;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// NetObjId of Monster to sync
		/// </summary>
		public uint EntityId { get; set; }
		/// <summary>
		/// Start or end
		/// </summary>
		public byte Start { get; set; }
		/// <summary>
		/// Target position
		/// </summary>
		public CSVec3 TargetPos { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteUInt(EntityId);
			writer.WriteByte(Start);
			TargetPos?.Serialize(writer);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			EntityId = reader.ReadUInt();
			Start = reader.ReadByte();
			TargetPos = new CSVec3();
			TargetPos.Deserialize(reader);
		}

    }
}