// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    public class CSMailNotify : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_MAIL_NOTIFY;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// 0:player mail;1:system mail 2:gift box;3:request box; 0xff:all types
		/// </summary>
		public byte MailType { get; set; }
		/// <summary>
		/// 0:player has new mail;1:system return deleted due to full mailbox 2:system return needs player to receive;3:mail deleted due to expiry
		/// </summary>
		public char MailNotifyType { get; set; }
		/// <summary>
		/// Total mail count
		/// </summary>
		public uint MailCount { get; set; }
		/// <summary>
		/// Mail details
		/// </summary>
		public CSMailListEntry MailListEntry { get; set; }
		public uint Uin { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteByte(MailType);
			writer.WriteChar(MailNotifyType);
			writer.WriteUInt(MailCount);
			MailListEntry?.Serialize(writer);
			writer.WriteUInt(Uin);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			MailType = reader.ReadByte();
			MailNotifyType = reader.ReadChar();
			MailCount = reader.ReadUInt();
			MailListEntry = new CSMailListEntry();
			MailListEntry.Deserialize(reader);
			Uin = reader.ReadUInt();
		}

    }
}