// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Instance main UI operation enter request
    /// </summary>
    public class CSMainInstanceEnterOptReq : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_MAIN_INSTANCE_ENTER_OPT_REQ;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// level id
		/// </summary>
		public int LevelID { get; set; }
		/// <summary>
		/// NPC parameter or Trigger parameter
		/// </summary>
		public int Param { get; set; }
		/// <summary>
		/// Mercenary
		/// </summary>
		public int UseEmploye { get; set; }
		/// <summary>
		/// Weapon trial layer
		/// </summary>
		public int WeaponTrial { get; set; }
		/// <summary>
		/// Grab target id
		/// </summary>
		public ulong GuildWarTargetId { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(LevelID);
			writer.WriteInt(Param);
			writer.WriteInt(UseEmploye);
			writer.WriteInt(WeaponTrial);
			writer.WriteULong(GuildWarTargetId);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			LevelID = reader.ReadInt();
			Param = reader.ReadInt();
			UseEmploye = reader.ReadInt();
			WeaponTrial = reader.ReadInt();
			GuildWarTargetId = reader.ReadULong();
		}

    }
}