// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    public class CSMailGroupDelRes : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_MAIL_GROUPDEL_RES;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		public int Result { get; set; }
		/// <summary>
		/// Delete result
		/// </summary>
		public CSMailGroupDelResult[] Results { get; set; } = Array.Empty<CSMailGroupDelResult>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(Result);
			// Write length for array: Results
			var Count = (int)(Results?.Length ?? 0);
			if (Count > CsprotoConstants.CS_MAIL_MAX_NUM)
			{
				throw new InvalidOperationException($"Array length of 'Results' exceeds maximum allowed length of {CsprotoConstants.CS_MAIL_MAX_NUM} but was {Count}.");
			}

			writer.WriteInt(Count);
			for (var i = 0; i < Count; i++)
			{
				Results[i]?.Serialize(writer);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Result = reader.ReadInt();
			// Read length for array: Results
			var Count = reader.ReadInt();
			// Read array: Results
			Results = new CSMailGroupDelResult[Math.Min((int)Count, CsprotoConstants.CS_MAIL_MAX_NUM)];
			for (var i = 0; i < Results.Length; i++)
			{
				Results[i] = new CSMailGroupDelResult();
				Results[i].Deserialize(reader);
			}
		}

    }
}