// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    public class CSMailLoginRes : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_MAIL_LOGIN_RES;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Mail type
		/// </summary>
		public byte MailType { get; set; }
		/// <summary>
		/// 0: no unread mail, 1: has unread mail
		/// </summary>
		public byte MailRemind { get; set; }
		/// <summary>
		/// -1: field has no meaning, non-negative: unread mail total
		/// </summary>
		public int MailRemindCount { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteByte(MailType);
			writer.WriteByte(MailRemind);
			writer.WriteInt(MailRemindCount);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			MailType = reader.ReadByte();
			MailRemind = reader.ReadByte();
			MailRemindCount = reader.ReadInt();
		}

    }
}