// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Hot sale goods response
    /// </summary>
    public class CSMartHotListRsp : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_MART_HOT_LIST_RSP;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Hot sale goods list
		/// </summary>
		public int[] Hotlist { get; set; } = Array.Empty<int>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			// Write length for array: Hotlist
			var Hotnum = (int)(Hotlist?.Length ?? 0);
			if (Hotnum > CsprotoConstants.CS_MAX_HOTSALE_NUM)
			{
				throw new InvalidOperationException($"Array length of 'Hotlist' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_HOTSALE_NUM} but was {Hotnum}.");
			}

			writer.WriteInt(Hotnum);
			for (var i = 0; i < Hotnum; i++)
			{
				writer.WriteInt(Hotlist[i]);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			// Read length for array: Hotlist
			var Hotnum = reader.ReadInt();
			// Read array: Hotlist
			Hotlist = new int[Math.Min((int)Hotnum, CsprotoConstants.CS_MAX_HOTSALE_NUM)];
			for (var i = 0; i < Hotlist.Length; i++)
			{
				Hotlist[i] = reader.ReadInt();
			}
		}

    }
}