// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// User or team leader self UI instance display sync response
    /// </summary>
    public class CSMainInstanceUIRsp : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_MAIN_INSTANCE_UI_RSP;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Error code
		/// </summary>
		public int ErrCode { get; set; }
		/// <summary>
		/// Entry hub ID
		/// </summary>
		public int HubEntryID { get; set; }
		/// <summary>
		/// UI display list
		/// </summary>
		public CSMainInstanceUIInfoList UIInfoList { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(ErrCode);
			writer.WriteInt(HubEntryID);
			UIInfoList?.Serialize(writer);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			ErrCode = reader.ReadInt();
			HubEntryID = reader.ReadInt();
			UIInfoList = new CSMainInstanceUIInfoList();
			UIInfoList.Deserialize(reader);
		}

    }
}