// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    public class CSMailGroupAccessoriesGetReq : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_MAIL_GROUP_ACCESSORIESGET_REQ;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Mail attachment storage location (bag, warehouse)
		/// </summary>
		public int AccStoreLocation { get; set; }
		/// <summary>
		/// Delete method
		/// </summary>
		public int DelType { get; set; }
		/// <summary>
		/// Batch delete mail ID
		/// </summary>
		public ulong[] MailId { get; set; } = Array.Empty<ulong>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(AccStoreLocation);
			writer.WriteInt(DelType);
			// Write length for array: MailId
			var Count = (int)(MailId?.Length ?? 0);
			if (Count > CsprotoConstants.CS_MAIL_MAX_NUM)
			{
				throw new InvalidOperationException($"Array length of 'MailId' exceeds maximum allowed length of {CsprotoConstants.CS_MAIL_MAX_NUM} but was {Count}.");
			}

			writer.WriteInt(Count);
			for (var i = 0; i < Count; i++)
			{
				writer.WriteULong(MailId[i]);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			AccStoreLocation = reader.ReadInt();
			DelType = reader.ReadInt();
			// Read length for array: MailId
			var Count = reader.ReadInt();
			// Read array: MailId
			MailId = new ulong[Math.Min((int)Count, CsprotoConstants.CS_MAIL_MAX_NUM)];
			for (var i = 0; i < MailId.Length; i++)
			{
				MailId[i] = reader.ReadULong();
			}
		}

    }
}