// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Shop exchange
    /// </summary>
    public class CSMaterialExchange : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_MATERIAL_EXCHANGE;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Exchange ID
		/// </summary>
		public uint MEID { get; set; }
		/// <summary>
		/// Exchange details
		/// </summary>
		public CSMaterialExchangeGrid[] MEGridInfo { get; set; } = Array.Empty<CSMaterialExchangeGrid>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteUInt(MEID);
			// Write length for array: MEGridInfo
			var MEGridCount = (uint)(MEGridInfo?.Length ?? 0);
			if (MEGridCount > CsprotoConstants.CS_MAX_MATERIAL_EXCHANGE_GRIDS)
			{
				throw new InvalidOperationException($"Array length of 'MEGridInfo' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_MATERIAL_EXCHANGE_GRIDS} but was {MEGridCount}.");
			}

			writer.WriteUInt(MEGridCount);
			for (var i = 0; i < MEGridCount; i++)
			{
				MEGridInfo[i]?.Serialize(writer);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			MEID = reader.ReadUInt();
			// Read length for array: MEGridInfo
			var MEGridCount = reader.ReadUInt();
			// Read array: MEGridInfo
			MEGridInfo = new CSMaterialExchangeGrid[Math.Min((int)MEGridCount, CsprotoConstants.CS_MAX_MATERIAL_EXCHANGE_GRIDS)];
			for (var i = 0; i < MEGridInfo.Length; i++)
			{
				MEGridInfo[i] = new CSMaterialExchangeGrid();
				MEGridInfo[i].Deserialize(reader);
			}
		}

    }
}