// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Instance main UI display info list
    /// </summary>
    public class CSMainInstanceUIInfoList
    {
		/// <summary>
		/// UI info
		/// </summary>
		public CSMainInstanceUIInfo[] UIInfos { get; set; } = Array.Empty<CSMainInstanceUIInfo>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			// Write length for array: UIInfos
			var InfoCount = (short)(UIInfos?.Length ?? 0);
			if (InfoCount > 100)
			{
				throw new InvalidOperationException($"Array length of 'UIInfos' exceeds maximum allowed length of {100} but was {InfoCount}.");
			}

			writer.WriteShort(InfoCount);
			for (var i = 0; i < InfoCount; i++)
			{
				UIInfos[i]?.Serialize(writer);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			// Read length for array: UIInfos
			var InfoCount = reader.ReadShort();
			// Read array: UIInfos
			UIInfos = new CSMainInstanceUIInfo[Math.Min((int)InfoCount, 100)];
			for (var i = 0; i < UIInfos.Length; i++)
			{
				UIInfos[i] = new CSMainInstanceUIInfo();
				UIInfos[i].Deserialize(reader);
			}
		}

    }
}