// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Monster size info list
    /// </summary>
    public class CSMonsterSizeNtf : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_MONSTER_SIZE_NTF;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// All monster size info
		/// </summary>
		public CSMonsterSizeInfo[] Infos { get; set; } = Array.Empty<CSMonsterSizeInfo>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			// Write length for array: Infos
			var InfoCount = (short)(Infos?.Length ?? 0);
			if (InfoCount > CsprotoConstants.MAX_MONSTER_SIZE_INFO_COUNT)
			{
				throw new InvalidOperationException($"Array length of 'Infos' exceeds maximum allowed length of {CsprotoConstants.MAX_MONSTER_SIZE_INFO_COUNT} but was {InfoCount}.");
			}

			writer.WriteShort(InfoCount);
			for (var i = 0; i < InfoCount; i++)
			{
				Infos[i]?.Serialize(writer);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			// Read length for array: Infos
			var InfoCount = reader.ReadShort();
			// Read array: Infos
			Infos = new CSMonsterSizeInfo[Math.Min((int)InfoCount, CsprotoConstants.MAX_MONSTER_SIZE_INFO_COUNT)];
			for (var i = 0; i < Infos.Length; i++)
			{
				Infos[i] = new CSMonsterSizeInfo();
				Infos[i].Deserialize(reader);
			}
		}

    }
}