// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Player dialog option
    /// </summary>
    public class CSMsgBoxSelectReq : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_MSGBOX_SELECT_REQ;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Instance ID
		/// </summary>
		public uint MsgBoxId { get; set; }
		/// <summary>
		/// Option, 0-agree, 1-disagree
		/// </summary>
		public byte Option { get; set; }
		/// <summary>
		/// Reject reason
		/// </summary>
		public int Reason { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteUInt(MsgBoxId);
			writer.WriteByte(Option);
			writer.WriteInt(Reason);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			MsgBoxId = reader.ReadUInt();
			Option = reader.ReadByte();
			Reason = reader.ReadInt();
		}

    }
}