// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Notice
    /// </summary>
    public class CSNoticeNtf : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_NOTICE_NTF;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Broadcast type
		/// </summary>
		public int NoticeType { get; set; }
		public string Content { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(NoticeType);
			if (Content.Length != CsprotoConstants.CS_MAX_NOTICE_CONTENT_LEN)
			{
				throw new InvalidOperationException($"Array length of 'Content' should be of length of {CsprotoConstants.CS_MAX_NOTICE_CONTENT_LEN} but was {Content.Length}.");
			}

			writer.WriteUTF(Content);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			NoticeType = reader.ReadInt();
			Content = reader.ReadUTF();
		}

    }
}