// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Request to sell item from bag
    /// </summary>
    public class CSNpcShopSellItemReq : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_NPCSHOP_SELLITEM_REQ;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Item Column position
		/// </summary>
		public int Column { get; set; }
		/// <summary>
		/// Item Grid position
		/// </summary>
		public int Grid { get; set; }
		/// <summary>
		/// Sell count
		/// </summary>
		public int Count { get; set; }
		/// <summary>
		/// Whether unified store
		/// </summary>
		public int IsUnifiedStore { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(Column);
			writer.WriteInt(Grid);
			writer.WriteInt(Count);
			writer.WriteInt(IsUnifiedStore);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Column = reader.ReadInt();
			Grid = reader.ReadInt();
			Count = reader.ReadInt();
			IsUnifiedStore = reader.ReadInt();
		}

    }
}