// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Response to sell item from bag
    /// </summary>
    public class CSNpcShopSellItemRsp : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_NPCSHOP_SELLITEM_RSP;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Return value, 0 for success
		/// </summary>
		public int Ret { get; set; }
		/// <summary>
		/// Sold item type
		/// </summary>
		public int ItemType { get; set; }
		/// <summary>
		/// Sold item count
		/// </summary>
		public int ItemCount { get; set; }
		/// <summary>
		/// Gold earned
		/// </summary>
		public int MoneyAdd { get; set; }
		/// <summary>
		/// Item data
		/// </summary>
		public CSGeneralItem ItemData { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(Ret);
			writer.WriteInt(ItemType);
			writer.WriteInt(ItemCount);
			writer.WriteInt(MoneyAdd);
			ItemData?.Serialize(writer);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Ret = reader.ReadInt();
			ItemType = reader.ReadInt();
			ItemCount = reader.ReadInt();
			MoneyAdd = reader.ReadInt();
			ItemData = new CSGeneralItem();
			ItemData.Deserialize(reader);
		}

    }
}