// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    public class CSObjectActionSyncEntry : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_BATTLE_OBJECT_ACTION;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		public uint EntityId { get; set; }
		/// <summary>
		/// Action type
		/// </summary>
		public CS_SCENE_OBJECT_ACTION_TYPE Action { get; set; }
		/// <summary>
		/// Parameter
		/// </summary>
		public CSObjectActionParam Param { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteUInt(EntityId);
			writer.WriteUShort((ushort)Action);
			// Selected by: Action
			Param?.Serialize(writer);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			EntityId = reader.ReadUInt();
			Action = (CS_SCENE_OBJECT_ACTION_TYPE)reader.ReadUShort();
			// Selected by: Action
			Param = ProtocolTypeManager.Get<CSObjectActionParam>(Action);
			Param.Deserialize(reader);
		}

    }
}