// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Contribution payment response
    /// </summary>
    public class CSPaidContributeBoxRsp : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_PAID_CONTRIBUTE_BOX_RSP;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Error code
		/// </summary>
		public int ErrCode { get; set; }
		/// <summary>
		/// Player ID
		/// </summary>
		public int NetID { get; set; }
		/// <summary>
		/// Contribution item group
		/// </summary>
		public CSPaidContributeBoxData[] PaidItems { get; set; } = Array.Empty<CSPaidContributeBoxData>();
		/// <summary>
		/// Contribution buff group
		/// </summary>
		public CSPaidContributeBoxData[] PaidBuffs { get; set; } = Array.Empty<CSPaidContributeBoxData>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(ErrCode);
			writer.WriteInt(NetID);
			// Write length for array: PaidItems
			var ItemDataCount = (int)(PaidItems?.Length ?? 0);
			if (ItemDataCount > CsprotoConstants.CS_MAX_PAID_BOX_DATA_COUNT)
			{
				throw new InvalidOperationException($"Array length of 'PaidItems' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_PAID_BOX_DATA_COUNT} but was {ItemDataCount}.");
			}

			writer.WriteInt(ItemDataCount);
			for (var i = 0; i < ItemDataCount; i++)
			{
				PaidItems[i]?.Serialize(writer);
			}
			// Write length for array: PaidBuffs
			var BuffDataCount = (int)(PaidBuffs?.Length ?? 0);
			if (BuffDataCount > CsprotoConstants.CS_MAX_PAID_BOX_DATA_COUNT)
			{
				throw new InvalidOperationException($"Array length of 'PaidBuffs' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_PAID_BOX_DATA_COUNT} but was {BuffDataCount}.");
			}

			writer.WriteInt(BuffDataCount);
			for (var i = 0; i < BuffDataCount; i++)
			{
				PaidBuffs[i]?.Serialize(writer);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			ErrCode = reader.ReadInt();
			NetID = reader.ReadInt();
			// Read length for array: PaidItems
			var ItemDataCount = reader.ReadInt();
			// Read array: PaidItems
			PaidItems = new CSPaidContributeBoxData[Math.Min((int)ItemDataCount, CsprotoConstants.CS_MAX_PAID_BOX_DATA_COUNT)];
			for (var i = 0; i < PaidItems.Length; i++)
			{
				PaidItems[i] = new CSPaidContributeBoxData();
				PaidItems[i].Deserialize(reader);
			}
			// Read length for array: PaidBuffs
			var BuffDataCount = reader.ReadInt();
			// Read array: PaidBuffs
			PaidBuffs = new CSPaidContributeBoxData[Math.Min((int)BuffDataCount, CsprotoConstants.CS_MAX_PAID_BOX_DATA_COUNT)];
			for (var i = 0; i < PaidBuffs.Length; i++)
			{
				PaidBuffs[i] = new CSPaidContributeBoxData();
				PaidBuffs[i].Deserialize(reader);
			}
		}

    }
}