// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Pet add sync
    /// </summary>
    public class CSPetAddSync : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_PET_ADD_SYNC;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Pet ID
		/// </summary>
		public int PetID { get; set; }
		/// <summary>
		/// pet index
		/// </summary>
		public int Idx { get; set; }
		/// <summary>
		/// pet UID
		/// </summary>
		public int UID { get; set; }
		/// <summary>
		/// pet sex
		/// </summary>
		public char Sex { get; set; }
		/// <summary>
		/// Innate skill
		/// </summary>
		public int GiftSkill { get; set; }
		/// <summary>
		/// Random attributes
		/// </summary>
		public CSPetRandAttrs RandAttrs { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(PetID);
			writer.WriteInt(Idx);
			writer.WriteInt(UID);
			writer.WriteChar(Sex);
			writer.WriteInt(GiftSkill);
			RandAttrs?.Serialize(writer);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			PetID = reader.ReadInt();
			Idx = reader.ReadInt();
			UID = reader.ReadInt();
			Sex = reader.ReadChar();
			GiftSkill = reader.ReadInt();
			RandAttrs = new CSPetRandAttrs();
			RandAttrs.Deserialize(reader);
		}

    }
}