// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Pet pending skill sync
    /// </summary>
    public class CSPetWaitSkillSync : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_PET_WAIT_SKILL_SYNC;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// pet index
		/// </summary>
		public int Idx { get; set; }
		/// <summary>
		/// pet UID
		/// </summary>
		public int UID { get; set; }
		/// <summary>
		/// Pending skill slots
		/// </summary>
		public int[] Skill { get; set; } = Array.Empty<int>();
		/// <summary>
		/// Pending skill slot new info
		/// </summary>
		public char[] NewFlag { get; set; } = Array.Empty<char>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(Idx);
			writer.WriteInt(UID);
			// Write length for array: Skill
			var Count = (short)(Skill?.Length ?? 0);
			if (Count > CsprotoConstants.CS_MAX_PET_WAIT_SKILL_NUM)
			{
				throw new InvalidOperationException($"Array length of 'Skill' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_PET_WAIT_SKILL_NUM} but was {Count}.");
			}

			writer.WriteShort(Count);
			for (var i = 0; i < Count; i++)
			{
				writer.WriteInt(Skill[i]);
			}
			for (var i = 0; i < Count; i++)
			{
				writer.WriteChar(NewFlag[i]);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Idx = reader.ReadInt();
			UID = reader.ReadInt();
			// Read length for array: Skill
			var Count = reader.ReadShort();
			// Read array: Skill
			Skill = new int[Math.Min((int)Count, CsprotoConstants.CS_MAX_PET_WAIT_SKILL_NUM)];
			for (var i = 0; i < Skill.Length; i++)
			{
				Skill[i] = reader.ReadInt();
			}
			// Read array: NewFlag
			NewFlag = new char[Math.Min((int)Count, CsprotoConstants.CS_MAX_PET_WAIT_SKILL_NUM)];
			for (var i = 0; i < NewFlag.Length; i++)
			{
				NewFlag[i] = reader.ReadChar();
			}
		}

    }
}