// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// pet appear notify list
    /// </summary>
    public class CSPetAppearNtfList : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_PET_APPEAR_NTF_LIST;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		public CSPetAppearNtf[] Appear { get; set; } = Array.Empty<CSPetAppearNtf>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			// Write length for array: Appear
			var Count = (int)(Appear?.Length ?? 0);
			if (Count > CsprotoConstants.CS_MAX_APPEAR_NTF_NUM)
			{
				throw new InvalidOperationException($"Array length of 'Appear' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_APPEAR_NTF_NUM} but was {Count}.");
			}

			writer.WriteInt(Count);
			for (var i = 0; i < Count; i++)
			{
				Appear[i]?.Serialize(writer);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			// Read length for array: Appear
			var Count = reader.ReadInt();
			// Read array: Appear
			Appear = new CSPetAppearNtf[Math.Min((int)Count, CsprotoConstants.CS_MAX_APPEAR_NTF_NUM)];
			for (var i = 0; i < Appear.Length; i++)
			{
				Appear[i] = new CSPetAppearNtf();
				Appear[i].Deserialize(reader);
			}
		}

    }
}