// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Ping message
    /// </summary>
    public class CSPing : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_SYSTEM_PING;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Ping message sequence number
		/// </summary>
		public uint PingID { get; set; }
		/// <summary>
		/// Delay statistics, milliseconds
		/// </summary>
		public ushort Delay { get; set; }
		/// <summary>
		/// Recent delay, milliseconds
		/// </summary>
		public ushort CurDelay { get; set; }
		/// <summary>
		/// Recent average delay, milliseconds
		/// </summary>
		public ushort AverageDelay { get; set; }
		/// <summary>
		/// Recent server FPS
		/// </summary>
		public char ServerFps { get; set; }
		/// <summary>
		/// Server timestamp
		/// </summary>
		public uint ServerTm { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteUInt(PingID);
			writer.WriteUShort(Delay);
			writer.WriteUShort(CurDelay);
			writer.WriteUShort(AverageDelay);
			writer.WriteChar(ServerFps);
			writer.WriteUInt(ServerTm);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			PingID = reader.ReadUInt();
			Delay = reader.ReadUShort();
			CurDelay = reader.ReadUShort();
			AverageDelay = reader.ReadUShort();
			ServerFps = reader.ReadChar();
			ServerTm = reader.ReadUInt();
		}

    }
}