// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Client send LOG
    /// </summary>
    public class CSPkgBodyClientSendLogNewplayer : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_CLIENT_SEND_LOG_NEWPLAYER;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Reason
		/// </summary>
		public int Reason { get; set; }
		/// <summary>
		/// Log info
		/// </summary>
		public string LogInfo { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(Reason);
			if (LogInfo.Length != CsprotoConstants.MAX_CHAT_CONTENT_LEN)
			{
				throw new InvalidOperationException($"Array length of 'LogInfo' should be of length of {CsprotoConstants.MAX_CHAT_CONTENT_LEN} but was {LogInfo.Length}.");
			}

			writer.WriteUTF(LogInfo);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Reason = reader.ReadInt();
			LogInfo = reader.ReadUTF();
		}

    }
}