// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// LL layer effect sync
    /// </summary>
    public class CSPlayFxNtf : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_PLAY_FX;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// LogicEntityID of attached object
		/// </summary>
		public uint Attached { get; set; }
		/// <summary>
		/// Effect ID to play
		/// </summary>
		public uint FxID { get; set; }
		/// <summary>
		/// Add or remove
		/// </summary>
		public int Remove { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteUInt(Attached);
			writer.WriteUInt(FxID);
			writer.WriteInt(Remove);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Attached = reader.ReadUInt();
			FxID = reader.ReadUInt();
			Remove = reader.ReadInt();
		}

    }
}