// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Player scene object interaction
    /// </summary>
    public class CSPlayerSceneObjSync : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_PLAYER_SCENEOBJ_INTE;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Scene object LogicID to sync
		/// </summary>
		public int SceneObjLogicID { get; set; }
		/// <summary>
		/// Requester LogicID
		/// </summary>
		public int ReqLogicID { get; set; }
		/// <summary>
		/// State sync parameter 1
		/// </summary>
		public int Params1 { get; set; }
		/// <summary>
		/// State sync parameter 2
		/// </summary>
		public int Params2 { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(SceneObjLogicID);
			writer.WriteInt(ReqLogicID);
			writer.WriteInt(Params1);
			writer.WriteInt(Params2);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			SceneObjLogicID = reader.ReadInt();
			ReqLogicID = reader.ReadInt();
			Params1 = reader.ReadInt();
			Params2 = reader.ReadInt();
		}

    }
}