// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// PVP score notification
    /// </summary>
    public class CSPvpBoundsNtf : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_PVP_BOUNDS_NTF;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// PVP total score
		/// </summary>
		public int TotalBounds { get; set; }
		/// <summary>
		/// Red team score
		/// </summary>
		public int RedBounds { get; set; }
		/// <summary>
		/// Blue team score
		/// </summary>
		public int BlueBounds { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(TotalBounds);
			writer.WriteInt(RedBounds);
			writer.WriteInt(BlueBounds);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			TotalBounds = reader.ReadInt();
			RedBounds = reader.ReadInt();
			BlueBounds = reader.ReadInt();
		}

    }
}