// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Prepare stage start notification
    /// </summary>
    public class CSPVPPrepareStageStartNtf : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_PVP_PREPARE_STAGE_START;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Whether to show prepare stage UI
		/// </summary>
		public int ShowUI { get; set; }
		/// <summary>
		/// Prepare stage remaining time
		/// </summary>
		public int SelectRemainSeconds { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(ShowUI);
			writer.WriteInt(SelectRemainSeconds);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			ShowUI = reader.ReadInt();
			SelectRemainSeconds = reader.ReadInt();
		}

    }
}