// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// PVP instant achievement notification
    /// </summary>
    public class CSPvpAchievementNtf : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_PVP_ACHIEVEMENT_NTF;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Player NetID
		/// </summary>
		public uint NetID { get; set; }
		/// <summary>
		/// Player faction
		/// </summary>
		public int CampType { get; set; }
		/// <summary>
		/// Role name
		/// </summary>
		public string Name { get; set; }
		/// <summary>
		/// Achievement type
		/// </summary>
		public int AchievementType { get; set; }
		/// <summary>
		/// Obtained count
		/// </summary>
		public int GetCount { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteUInt(NetID);
			writer.WriteInt(CampType);
			if (Name.Length > (CsprotoConstants.CS_MAX_ROLE_NAME - 1))
			{
				throw new InvalidOperationException($"String length of 'Name' should be of length of {(CsprotoConstants.CS_MAX_ROLE_NAME - 1)} but was {Name.Length}.");
			}

			writer.WriteUTF(Name);
			writer.WriteInt(AchievementType);
			writer.WriteInt(GetCount);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			NetID = reader.ReadUInt();
			CampType = reader.ReadInt();
			Name = reader.ReadUTF();
			AchievementType = reader.ReadInt();
			GetCount = reader.ReadInt();
		}

    }
}