// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Quit instance queue
    /// </summary>
    public class CSQuitLineUpInstanceRsp : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_QUIT_LINE_UP_INSTANCE_RSP;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Error code
		/// </summary>
		public int ErrCode { get; set; }
		/// <summary>
		/// Player ID
		/// </summary>
		public uint NetID { get; set; }
		/// <summary>
		/// Role name
		/// </summary>
		public string Name { get; set; }
		/// <summary>
		/// Current room member count
		/// </summary>
		public int CurRoomMemCount { get; set; }
		/// <summary>
		/// Max room member count
		/// </summary>
		public int MaxRoomMemCount { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(ErrCode);
			writer.WriteUInt(NetID);
			if (Name.Length > (CsprotoConstants.CS_MAX_ROLE_NAME - 1))
			{
				throw new InvalidOperationException($"String length of 'Name' should be of length of {(CsprotoConstants.CS_MAX_ROLE_NAME - 1)} but was {Name.Length}.");
			}

			writer.WriteUTF(Name);
			writer.WriteInt(CurRoomMemCount);
			writer.WriteInt(MaxRoomMemCount);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			ErrCode = reader.ReadInt();
			NetID = reader.ReadUInt();
			Name = reader.ReadUTF();
			CurRoomMemCount = reader.ReadInt();
			MaxRoomMemCount = reader.ReadInt();
		}

    }
}