// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Quick change equipment
    /// </summary>
    public class CSQuickChangeEquipReq : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_ITEM_EQUIP_QUICK_CHANGE_REQ;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Equipment list
		/// </summary>
		public EquipParam[] EquipParamList { get; set; } = Array.Empty<EquipParam>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			// Write length for array: EquipParamList
			var EquipCnt = (int)(EquipParamList?.Length ?? 0);
			if (EquipCnt > CsprotoConstants.ROLE_EQUIPED_MAX_NETMESSAGE)
			{
				throw new InvalidOperationException($"Array length of 'EquipParamList' exceeds maximum allowed length of {CsprotoConstants.ROLE_EQUIPED_MAX_NETMESSAGE} but was {EquipCnt}.");
			}

			writer.WriteInt(EquipCnt);
			for (var i = 0; i < EquipCnt; i++)
			{
				EquipParamList[i]?.Serialize(writer);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			// Read length for array: EquipParamList
			var EquipCnt = reader.ReadInt();
			// Read array: EquipParamList
			EquipParamList = new EquipParam[Math.Min((int)EquipCnt, CsprotoConstants.ROLE_EQUIPED_MAX_NETMESSAGE)];
			for (var i = 0; i < EquipParamList.Length; i++)
			{
				EquipParamList[i] = new EquipParam();
				EquipParamList[i].Deserialize(reader);
			}
		}

    }
}