// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Random seed sync response
    /// </summary>
    public class CSRandSeedSyncRsp : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_RANDSEEDSYNC_RSP;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Entity ID
		/// </summary>
		public uint NetID { get; set; }
		/// <summary>
		/// Seed
		/// </summary>
		public uint RandSeed { get; set; }
		/// <summary>
		/// Random count
		/// </summary>
		public uint RandTimes { get; set; }
		/// <summary>
		/// Random before message
		/// </summary>
		public byte UsedBeforeMsg { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteUInt(NetID);
			writer.WriteUInt(RandSeed);
			writer.WriteUInt(RandTimes);
			writer.WriteByte(UsedBeforeMsg);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			NetID = reader.ReadUInt();
			RandSeed = reader.ReadUInt();
			RandTimes = reader.ReadUInt();
			UsedBeforeMsg = reader.ReadByte();
		}

    }
}