// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Equipment enhance broadcast
    /// </summary>
    public class CSResEquipEnforceBoard : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_ITEM_RES_EQUIP_ENFORCE_BOARD;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Item ID
		/// </summary>
		public int M_nItemID { get; set; }
		/// <summary>
		/// Enhance level
		/// </summary>
		public int M_nEnforceLv { get; set; }
		/// <summary>
		/// Player name
		/// </summary>
		public string M_strName { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(M_nItemID);
			writer.WriteInt(M_nEnforceLv);
			if (M_strName.Length != CsprotoConstants.CS_MAX_ROLE_NAME)
			{
				throw new InvalidOperationException($"Array length of 'M_strName' should be of length of {CsprotoConstants.CS_MAX_ROLE_NAME} but was {M_strName.Length}.");
			}

			writer.WriteUTF(M_strName);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			M_nItemID = reader.ReadInt();
			M_nEnforceLv = reader.ReadInt();
			M_strName = reader.ReadUTF();
		}

    }
}