// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Request socket equipment
    /// </summary>
    public class CSResEnchaseEquip : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_ITEM_RES_ENCHASEEQUIP;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Result
		/// </summary>
		public int Ret { get; set; }
		/// <summary>
		/// Equipment slot
		/// </summary>
		public byte EquipColumn { get; set; }
		/// <summary>
		/// Equipment grid
		/// </summary>
		public ushort EquipGrid { get; set; }
		/// <summary>
		/// Equipment socket
		/// </summary>
		public byte DstSlot { get; set; }
		/// <summary>
		/// Skill gem slot
		/// </summary>
		public byte Column { get; set; }
		/// <summary>
		/// Skill gem grid
		/// </summary>
		public ushort Grid { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(Ret);
			writer.WriteByte(EquipColumn);
			writer.WriteUShort(EquipGrid);
			writer.WriteByte(DstSlot);
			writer.WriteByte(Column);
			writer.WriteUShort(Grid);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Ret = reader.ReadInt();
			EquipColumn = reader.ReadByte();
			EquipGrid = reader.ReadUShort();
			DstSlot = reader.ReadByte();
			Column = reader.ReadByte();
			Grid = reader.ReadUShort();
		}

    }
}