// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Load ammo response
    /// </summary>
    public class CSReloadAmmoRsp : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_RELOAD_AMMO_RSP;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Loader id
		/// </summary>
		public int NetID { get; set; }
		public CSAmmoInfo[] Ammos { get; set; } = Array.Empty<CSAmmoInfo>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(NetID);
			// Write length for array: Ammos
			var Count = (int)(Ammos?.Length ?? 0);
			if (Count > CsprotoConstants.CS_MAX_AMMO_NUM)
			{
				throw new InvalidOperationException($"Array length of 'Ammos' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_AMMO_NUM} but was {Count}.");
			}

			writer.WriteInt(Count);
			for (var i = 0; i < Count; i++)
			{
				Ammos[i]?.Serialize(writer);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			NetID = reader.ReadInt();
			// Read length for array: Ammos
			var Count = reader.ReadInt();
			// Read array: Ammos
			Ammos = new CSAmmoInfo[Math.Min((int)Count, CsprotoConstants.CS_MAX_AMMO_NUM)];
			for (var i = 0; i < Ammos.Length; i++)
			{
				Ammos[i] = new CSAmmoInfo();
				Ammos[i].Deserialize(reader);
			}
		}

    }
}