// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Refine response
    /// </summary>
    public class CSResEquipFound : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_ITEM_RES_EQUIP_FOUND;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Result
		/// </summary>
		public int Ret { get; set; }
		/// <summary>
		/// Slot
		/// </summary>
		public byte EquipColumn { get; set; }
		/// <summary>
		/// Grid
		/// </summary>
		public ushort EquipGrid { get; set; }
		/// <summary>
		/// Locked attribute
		/// </summary>
		public byte LockAttr { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(Ret);
			writer.WriteByte(EquipColumn);
			writer.WriteUShort(EquipGrid);
			writer.WriteByte(LockAttr);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Ret = reader.ReadInt();
			EquipColumn = reader.ReadByte();
			EquipGrid = reader.ReadUShort();
			LockAttr = reader.ReadByte();
		}

    }
}