// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Revive other player response
    /// </summary>
    public class CSReviveOtherPlayerRsp : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_REVIVE_OTHER_PLAYER_RSP;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Player ID requesting revive
		/// </summary>
		public int PlayerID { get; set; }
		/// <summary>
		/// Target
		/// </summary>
		public int TargetID { get; set; }
		/// <summary>
		/// Revive point number
		/// </summary>
		public int RevivePoint { get; set; }
		/// <summary>
		/// Revive method, 0 on spot 1 cat cart -1 failed
		/// </summary>
		public int ReviveType { get; set; }
		/// <summary>
		/// If cat cart, this is corresponding cat cart LogicEntityID
		/// </summary>
		public int Param { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(PlayerID);
			writer.WriteInt(TargetID);
			writer.WriteInt(RevivePoint);
			writer.WriteInt(ReviveType);
			writer.WriteInt(Param);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			PlayerID = reader.ReadInt();
			TargetID = reader.ReadInt();
			RevivePoint = reader.ReadInt();
			ReviveType = reader.ReadInt();
			Param = reader.ReadInt();
		}

    }
}