// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Reply sort items
    /// </summary>
    public class CSResSortItem : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_ITEM_RES_SORTITEM;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Sort result
		/// </summary>
		public int Ret { get; set; }
		/// <summary>
		/// Column flag
		/// </summary>
		public byte SrcColumn { get; set; }
		/// <summary>
		/// Column start position
		/// </summary>
		public ushort BegIndex { get; set; }
		/// <summary>
		/// Column end position, inclusive
		/// </summary>
		public ushort EndIndex { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(Ret);
			writer.WriteByte(SrcColumn);
			writer.WriteUShort(BegIndex);
			writer.WriteUShort(EndIndex);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Ret = reader.ReadInt();
			SrcColumn = reader.ReadByte();
			BegIndex = reader.ReadUShort();
			EndIndex = reader.ReadUShort();
		}

    }
}