// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Request swap items at 2 positions
    /// </summary>
    public class CSReqSwapItem : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_ITEM_REQ_SWAPITEM;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Source column flag
		/// </summary>
		public byte SrcColumn { get; set; }
		/// <summary>
		/// Source column position
		/// </summary>
		public ushort SrcIndex { get; set; }
		/// <summary>
		/// Target column flag
		/// </summary>
		public byte DstColumn { get; set; }
		/// <summary>
		/// Target column position
		/// </summary>
		public ushort DstIndex { get; set; }
		/// <summary>
		/// Auto unequip if range mismatch
		/// </summary>
		public byte AutoDown { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteByte(SrcColumn);
			writer.WriteUShort(SrcIndex);
			writer.WriteByte(DstColumn);
			writer.WriteUShort(DstIndex);
			writer.WriteByte(AutoDown);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			SrcColumn = reader.ReadByte();
			SrcIndex = reader.ReadUShort();
			DstColumn = reader.ReadByte();
			DstIndex = reader.ReadUShort();
			AutoDown = reader.ReadByte();
		}

    }
}