// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Role basic info
    /// </summary>
    public class CSRoleBaseInfo
    {
		/// <summary>
		/// Role ID
		/// </summary>
		public ulong RoleID { get; set; }
		/// <summary>
		/// Role Index
		/// </summary>
		public int RoleIndex { get; set; }
		/// <summary>
		/// Role name
		/// </summary>
		public string Name { get; set; }
		/// <summary>
		/// Role gender
		/// </summary>
		public byte Gender { get; set; }
		/// <summary>
		/// Role level
		/// </summary>
		public int Level { get; set; }
		/// <summary>
		/// Role state
		/// </summary>
		public int RoleState { get; set; }
		/// <summary>
		/// Remaining time until role state ends
		/// </summary>
		public uint RoleStateEndLeftTime { get; set; }
		/// <summary>
		/// Avatar Set
		/// </summary>
		public byte AvatarSetID { get; set; }
		/// <summary>
		/// Face type
		/// </summary>
		public ushort FaceId { get; set; }
		/// <summary>
		/// Hair style
		/// </summary>
		public ushort HairId { get; set; }
		/// <summary>
		/// Underclothes
		/// </summary>
		public ushort UnderclothesId { get; set; }
		/// <summary>
		/// Skin color
		/// </summary>
		public int SkinColor { get; set; }
		/// <summary>
		/// Hair color
		/// </summary>
		public int HairColor { get; set; }
		/// <summary>
		/// Inner color
		/// </summary>
		public int InnerColor { get; set; }
		/// <summary>
		/// Eyes
		/// </summary>
		public int EyeBall { get; set; }
		/// <summary>
		/// Eye color
		/// </summary>
		public int EyeColor { get; set; }
		/// <summary>
		/// Face tattoo
		/// </summary>
		public int FaceTattooIndex { get; set; }
		/// <summary>
		/// Face tattoo color
		/// </summary>
		public int FaceTattooColor { get; set; }
		/// <summary>
		/// Equipment items
		/// </summary>
		public CSAvatarItem[] Equip { get; set; } = Array.Empty<CSAvatarItem>();
		/// <summary>
		/// Whether to hide helmet
		/// </summary>
		public byte HideHelm { get; set; }
		/// <summary>
		/// Whether to hide fashion
		/// </summary>
		public byte HideFashion { get; set; }
		/// <summary>
		/// Whether to hide suite
		/// </summary>
		public byte HideSuite { get; set; }
		/// <summary>
		/// Face customization data set
		/// </summary>
		public short[] FacialInfo { get; set; } = Array.Empty<short>();
		/// <summary>
		/// Star level
		/// </summary>
		public string StarLevel { get; set; }
		/// <summary>
		/// Role HR level
		/// </summary>
		public int HRLevel { get; set; }
		/// <summary>
		/// Soul stone level
		/// </summary>
		public int SoulStoneLv { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteULong(RoleID);
			writer.WriteInt(RoleIndex);
			if (Name.Length != CsprotoConstants.CS_MAX_ROLE_NAME)
			{
				throw new InvalidOperationException($"Array length of 'Name' should be of length of {CsprotoConstants.CS_MAX_ROLE_NAME} but was {Name.Length}.");
			}

			writer.WriteUTF(Name);
			writer.WriteByte(Gender);
			writer.WriteInt(Level);
			writer.WriteInt(RoleState);
			writer.WriteUInt(RoleStateEndLeftTime);
			writer.WriteByte(AvatarSetID);
			writer.WriteUShort(FaceId);
			writer.WriteUShort(HairId);
			writer.WriteUShort(UnderclothesId);
			// Write length for array: Equip
			var EquipCount = (ushort)(Equip?.Length ?? 0);
			if (EquipCount > CsprotoConstants.ROLE_EQUIPED_MAX_NETMESSAGE)
			{
				throw new InvalidOperationException($"Array length of 'Equip' exceeds maximum allowed length of {CsprotoConstants.ROLE_EQUIPED_MAX_NETMESSAGE} but was {EquipCount}.");
			}

			writer.WriteUShort(EquipCount);
			writer.WriteInt(SkinColor);
			writer.WriteInt(HairColor);
			writer.WriteInt(InnerColor);
			writer.WriteInt(EyeBall);
			writer.WriteInt(EyeColor);
			writer.WriteInt(FaceTattooIndex);
			writer.WriteInt(FaceTattooColor);
			for (var i = 0; i < EquipCount; i++)
			{
				Equip[i]?.Serialize(writer);
			}
			writer.WriteByte(HideHelm);
			writer.WriteByte(HideFashion);
			writer.WriteByte(HideSuite);
			if ((FacialInfo?.Length ?? 0) != CsprotoConstants.CS_MAX_FACIALINFO_COUNT)
			{
				throw new InvalidOperationException($"Array length of 'FacialInfo' should be of length of {CsprotoConstants.CS_MAX_FACIALINFO_COUNT} but was {(FacialInfo?.Length ?? 0)}.");
			}

			for (var i = 0; i < CsprotoConstants.CS_MAX_FACIALINFO_COUNT; i++)
			{
				writer.WriteShort(FacialInfo[i]);
			}
			if (StarLevel.Length != CsprotoConstants.CS_MAX_HUNTER_STAR_LEVEL_LEN)
			{
				throw new InvalidOperationException($"Array length of 'StarLevel' should be of length of {CsprotoConstants.CS_MAX_HUNTER_STAR_LEVEL_LEN} but was {StarLevel.Length}.");
			}

			writer.WriteUTF(StarLevel);
			writer.WriteInt(HRLevel);
			writer.WriteInt(SoulStoneLv);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			RoleID = reader.ReadULong();
			RoleIndex = reader.ReadInt();
			Name = reader.ReadUTF();
			Gender = reader.ReadByte();
			Level = reader.ReadInt();
			RoleState = reader.ReadInt();
			RoleStateEndLeftTime = reader.ReadUInt();
			AvatarSetID = reader.ReadByte();
			FaceId = reader.ReadUShort();
			HairId = reader.ReadUShort();
			UnderclothesId = reader.ReadUShort();
			// Read length for array: Equip
			var EquipCount = reader.ReadUShort();
			SkinColor = reader.ReadInt();
			HairColor = reader.ReadInt();
			InnerColor = reader.ReadInt();
			EyeBall = reader.ReadInt();
			EyeColor = reader.ReadInt();
			FaceTattooIndex = reader.ReadInt();
			FaceTattooColor = reader.ReadInt();
			// Read array: Equip
			Equip = new CSAvatarItem[Math.Min((int)EquipCount, CsprotoConstants.ROLE_EQUIPED_MAX_NETMESSAGE)];
			for (var i = 0; i < Equip.Length; i++)
			{
				Equip[i] = new CSAvatarItem();
				Equip[i].Deserialize(reader);
			}
			HideHelm = reader.ReadByte();
			HideFashion = reader.ReadByte();
			HideSuite = reader.ReadByte();
			// Read array: FacialInfo
			FacialInfo = new short[CsprotoConstants.CS_MAX_FACIALINFO_COUNT];
			for (var i = 0; i < FacialInfo.Length; i++)
			{
				FacialInfo[i] = reader.ReadShort();
			}
			StarLevel = reader.ReadUTF();
			HRLevel = reader.ReadInt();
			SoulStoneLv = reader.ReadInt();
		}

    }
}