// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Role
    /// </summary>
    public class CSRole
    {
		/// <summary>
		/// Name
		/// </summary>
		public string Name { get; set; }
		/// <summary>
		/// Dbid
		/// </summary>
		public ulong Dbid { get; set; }
		/// <summary>
		/// Rtid
		/// </summary>
		public uint Rtid { get; set; }
		/// <summary>
		/// Uin
		/// </summary>
		public ulong Uin { get; set; }
		/// <summary>
		/// Reward
		/// </summary>
		public int CelebrationReward { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			if (Name.Length != CsprotoConstants.CS_MAX_ROLE_NAME)
			{
				throw new InvalidOperationException($"Array length of 'Name' should be of length of {CsprotoConstants.CS_MAX_ROLE_NAME} but was {Name.Length}.");
			}

			writer.WriteUTF(Name);
			writer.WriteULong(Dbid);
			writer.WriteUInt(Rtid);
			writer.WriteULong(Uin);
			writer.WriteInt(CelebrationReward);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Name = reader.ReadUTF();
			Dbid = reader.ReadULong();
			Rtid = reader.ReadUInt();
			Uin = reader.ReadULong();
			CelebrationReward = reader.ReadInt();
		}

    }
}