// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// global token
    /// </summary>
    public class CSScriptActivityGlobalToken
    {
		/// <summary>
		/// key
		/// </summary>
		public string Key { get; set; }
		/// <summary>
		/// value
		/// </summary>
		public int Value { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			if (Key.Length > (128 - 1))
			{
				throw new InvalidOperationException($"String length of 'Key' should be of length of {(128 - 1)} but was {Key.Length}.");
			}

			writer.WriteUTF(Key);
			writer.WriteInt(Value);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Key = reader.ReadUTF();
			Value = reader.ReadInt();
		}

    }
}