// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Sculpture Avatar
    /// </summary>
    public class CSSculptureAvatar
    {
		/// <summary>
		/// Sculpture avatar
		/// </summary>
		public byte[] AvatarData { get; set; } = Array.Empty<byte>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			// Write length for array: AvatarData
			var AvatarSize = (int)(AvatarData?.Length ?? 0);
			if (AvatarSize > CsprotoConstants.CS_MAX_SCULPTURE_AVATAR_LEN)
			{
				throw new InvalidOperationException($"Array length of 'AvatarData' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_SCULPTURE_AVATAR_LEN} but was {AvatarSize}.");
			}

			writer.WriteInt(AvatarSize);
			for (var i = 0; i < AvatarSize; i++)
			{
				writer.WriteByte(AvatarData[i]);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			// Read length for array: AvatarData
			var AvatarSize = reader.ReadInt();
			// Read array: AvatarData
			AvatarData = new byte[Math.Min((int)AvatarSize, CsprotoConstants.CS_MAX_SCULPTURE_AVATAR_LEN)];
			for (var i = 0; i < AvatarData.Length; i++)
			{
				AvatarData[i] = reader.ReadByte();
			}
		}

    }
}