// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Select role request
    /// </summary>
    public class CSSelectRoleReq : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_SELECT_ROLE_REQ;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Role Index
		/// </summary>
		public int RoleIndex { get; set; }
		/// <summary>
		/// Client MAC address
		/// </summary>
		public string MacAddress { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(RoleIndex);
			if (MacAddress.Length != CsprotoConstants.CS_MAC_ADDRESS_LEN)
			{
				throw new InvalidOperationException($"Array length of 'MacAddress' should be of length of {CsprotoConstants.CS_MAC_ADDRESS_LEN} but was {MacAddress.Length}.");
			}

			writer.WriteUTF(MacAddress);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			RoleIndex = reader.ReadInt();
			MacAddress = reader.ReadUTF();
		}

    }
}