// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Set PVE rage response
    /// </summary>
    public class CSSetPVERageRsp : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_SET_PVE_RAGE_RSP;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Weapon type
		/// </summary>
		public int WeaponType { get; set; }
		/// <summary>
		/// Index
		/// </summary>
		public int Idx { get; set; }
		/// <summary>
		/// Error code
		/// </summary>
		public int ErrorID { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(WeaponType);
			writer.WriteInt(Idx);
			writer.WriteInt(ErrorID);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			WeaponType = reader.ReadInt();
			Idx = reader.ReadInt();
			ErrorID = reader.ReadInt();
		}

    }
}