// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Shortcut bar data
    /// </summary>
    public class CSShortcut
    {
		/// <summary>
		/// Shortcut bar position
		/// </summary>
		public uint NPos { get; set; }
		/// <summary>
		/// Item ID
		/// </summary>
		public uint NItemID { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteUInt(NPos);
			writer.WriteUInt(NItemID);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			NPos = reader.ReadUInt();
			NItemID = reader.ReadUInt();
		}

    }
}