// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Daily
    /// </summary>
    public class CSShop
    {
		/// <summary>
		/// Refresh time
		/// </summary>
		public uint RefreshTime { get; set; }
		/// <summary>
		/// Library
		/// </summary>
		public int Lib { get; set; }
		/// <summary>
		/// Manual refresh times
		/// </summary>
		public int ResetTimes { get; set; }
		/// <summary>
		/// Commodities
		/// </summary>
		public CSCommodity[] Commodity { get; set; } = Array.Empty<CSCommodity>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteUInt(RefreshTime);
			writer.WriteInt(Lib);
			writer.WriteInt(ResetTimes);
			// Write length for array: Commodity
			var CommodityCount = (short)(Commodity?.Length ?? 0);
			if (CommodityCount > CsprotoConstants.CS_MAX_SHOP_LIB_COMMODITY_LEN)
			{
				throw new InvalidOperationException($"Array length of 'Commodity' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_SHOP_LIB_COMMODITY_LEN} but was {CommodityCount}.");
			}

			writer.WriteShort(CommodityCount);
			for (var i = 0; i < CommodityCount; i++)
			{
				Commodity[i]?.Serialize(writer);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			RefreshTime = reader.ReadUInt();
			Lib = reader.ReadInt();
			ResetTimes = reader.ReadInt();
			// Read length for array: Commodity
			var CommodityCount = reader.ReadShort();
			// Read array: Commodity
			Commodity = new CSCommodity[Math.Min((int)CommodityCount, CsprotoConstants.CS_MAX_SHOP_LIB_COMMODITY_LEN)];
			for (var i = 0; i < Commodity.Length; i++)
			{
				Commodity[i] = new CSCommodity();
				Commodity[i].Deserialize(reader);
			}
		}

    }
}