// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    public class CSSimpleActionParam : CSObjectActionParam
    {
		public const CS_SCENE_OBJECT_ACTION_TYPE ProtocolIdConst = CS_SCENE_OBJECT_ACTION_TYPE.CS_ACTION_TYPE_SIMPLE;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Action type
		/// </summary>
		public int ActionType { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(ActionType);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			ActionType = reader.ReadInt();
		}

    }
}