// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Skill result sync info
    /// </summary>
    public class CSSkillResultList : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_SKILL_RESULT_SYNC;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Entity ID
		/// </summary>
		public uint EntityId { get; set; }
		/// <summary>
		/// Result list
		/// </summary>
		public CSSkillResult[] Result { get; set; } = Array.Empty<CSSkillResult>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteUInt(EntityId);
			// Write length for array: Result
			var Count = (short)(Result?.Length ?? 0);
			if (Count > CsprotoConstants.CS_MAX_SKILL_RESULT_NUM)
			{
				throw new InvalidOperationException($"Array length of 'Result' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_SKILL_RESULT_NUM} but was {Count}.");
			}

			writer.WriteShort(Count);
			for (var i = 0; i < Count; i++)
			{
				Result[i]?.Serialize(writer);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			EntityId = reader.ReadUInt();
			// Read length for array: Result
			var Count = reader.ReadShort();
			// Read array: Result
			Result = new CSSkillResult[Math.Min((int)Count, CsprotoConstants.CS_MAX_SKILL_RESULT_NUM)];
			for (var i = 0; i < Result.Length; i++)
			{
				Result[i] = new CSSkillResult();
				Result[i].Deserialize(reader);
			}
		}

    }
}