// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Skill effect sync info
    /// </summary>
    public class CSSkillEffectInfo : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_SKILL_EFFECT_SYNC;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Entity ID
		/// </summary>
		public uint EntityId { get; set; }
		/// <summary>
		/// Skill ID
		/// </summary>
		public int SkillID { get; set; }
		/// <summary>
		/// Skill level
		/// </summary>
		public int SkillLevel { get; set; }
		/// <summary>
		/// Skill effect type
		/// </summary>
		public int Type { get; set; }
		/// <summary>
		/// Skill effect name
		/// </summary>
		public string EventName { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteUInt(EntityId);
			writer.WriteInt(SkillID);
			writer.WriteInt(SkillLevel);
			writer.WriteInt(Type);
			if (EventName.Length > (CsprotoConstants.CS_MAX_SKILL_EVENT_NAME_LEN - 1))
			{
				throw new InvalidOperationException($"String length of 'EventName' should be of length of {(CsprotoConstants.CS_MAX_SKILL_EVENT_NAME_LEN - 1)} but was {EventName.Length}.");
			}

			writer.WriteUTF(EventName);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			EntityId = reader.ReadUInt();
			SkillID = reader.ReadInt();
			SkillLevel = reader.ReadInt();
			Type = reader.ReadInt();
			EventName = reader.ReadUTF();
		}

    }
}