// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Speak execute
    /// </summary>
    public class CSSpeaksExec
    {
		/// <summary>
		/// Speak execute
		/// </summary>
		public CSSpeakExec[] Exec { get; set; } = Array.Empty<CSSpeakExec>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			// Write length for array: Exec
			var Count = (byte)(Exec?.Length ?? 0);
			if (Count > CsprotoConstants.CS_MAX_EXEC_SPEAK_LEN)
			{
				throw new InvalidOperationException($"Array length of 'Exec' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_EXEC_SPEAK_LEN} but was {Count}.");
			}

			writer.WriteByte(Count);
			for (var i = 0; i < Count; i++)
			{
				Exec[i]?.Serialize(writer);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			// Read length for array: Exec
			var Count = reader.ReadByte();
			// Read array: Exec
			Exec = new CSSpeakExec[Math.Min((int)Count, CsprotoConstants.CS_MAX_EXEC_SPEAK_LEN)];
			for (var i = 0; i < Exec.Length; i++)
			{
				Exec[i] = new CSSpeakExec();
				Exec[i].Deserialize(reader);
			}
		}

    }
}