// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Unlock suit skill response
    /// </summary>
    public class CSSuitSkillUnlockRsp : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_SUITSKILL_UNLOCK_RSP;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Response code
		/// </summary>
		public int RetCode { get; set; }
		/// <summary>
		/// Error parameter
		/// </summary>
		public int Arg { get; set; }
		/// <summary>
		/// Skill group
		/// </summary>
		public int Group { get; set; }
		/// <summary>
		/// Skill ID
		/// </summary>
		public int Skill { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(RetCode);
			writer.WriteInt(Arg);
			writer.WriteInt(Group);
			writer.WriteInt(Skill);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			RetCode = reader.ReadInt();
			Arg = reader.ReadInt();
			Group = reader.ReadInt();
			Skill = reader.ReadInt();
		}

    }
}