// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Suit skill edit request
    /// </summary>
    public class CSSuitSkillEditReq : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_SUITSKILL_EDIT_REQ;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Skill group
		/// </summary>
		public int Group { get; set; }
		public int[] SkillID { get; set; } = Array.Empty<int>();
		/// <summary>
		/// Whether to use item
		/// </summary>
		public int ItemFlag { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(Group);
			// Write length for array: SkillID
			var SkillCnt = (int)(SkillID?.Length ?? 0);
			if (SkillCnt > CsprotoConstants.CS_MAX_GROUP_SKILL)
			{
				throw new InvalidOperationException($"Array length of 'SkillID' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_GROUP_SKILL} but was {SkillCnt}.");
			}

			writer.WriteInt(SkillCnt);
			for (var i = 0; i < SkillCnt; i++)
			{
				writer.WriteInt(SkillID[i]);
			}
			writer.WriteInt(ItemFlag);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Group = reader.ReadInt();
			// Read length for array: SkillID
			var SkillCnt = reader.ReadInt();
			// Read array: SkillID
			SkillID = new int[Math.Min((int)SkillCnt, CsprotoConstants.CS_MAX_GROUP_SKILL)];
			for (var i = 0; i < SkillID.Length; i++)
			{
				SkillID[i] = reader.ReadInt();
			}
			ItemFlag = reader.ReadInt();
		}

    }
}