// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Initialize
    /// </summary>
    public class CSSupplyBoxInitItemNtf : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_SUPPLY_BOX_INIT_ITEM_NTF;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Supply box type
		/// </summary>
		public byte SupplyBoxType { get; set; }
		/// <summary>
		/// Share identifier
		/// </summary>
		public uint ShareId { get; set; }
		/// <summary>
		/// Whether supply cat unlocked
		/// </summary>
		public byte SupplyCatUnlock { get; set; }
		/// <summary>
		/// Supply item list
		/// </summary>
		public CSSupplyItem[] SupplyItemList { get; set; } = Array.Empty<CSSupplyItem>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteByte(SupplyBoxType);
			writer.WriteUInt(ShareId);
			writer.WriteByte(SupplyCatUnlock);
			// Write length for array: SupplyItemList
			var ItemCount = (int)(SupplyItemList?.Length ?? 0);
			if (ItemCount > CsprotoConstants.CS_MAX_SUPPLY_ITEM)
			{
				throw new InvalidOperationException($"Array length of 'SupplyItemList' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_SUPPLY_ITEM} but was {ItemCount}.");
			}

			writer.WriteInt(ItemCount);
			for (var i = 0; i < ItemCount; i++)
			{
				SupplyItemList[i]?.Serialize(writer);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			SupplyBoxType = reader.ReadByte();
			ShareId = reader.ReadUInt();
			SupplyCatUnlock = reader.ReadByte();
			// Read length for array: SupplyItemList
			var ItemCount = reader.ReadInt();
			// Read array: SupplyItemList
			SupplyItemList = new CSSupplyItem[Math.Min((int)ItemCount, CsprotoConstants.CS_MAX_SUPPLY_ITEM)];
			for (var i = 0; i < SupplyItemList.Length; i++)
			{
				SupplyItemList[i] = new CSSupplyItem();
				SupplyItemList[i].Deserialize(reader);
			}
		}

    }
}