// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Quick team search team list request
    /// </summary>
    public class CSTeamSearchTeamsReq : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_TEAM_SEARCH_TEAMS_REQ;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Mode
		/// </summary>
		public short LevelMode { get; set; }
		/// <summary>
		/// Region (map ID)
		/// </summary>
		public uint MapId { get; set; }
		/// <summary>
		/// Level (level group ID)
		/// </summary>
		public uint LevelGrpId { get; set; }
		/// <summary>
		/// Difficulty
		/// </summary>
		public short Difficulty { get; set; }
		/// <summary>
		/// All lines (cross-line bool)
		/// </summary>
		public short CrossLine { get; set; }
		/// <summary>
		/// Paging: start team index (from 0, inclusive)
		/// </summary>
		public uint BeginFrom { get; set; }
		/// <summary>
		/// Paging: end team index (exclusive)
		/// </summary>
		public uint EndTo { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteShort(LevelMode);
			writer.WriteUInt(MapId);
			writer.WriteUInt(LevelGrpId);
			writer.WriteShort(Difficulty);
			writer.WriteShort(CrossLine);
			writer.WriteUInt(BeginFrom);
			writer.WriteUInt(EndTo);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			LevelMode = reader.ReadShort();
			MapId = reader.ReadUInt();
			LevelGrpId = reader.ReadUInt();
			Difficulty = reader.ReadShort();
			CrossLine = reader.ReadShort();
			BeginFrom = reader.ReadUInt();
			EndTo = reader.ReadUInt();
		}

    }
}