// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Team member add/del buff sync
    /// </summary>
    public class CSTeamMemberBuffAddDelNtf : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_TEAM_MEMBER_BUFF_ADDDEL_NTF;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Member NetID
		/// </summary>
		public uint NetId { get; set; }
		/// <summary>
		/// Buff operation (add/del)
		/// </summary>
		public int BuffOp { get; set; }
		/// <summary>
		/// Buff Id
		/// </summary>
		public int BuffId { get; set; }
		public int BuffRetainTime { get; set; }
		public int BuffStackCount { get; set; }
		/// <summary>
		/// Member dbid
		/// </summary>
		public ulong Dbid { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteUInt(NetId);
			writer.WriteInt(BuffOp);
			writer.WriteInt(BuffId);
			writer.WriteInt(BuffRetainTime);
			writer.WriteInt(BuffStackCount);
			writer.WriteULong(Dbid);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			NetId = reader.ReadUInt();
			BuffOp = reader.ReadInt();
			BuffId = reader.ReadInt();
			BuffRetainTime = reader.ReadInt();
			BuffStackCount = reader.ReadInt();
			Dbid = reader.ReadULong();
		}

    }
}