// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Team member move notify
    /// </summary>
    public class CSTeamMemberMoveNtf : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_TEAM_MEMBER_MOVE_NTF;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		public ulong DBID { get; set; }
		/// <summary>
		/// Position
		/// </summary>
		public CSVec3 Vec3 { get; set; }
		/// <summary>
		/// Direction
		/// </summary>
		public CSVec3 Dir { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteULong(DBID);
			Vec3?.Serialize(writer);
			Dir?.Serialize(writer);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			DBID = reader.ReadULong();
			Vec3 = new CSVec3();
			Vec3.Deserialize(reader);
			Dir = new CSVec3();
			Dir.Deserialize(reader);
		}

    }
}