// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Reply team invite
    /// </summary>
    public class CSTeamInviteRet : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_TEAM_INVITE_RET;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Team inviter
		/// </summary>
		public uint SrcPlayerId { get; set; }
		/// <summary>
		/// Inviter team ID
		/// </summary>
		public uint SrcTeamId { get; set; }
		/// <summary>
		/// Reply 0-accept, 1-decline
		/// </summary>
		public int InviteRet { get; set; }
		/// <summary>
		/// Invite time
		/// </summary>
		public uint InviteTime { get; set; }
		/// <summary>
		/// Verification code
		/// </summary>
		public uint VerifyCode { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteUInt(SrcPlayerId);
			writer.WriteUInt(SrcTeamId);
			writer.WriteInt(InviteRet);
			writer.WriteUInt(InviteTime);
			writer.WriteUInt(VerifyCode);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			SrcPlayerId = reader.ReadUInt();
			SrcTeamId = reader.ReadUInt();
			InviteRet = reader.ReadInt();
			InviteTime = reader.ReadUInt();
			VerifyCode = reader.ReadUInt();
		}

    }
}