// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Team notify
    /// </summary>
    public class CSTeamNotify : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_TEAM_NOTIFY;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Type
		/// </summary>
		public int Type { get; set; }
		/// <summary>
		/// Parameter 1
		/// </summary>
		public int Arg1 { get; set; }
		/// <summary>
		/// Parameter 2
		/// </summary>
		public int Arg2 { get; set; }
		/// <summary>
		/// Parameter 3
		/// </summary>
		public string Arg3 { get; set; }
		/// <summary>
		/// Parameter 4
		/// </summary>
		public string Arg4 { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(Type);
			writer.WriteInt(Arg1);
			writer.WriteInt(Arg2);
			if (Arg3.Length != CsprotoConstants.CS_MAX_TEAM_STR_LEN)
			{
				throw new InvalidOperationException($"Array length of 'Arg3' should be of length of {CsprotoConstants.CS_MAX_TEAM_STR_LEN} but was {Arg3.Length}.");
			}

			writer.WriteUTF(Arg3);
			if (Arg4.Length != CsprotoConstants.CS_MAX_TEAM_STR_LEN)
			{
				throw new InvalidOperationException($"Array length of 'Arg4' should be of length of {CsprotoConstants.CS_MAX_TEAM_STR_LEN} but was {Arg4.Length}.");
			}

			writer.WriteUTF(Arg4);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Type = reader.ReadInt();
			Arg1 = reader.ReadInt();
			Arg2 = reader.ReadInt();
			Arg3 = reader.ReadUTF();
			Arg4 = reader.ReadUTF();
		}

    }
}