// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Quick join team request
    /// </summary>
    public class CSTeamQuickJoinReq : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_TEAM_QUICK_JOIN_REQ;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Mode
		/// </summary>
		public int Mode { get; set; }
		/// <summary>
		/// Region (map ID)
		/// </summary>
		public int Map { get; set; }
		/// <summary>
		/// Level (level group ID)
		/// </summary>
		public int Level { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(Mode);
			writer.WriteInt(Map);
			writer.WriteInt(Level);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Mode = reader.ReadInt();
			Map = reader.ReadInt();
			Level = reader.ReadInt();
		}

    }
}