// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Quick team search by team name request
    /// </summary>
    public class CSTeamSearchByNameReq : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_TEAM_SEARCH_BY_NAME_REQ;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Team name
		/// </summary>
		public string Name { get; set; }
		/// <summary>
		/// Paging: start team index (from 0, inclusive)
		/// </summary>
		public uint Begin { get; set; }
		/// <summary>
		/// Paging: end team index (exclusive)
		/// </summary>
		public uint End { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			if (Name.Length != CsprotoConstants.CS_MAX_TEAM_NAME)
			{
				throw new InvalidOperationException($"Array length of 'Name' should be of length of {CsprotoConstants.CS_MAX_TEAM_NAME} but was {Name.Length}.");
			}

			writer.WriteUTF(Name);
			writer.WriteUInt(Begin);
			writer.WriteUInt(End);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Name = reader.ReadUTF();
			Begin = reader.ReadUInt();
			End = reader.ReadUInt();
		}

    }
}