// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Quick team modify request
    /// </summary>
    public class CSTeamModifyReq : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_TEAM_MODIFY_REQ;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Team config info
		/// </summary>
		public CSTeamSetting TeamSetting { get; set; }
		/// <summary>
		/// Team name
		/// </summary>
		public string TeamName { get; set; }
		/// <summary>
		/// Mode
		/// </summary>
		public short TargetMode { get; set; }
		/// <summary>
		/// Region (map ID)
		/// </summary>
		public uint TargetMap { get; set; }
		/// <summary>
		/// Level (level group ID)
		/// </summary>
		public uint TargetLevelGrp { get; set; }
		/// <summary>
		/// Difficulty
		/// </summary>
		public short Difficulty { get; set; }
		/// <summary>
		/// Max team members
		/// </summary>
		public ushort MemberMax { get; set; }
		/// <summary>
		/// Free join (set to 0 for leader auth)
		/// </summary>
		public int FreeJoin { get; set; }
		/// <summary>
		/// Whether allow public recruit (0-no, 1-yes)
		/// </summary>
		public int OpenRecruit { get; set; }
		/// <summary>
		/// Join password
		/// </summary>
		public string Pwd { get; set; }
		/// <summary>
		/// Min level limit
		/// </summary>
		public ushort MinLevel { get; set; }
		/// <summary>
		/// Max level limit
		/// </summary>
		public ushort MaxLevel { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			TeamSetting?.Serialize(writer);
			if (TeamName.Length > (CsprotoConstants.CS_MAX_TEAM_NAME - 1))
			{
				throw new InvalidOperationException($"String length of 'TeamName' should be of length of {(CsprotoConstants.CS_MAX_TEAM_NAME - 1)} but was {TeamName.Length}.");
			}

			writer.WriteUTF(TeamName);
			writer.WriteShort(TargetMode);
			writer.WriteUInt(TargetMap);
			writer.WriteUInt(TargetLevelGrp);
			writer.WriteShort(Difficulty);
			writer.WriteUShort(MemberMax);
			writer.WriteInt(FreeJoin);
			writer.WriteInt(OpenRecruit);
			if (Pwd.Length > (CsprotoConstants.CS_MAX_ROLE_NAME - 1))
			{
				throw new InvalidOperationException($"String length of 'Pwd' should be of length of {(CsprotoConstants.CS_MAX_ROLE_NAME - 1)} but was {Pwd.Length}.");
			}

			writer.WriteUTF(Pwd);
			writer.WriteUShort(MinLevel);
			writer.WriteUShort(MaxLevel);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			TeamSetting = new CSTeamSetting();
			TeamSetting.Deserialize(reader);
			TeamName = reader.ReadUTF();
			TargetMode = reader.ReadShort();
			TargetMap = reader.ReadUInt();
			TargetLevelGrp = reader.ReadUInt();
			Difficulty = reader.ReadShort();
			MemberMax = reader.ReadUShort();
			FreeJoin = reader.ReadInt();
			OpenRecruit = reader.ReadInt();
			Pwd = reader.ReadUTF();
			MinLevel = reader.ReadUShort();
			MaxLevel = reader.ReadUShort();
		}

    }
}