// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Thousand layer tower floor clear time
    /// </summary>
    public class CSThousandLayerDataInfo
    {
		/// <summary>
		/// Level ID
		/// </summary>
		public int LevelID { get; set; }
		/// <summary>
		/// Floor best score
		/// </summary>
		public int Seconds { get; set; }
		/// <summary>
		/// Floor number
		/// </summary>
		public short Layer { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(LevelID);
			writer.WriteInt(Seconds);
			writer.WriteShort(Layer);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			LevelID = reader.ReadInt();
			Seconds = reader.ReadInt();
			Layer = reader.ReadShort();
		}

    }
}