// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    public class CSTitleFetchDataRsp : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_TITLE_FETCH_DATA_RSP;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		public int ErrCode { get; set; }
		public CSTitleData[] TitleData { get; set; } = Array.Empty<CSTitleData>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(ErrCode);
			// Write length for array: TitleData
			var TitleDataCount = (int)(TitleData?.Length ?? 0);
			if (TitleDataCount > CsprotoConstants.MAX_TITLE_SYNC_COUNT)
			{
				throw new InvalidOperationException($"Array length of 'TitleData' exceeds maximum allowed length of {CsprotoConstants.MAX_TITLE_SYNC_COUNT} but was {TitleDataCount}.");
			}

			writer.WriteInt(TitleDataCount);
			for (var i = 0; i < TitleDataCount; i++)
			{
				TitleData[i]?.Serialize(writer);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			ErrCode = reader.ReadInt();
			// Read length for array: TitleData
			var TitleDataCount = reader.ReadInt();
			// Read array: TitleData
			TitleData = new CSTitleData[Math.Min((int)TitleDataCount, CsprotoConstants.MAX_TITLE_SYNC_COUNT)];
			for (var i = 0; i < TitleData.Length; i++)
			{
				TitleData[i] = new CSTitleData();
				TitleData[i].Deserialize(reader);
			}
		}

    }
}