// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    public class CSTowerSupplyCloseNtf : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_TOWER_SUPPLY_CLOSE_NTF;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Floor number
		/// </summary>
		public int Layer { get; set; }
		/// <summary>
		/// Appraisal level
		/// </summary>
		public int Appraisal { get; set; }
		/// <summary>
		/// Floor supply ID
		/// </summary>
		public int TowerSupplyID { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(Layer);
			writer.WriteInt(Appraisal);
			writer.WriteInt(TowerSupplyID);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Layer = reader.ReadInt();
			Appraisal = reader.ReadInt();
			TowerSupplyID = reader.ReadInt();
		}

    }
}