// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Tower supply item structure
    /// </summary>
    public class CSTowerItemInfo
    {
		/// <summary>
		/// id
		/// </summary>
		public uint ItemID { get; set; }
		/// <summary>
		/// num
		/// </summary>
		public int ItemCount { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteUInt(ItemID);
			writer.WriteInt(ItemCount);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			ItemID = reader.ReadUInt();
			ItemCount = reader.ReadInt();
		}

    }
}