// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    public class CSTowerMemberInfo
    {
		/// <summary>
		/// Player ID
		/// </summary>
		public int PlayerNetID { get; set; }
		/// <summary>
		/// Damage dealt
		/// </summary>
		public int Attack { get; set; }
		/// <summary>
		/// Damage taken
		/// </summary>
		public int Defense { get; set; }
		public string RoleName { get; set; }
		/// <summary>
		/// Best historical time in seconds
		/// </summary>
		public int BestHistoryTime { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(PlayerNetID);
			writer.WriteInt(Attack);
			writer.WriteInt(Defense);
			if (RoleName.Length > (CsprotoConstants.CS_MAX_ROLE_NAME - 1))
			{
				throw new InvalidOperationException($"String length of 'RoleName' should be of length of {(CsprotoConstants.CS_MAX_ROLE_NAME - 1)} but was {RoleName.Length}.");
			}

			writer.WriteUTF(RoleName);
			writer.WriteInt(BestHistoryTime);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			PlayerNetID = reader.ReadInt();
			Attack = reader.ReadInt();
			Defense = reader.ReadInt();
			RoleName = reader.ReadUTF();
			BestHistoryTime = reader.ReadInt();
		}

    }
}