// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    public class CSVar
    {
		/// <summary>
		/// Identifier
		/// </summary>
		public int Id { get; set; }
		/// <summary>
		/// Value type
		/// </summary>
		public CS_ANY_TYPE Type { get; set; }
		/// <summary>
		/// Value
		/// </summary>
		public CSAny Val { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(Id);
			writer.WriteInt((int)Type);
			// Selected by: Type
			Val?.Serialize(writer);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Id = reader.ReadInt();
			Type = (CS_ANY_TYPE)reader.ReadInt();
			// Selected by: Type
			Val = ProtocolTypeManager.Get<CSAny>(Type);
			Val.Deserialize(reader);
		}

    }
}