// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// VIP service renewal request
    /// </summary>
    public class CSVIPServiceRenewReq : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_VIP_SERVICE_RENEW_REQ;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Renewal type
		/// </summary>
		public int RenewType { get; set; }
		/// <summary>
		/// VIP service type
		/// </summary>
		public int ServiceType { get; set; }
		/// <summary>
		/// Renewal duration
		/// </summary>
		public int RenewPeriod { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(RenewType);
			writer.WriteInt(ServiceType);
			writer.WriteInt(RenewPeriod);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			RenewType = reader.ReadInt();
			ServiceType = reader.ReadInt();
			RenewPeriod = reader.ReadInt();
		}

    }
}