// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Packaged VIP goods info
    /// </summary>
    public class CSVIPGoodsInfo
    {
		/// <summary>
		/// Goods ID
		/// </summary>
		public uint GoodsID { get; set; }
		/// <summary>
		/// Goods count
		/// </summary>
		public uint GoodsCount { get; set; }
		/// <summary>
		/// Goods version number
		/// </summary>
		public uint GoodsVersion { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteUInt(GoodsID);
			writer.WriteUInt(GoodsCount);
			writer.WriteUInt(GoodsVersion);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			GoodsID = reader.ReadUInt();
			GoodsCount = reader.ReadUInt();
			GoodsVersion = reader.ReadUInt();
		}

    }
}