// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Queue info
    /// </summary>
    public class CSWaitQueueInfo : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_WAITQUEUE_INFO;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Is VIP
		/// </summary>
		public int IsVIP { get; set; }
		/// <summary>
		/// Own queue position
		/// </summary>
		public uint Position { get; set; }
		/// <summary>
		/// Normal queue estimated time
		/// </summary>
		public uint NormalWaitTime { get; set; }
		/// <summary>
		/// VIP queue estimated time
		/// </summary>
		public uint VIPWaitTime { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(IsVIP);
			writer.WriteUInt(Position);
			writer.WriteUInt(NormalWaitTime);
			writer.WriteUInt(VIPWaitTime);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			IsVIP = reader.ReadInt();
			Position = reader.ReadUInt();
			NormalWaitTime = reader.ReadUInt();
			VIPWaitTime = reader.ReadUInt();
		}

    }
}