// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Weapon style activation response
    /// </summary>
    public class CSWeaponStyleActiveRsp : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_WEAPON_STYLE_ACTIVE_RSP;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Return result
		/// </summary>
		public int Ret { get; set; }
		/// <summary>
		/// Weapon type
		/// </summary>
		public int WeaponType { get; set; }
		/// <summary>
		/// Which style to activate
		/// </summary>
		public int Style { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(Ret);
			writer.WriteInt(WeaponType);
			writer.WriteInt(Style);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Ret = reader.ReadInt();
			WeaponType = reader.ReadInt();
			Style = reader.ReadInt();
		}

    }
}