// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Get all friend system info data
    /// </summary>
    public class FriendQueryInfo
    {
		/// <summary>
		/// Friend DBID
		/// </summary>
		public ulong DBID { get; set; }
		/// <summary>
		/// Friend role ID
		/// </summary>
		public int RoleID { get; set; }
		/// <summary>
		/// Friend level
		/// </summary>
		public int Level { get; set; }
		/// <summary>
		/// Friend role LevelID
		/// </summary>
		public uint LevelID { get; set; }
		/// <summary>
		/// Friend currently online
		/// </summary>
		public byte IsOnline { get; set; }
		/// <summary>
		/// Mood
		/// </summary>
		public string Mood { get; set; }
		/// <summary>
		/// Player's current line
		/// </summary>
		public int LineId { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteULong(DBID);
			writer.WriteInt(RoleID);
			writer.WriteInt(Level);
			writer.WriteUInt(LevelID);
			writer.WriteByte(IsOnline);
			if (Mood.Length > (CsprotoConstants.CS_MOOD_LEN - 1))
			{
				throw new InvalidOperationException($"String length of 'Mood' should be of length of {(CsprotoConstants.CS_MOOD_LEN - 1)} but was {Mood.Length}.");
			}

			writer.WriteUTF(Mood);
			writer.WriteInt(LineId);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			DBID = reader.ReadULong();
			RoleID = reader.ReadInt();
			Level = reader.ReadInt();
			LevelID = reader.ReadUInt();
			IsOnline = reader.ReadByte();
			Mood = reader.ReadUTF();
			LineId = reader.ReadInt();
		}

    }
}