// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Friend info data
    /// </summary>
    public class FriendInfoPacket
    {
		public ulong RoleDBID { get; set; }
		/// <summary>
		/// Level
		/// </summary>
		public int Level { get; set; }
		public string RoleName { get; set; }
		/// <summary>
		/// Group ID
		/// </summary>
		public byte GroupID { get; set; }
		/// <summary>
		/// Friendliness
		/// </summary>
		public uint Friendly { get; set; }
		/// <summary>
		/// Farm points
		/// </summary>
		public int FarmPoint { get; set; }
		/// <summary>
		/// Player farm remaining gatherable count
		/// </summary>
		public int FarmCanBeGatheredCount { get; set; }
		/// <summary>
		/// HR level
		/// </summary>
		public int HRLevel { get; set; }
		/// <summary>
		/// SvrId
		/// </summary>
		public uint SvrId { get; set; }
		/// <summary>
		/// AddTime
		/// </summary>
		public int AddTime { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteULong(RoleDBID);
			writer.WriteInt(Level);
			if (RoleName.Length > (CsprotoConstants.CS_MAX_ROLE_NAME - 1))
			{
				throw new InvalidOperationException($"String length of 'RoleName' should be of length of {(CsprotoConstants.CS_MAX_ROLE_NAME - 1)} but was {RoleName.Length}.");
			}

			writer.WriteUTF(RoleName);
			writer.WriteByte(GroupID);
			writer.WriteUInt(Friendly);
			writer.WriteInt(FarmPoint);
			writer.WriteInt(FarmCanBeGatheredCount);
			writer.WriteInt(HRLevel);
			writer.WriteUInt(SvrId);
			writer.WriteInt(AddTime);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			RoleDBID = reader.ReadULong();
			Level = reader.ReadInt();
			RoleName = reader.ReadUTF();
			GroupID = reader.ReadByte();
			Friendly = reader.ReadUInt();
			FarmPoint = reader.ReadInt();
			FarmCanBeGatheredCount = reader.ReadInt();
			HRLevel = reader.ReadInt();
			SvrId = reader.ReadUInt();
			AddTime = reader.ReadInt();
		}

    }
}