// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Player newbie guide book chapter info, consistent with csproto.xml
    /// </summary>
    public class GuideBookChapterInfo
    {
		/// <summary>
		/// Chapter id
		/// </summary>
		public int ChapterId { get; set; }
		/// <summary>
		/// Reward claim count
		/// </summary>
		public int GetRewardCount { get; set; }
		/// <summary>
		/// Has not been opened before
		/// </summary>
		public char IsNotNew { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(ChapterId);
			writer.WriteInt(GetRewardCount);
			writer.WriteChar(IsNotNew);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			ChapterId = reader.ReadInt();
			GetRewardCount = reader.ReadInt();
			IsNotNew = reader.ReadChar();
		}

    }
}