// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    public class GuildWarSimpleInfo
    {
		/// <summary>
		/// Guild ID
		/// </summary>
		public ulong GuildId { get; set; }
		/// <summary>
		/// Player guild name
		/// </summary>
		public string GuildName { get; set; }
		/// <summary>
		/// Sailing count
		/// </summary>
		public byte BoatsCount { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteULong(GuildId);
			if (GuildName.Length != CsprotoConstants.CS_MAX_GUILD_NAME_LEN)
			{
				throw new InvalidOperationException($"Array length of 'GuildName' should be of length of {CsprotoConstants.CS_MAX_GUILD_NAME_LEN} but was {GuildName.Length}.");
			}

			writer.WriteUTF(GuildName);
			writer.WriteByte(BoatsCount);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			GuildId = reader.ReadULong();
			GuildName = reader.ReadUTF();
			BoatsCount = reader.ReadByte();
		}

    }
}