// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Secret research lab lottery box info
    /// </summary>
    public class ItemBoxType
    {
		/// <summary>
		/// Box ID
		/// </summary>
		public int BoxId { get; set; }
		/// <summary>
		/// Reward slot info
		/// </summary>
		public LotteryItemType[] LotteryItemList { get; set; } = Array.Empty<LotteryItemType>();
		/// <summary>
		/// VIP refresh count
		/// </summary>
		public int VipRefrshCount { get; set; }
		/// <summary>
		/// Refresh count
		/// </summary>
		public int RefreshCount { get; set; }
		/// <summary>
		/// Research count
		/// </summary>
		public int ResearchCount { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(BoxId);
			if ((LotteryItemList?.Length ?? 0) != CsprotoConstants.SECRET_RESEARCH_LAB_LOTTERY_ITEM_MAX_LEN)
			{
				throw new InvalidOperationException($"Array length of 'LotteryItemList' should be of length of {CsprotoConstants.SECRET_RESEARCH_LAB_LOTTERY_ITEM_MAX_LEN} but was {(LotteryItemList?.Length ?? 0)}.");
			}

			for (var i = 0; i < CsprotoConstants.SECRET_RESEARCH_LAB_LOTTERY_ITEM_MAX_LEN; i++)
			{
				LotteryItemList[i]?.Serialize(writer);
			}
			writer.WriteInt(VipRefrshCount);
			writer.WriteInt(RefreshCount);
			writer.WriteInt(ResearchCount);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			BoxId = reader.ReadInt();
			// Read array: LotteryItemList
			LotteryItemList = new LotteryItemType[CsprotoConstants.SECRET_RESEARCH_LAB_LOTTERY_ITEM_MAX_LEN];
			for (var i = 0; i < LotteryItemList.Length; i++)
			{
				LotteryItemList[i] = new LotteryItemType();
				LotteryItemList[i].Deserialize(reader);
			}
			VipRefrshCount = reader.ReadInt();
			RefreshCount = reader.ReadInt();
			ResearchCount = reader.ReadInt();
		}

    }
}