// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Track set collection
    /// </summary>
    public class ItemRebuildTracksSet
    {
		/// <summary>
		/// Track
		/// </summary>
		public ItemRebuildTracks[] TracksSet { get; set; } = Array.Empty<ItemRebuildTracks>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			// Write length for array: TracksSet
			var Count = (int)(TracksSet?.Length ?? 0);
			if (Count > CsprotoConstants.CS_ITEM_REBUILD_TRACKS_SET_MAX)
			{
				throw new InvalidOperationException($"Array length of 'TracksSet' exceeds maximum allowed length of {CsprotoConstants.CS_ITEM_REBUILD_TRACKS_SET_MAX} but was {Count}.");
			}

			writer.WriteInt(Count);
			for (var i = 0; i < Count; i++)
			{
				TracksSet[i]?.Serialize(writer);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			// Read length for array: TracksSet
			var Count = reader.ReadInt();
			// Read array: TracksSet
			TracksSet = new ItemRebuildTracks[Math.Min((int)Count, CsprotoConstants.CS_ITEM_REBUILD_TRACKS_SET_MAX)];
			for (var i = 0; i < TracksSet.Length; i++)
			{
				TracksSet[i] = new ItemRebuildTracks();
				TracksSet[i].Deserialize(reader);
			}
		}

    }
}