// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Monster size record info
    /// </summary>
    public class MonsterSizeChange
    {
		/// <summary>
		/// Monster ID
		/// </summary>
		public int MonsterID { get; set; }
		/// <summary>
		/// Size change type
		/// </summary>
		public int ChangeType { get; set; }
		/// <summary>
		/// Old size
		/// </summary>
		public float OldSize { get; set; }
		/// <summary>
		/// New size
		/// </summary>
		public float NewSize { get; set; }
		/// <summary>
		/// Old size type
		/// </summary>
		public int OldType { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(MonsterID);
			writer.WriteInt(ChangeType);
			writer.WriteFloat(OldSize);
			writer.WriteFloat(NewSize);
			writer.WriteInt(OldType);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			MonsterID = reader.ReadInt();
			ChangeType = reader.ReadInt();
			OldSize = reader.ReadFloat();
			NewSize = reader.ReadFloat();
			OldType = reader.ReadInt();
		}

    }
}