// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using Rathalos.Core.Utils.IO;


namespace Rathalos.Core.Protocol.Messages.Csproto
{

    /// <summary>
    /// System notice content
    /// </summary>

    public interface NoticeMsg
    {
        void Serialize(IDataWriter writer);
        void Deserialize(IDataReader reader);
    }
}