// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Cleared instance info
    /// </summary>
    public class PlayerPassLevelInfo
    {
		/// <summary>
		/// Cleared instance ID
		/// </summary>
		public uint LevelID { get; set; }
		/// <summary>
		/// Clear time
		/// </summary>
		public uint PassTime { get; set; }
		/// <summary>
		/// Historical best score
		/// </summary>
		public int BestFinalRank { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteUInt(LevelID);
			writer.WriteUInt(PassTime);
			writer.WriteInt(BestFinalRank);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			LevelID = reader.ReadUInt();
			PassTime = reader.ReadUInt();
			BestFinalRank = reader.ReadInt();
		}

    }
}