// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Rank reward
    /// </summary>
    public class RankReward
    {
		/// <summary>
		/// Player name
		/// </summary>
		public string Name { get; set; }
		/// <summary>
		/// Reward ID
		/// </summary>
		public int Reward { get; set; }
		/// <summary>
		/// 0: Not claimed; 1: Claimed
		/// </summary>
		public byte BFetched { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			if (Name.Length > (CsprotoConstants.CS_MAX_ROLE_NAME - 1))
			{
				throw new InvalidOperationException($"String length of 'Name' should be of length of {(CsprotoConstants.CS_MAX_ROLE_NAME - 1)} but was {Name.Length}.");
			}

			writer.WriteUTF(Name);
			writer.WriteInt(Reward);
			writer.WriteByte(BFetched);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Name = reader.ReadUTF();
			Reward = reader.ReadInt();
			BFetched = reader.ReadByte();
		}

    }
}