// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Red yellow confrontation add secret quest
    /// </summary>
    public class S2CActivityAddSecretQuest : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.S2C_CMD_ACTIVITY_ADDSECRETQUEST;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Camp
		/// </summary>
		public int Camp { get; set; }
		/// <summary>
		/// End time
		/// </summary>
		public uint EndTime { get; set; }
		/// <summary>
		/// Level collection
		/// </summary>
		public int[] Levels { get; set; } = Array.Empty<int>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(Camp);
			writer.WriteUInt(EndTime);
			// Write length for array: Levels
			var Count = (int)(Levels?.Length ?? 0);
			if (Count > CsprotoConstants.CS_MAX_ACTIVITY_SECRET_QUEST_LEVEL_COUNT)
			{
				throw new InvalidOperationException($"Array length of 'Levels' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_ACTIVITY_SECRET_QUEST_LEVEL_COUNT} but was {Count}.");
			}

			writer.WriteInt(Count);
			for (var i = 0; i < Count; i++)
			{
				writer.WriteInt(Levels[i]);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Camp = reader.ReadInt();
			EndTime = reader.ReadUInt();
			// Read length for array: Levels
			var Count = reader.ReadInt();
			// Read array: Levels
			Levels = new int[Math.Min((int)Count, CsprotoConstants.CS_MAX_ACTIVITY_SECRET_QUEST_LEVEL_COUNT)];
			for (var i = 0; i < Levels.Length; i++)
			{
				Levels[i] = reader.ReadInt();
			}
		}

    }
}