// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Wild hunt signup
    /// </summary>
    public class S2CActivityWildHuntApply : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.S2C_CMD_ACTIVITY_WILDHUNTAPPLY;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Phase number
		/// </summary>
		public int Phase { get; set; }
		/// <summary>
		/// Camp
		/// </summary>
		public int Camp { get; set; }
		/// <summary>
		/// Apply method
		/// </summary>
		public int ApplyType { get; set; }
		/// <summary>
		/// Guild
		/// </summary>
		public ulong Guild { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(Phase);
			writer.WriteInt(Camp);
			writer.WriteInt(ApplyType);
			writer.WriteULong(Guild);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Phase = reader.ReadInt();
			Camp = reader.ReadInt();
			ApplyType = reader.ReadInt();
			Guild = reader.ReadULong();
		}

    }
}