// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Return clan member list
    /// </summary>
    public class S2CClanMemberRsp : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.S2C_CMD_CLAN_MEMBER_LIST_RSP;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		public ClanerNameInfo[] ClanerNames { get; set; } = Array.Empty<ClanerNameInfo>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			// Write length for array: ClanerNames
			var Count = (int)(ClanerNames?.Length ?? 0);
			if (Count > CsprotoConstants.CS_MAX_CLAN_MEMBER_LEN)
			{
				throw new InvalidOperationException($"Array length of 'ClanerNames' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_CLAN_MEMBER_LEN} but was {Count}.");
			}

			writer.WriteInt(Count);
			for (var i = 0; i < Count; i++)
			{
				ClanerNames[i]?.Serialize(writer);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			// Read length for array: ClanerNames
			var Count = reader.ReadInt();
			// Read array: ClanerNames
			ClanerNames = new ClanerNameInfo[Math.Min((int)Count, CsprotoConstants.CS_MAX_CLAN_MEMBER_LEN)];
			for (var i = 0; i < ClanerNames.Length; i++)
			{
				ClanerNames[i] = new ClanerNameInfo();
				ClanerNames[i].Deserialize(reader);
			}
		}

    }
}