// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Get guild depot
    /// </summary>
    public class S2CGuildGetDepot : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.S2C_CMD_GUILD_GETDEPOT;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Guild depot
		/// </summary>
		public byte[] Depot { get; set; } = Array.Empty<byte>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			// Write length for array: Depot
			var DepotLen = (int)(Depot?.Length ?? 0);
			if (DepotLen > CsprotoConstants.CS_MAX_GUILD_DEPOT_DATA_LEN)
			{
				throw new InvalidOperationException($"Array length of 'Depot' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_GUILD_DEPOT_DATA_LEN} but was {DepotLen}.");
			}

			writer.WriteInt(DepotLen);
			for (var i = 0; i < DepotLen; i++)
			{
				writer.WriteByte(Depot[i]);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			// Read length for array: Depot
			var DepotLen = reader.ReadInt();
			// Read array: Depot
			Depot = new byte[Math.Min((int)DepotLen, CsprotoConstants.CS_MAX_GUILD_DEPOT_DATA_LEN)];
			for (var i = 0; i < Depot.Length; i++)
			{
				Depot[i] = reader.ReadByte();
			}
		}

    }
}