// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Personal stage reward request response
    /// </summary>
    public class S2CLeagueStepReward : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.S2C_CMD_LEAGUE_STEP_REWARD;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Reward level
		/// </summary>
		public int Level { get; set; }
		/// <summary>
		/// Honor medal weekly limit reached
		/// </summary>
		public byte WeekLimit { get; set; }
		/// <summary>
		/// Honor medal total limit reached
		/// </summary>
		public byte TotalLimit { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(Level);
			writer.WriteByte(WeekLimit);
			writer.WriteByte(TotalLimit);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Level = reader.ReadInt();
			WeekLimit = reader.ReadByte();
			TotalLimit = reader.ReadByte();
		}

    }
}