// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Season instance list response
    /// </summary>
    public class S2CLeagueLevelRsp : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.S2C_CMD_LEAGUE_LEVEL_RSP;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Season
		/// </summary>
		public LeagueOpenInfo[] LeagueOpen { get; set; } = Array.Empty<LeagueOpenInfo>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			// Write length for array: LeagueOpen
			var Count = (int)(LeagueOpen?.Length ?? 0);
			if (Count > CsprotoConstants.CS_MAX_LEAGUE_INFOS)
			{
				throw new InvalidOperationException($"Array length of 'LeagueOpen' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_LEAGUE_INFOS} but was {Count}.");
			}

			writer.WriteInt(Count);
			for (var i = 0; i < Count; i++)
			{
				LeagueOpen[i]?.Serialize(writer);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			// Read length for array: LeagueOpen
			var Count = reader.ReadInt();
			// Read array: LeagueOpen
			LeagueOpen = new LeagueOpenInfo[Math.Min((int)Count, CsprotoConstants.CS_MAX_LEAGUE_INFOS)];
			for (var i = 0; i < LeagueOpen.Length; i++)
			{
				LeagueOpen[i] = new LeagueOpenInfo();
				LeagueOpen[i].Deserialize(reader);
			}
		}

    }
}