// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Pet random info
    /// </summary>
    public class S2CPetRng : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.S2C_CMD_PET_RNG;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Pet attributes
		/// </summary>
		public byte[] Attrs { get; set; } = Array.Empty<byte>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			// Write length for array: Attrs
			var Size = (int)(Attrs?.Length ?? 0);
			if (Size > CsprotoConstants.CS_MAX_PET_RNG_ATTRS_LEN)
			{
				throw new InvalidOperationException($"Array length of 'Attrs' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_PET_RNG_ATTRS_LEN} but was {Size}.");
			}

			writer.WriteInt(Size);
			for (var i = 0; i < Size; i++)
			{
				writer.WriteByte(Attrs[i]);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			// Read length for array: Attrs
			var Size = reader.ReadInt();
			// Read array: Attrs
			Attrs = new byte[Math.Min((int)Size, CsprotoConstants.CS_MAX_PET_RNG_ATTRS_LEN)];
			for (var i = 0; i < Attrs.Length; i++)
			{
				Attrs[i] = reader.ReadByte();
			}
		}

    }
}