// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    public class S2CRankGetUserData : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.S2C_CMD_RANK_GETUSERDATA;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Player attached data
		/// </summary>
		public CSRankUserData[] UserDatas { get; set; } = Array.Empty<CSRankUserData>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			// Write length for array: UserDatas
			var UserCount = (int)(UserDatas?.Length ?? 0);
			if (UserCount > CsprotoConstants.CS_XRANK_BATCHGET_MAX_USERS)
			{
				throw new InvalidOperationException($"Array length of 'UserDatas' exceeds maximum allowed length of {CsprotoConstants.CS_XRANK_BATCHGET_MAX_USERS} but was {UserCount}.");
			}

			writer.WriteInt(UserCount);
			for (var i = 0; i < UserCount; i++)
			{
				UserDatas[i]?.Serialize(writer);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			// Read length for array: UserDatas
			var UserCount = reader.ReadInt();
			// Read array: UserDatas
			UserDatas = new CSRankUserData[Math.Min((int)UserCount, CsprotoConstants.CS_XRANK_BATCHGET_MAX_USERS)];
			for (var i = 0; i < UserDatas.Length; i++)
			{
				UserDatas[i] = new CSRankUserData();
				UserDatas[i].Deserialize(reader);
			}
		}

    }
}