// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Silver storage box
    /// </summary>
    public class S2CSilverStorageBoxInfo
    {
		/// <summary>
		/// Current silver amount in storage box
		/// </summary>
		public int SilverCount { get; set; }
		/// <summary>
		/// Free silver fetch times this week
		/// </summary>
		public int WeekFreeFetchTimes { get; set; }
		/// <summary>
		/// Paid silver fetch times this week
		/// </summary>
		public int WeekBuyFetchTimes { get; set; }
		/// <summary>
		/// Cumulative expansion times
		/// </summary>
		public int EnlargeTimes { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(SilverCount);
			writer.WriteInt(WeekFreeFetchTimes);
			writer.WriteInt(WeekBuyFetchTimes);
			writer.WriteInt(EnlargeTimes);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			SilverCount = reader.ReadInt();
			WeekFreeFetchTimes = reader.ReadInt();
			WeekBuyFetchTimes = reader.ReadInt();
			EnlargeTimes = reader.ReadInt();
		}

    }
}