// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Season details
    /// </summary>
    public class S2CTournamentsGetDetail : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.S2C_CMD_TOURNAMENTS_GETDETAIL;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Season
		/// </summary>
		public int Season { get; set; }
		/// <summary>
		/// Round
		/// </summary>
		public int Round { get; set; }
		/// <summary>
		/// Season state
		/// </summary>
		public int State { get; set; }
		/// <summary>
		/// Level ID
		/// </summary>
		public int[] Levels { get; set; } = Array.Empty<int>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(Season);
			writer.WriteInt(Round);
			writer.WriteInt(State);
			// Write length for array: Levels
			var Count = (int)(Levels?.Length ?? 0);
			if (Count > CsprotoConstants.CS_TOURNAMENTS_LEVEVL_MAX_NUM)
			{
				throw new InvalidOperationException($"Array length of 'Levels' exceeds maximum allowed length of {CsprotoConstants.CS_TOURNAMENTS_LEVEVL_MAX_NUM} but was {Count}.");
			}

			writer.WriteInt(Count);
			for (var i = 0; i < Count; i++)
			{
				writer.WriteInt(Levels[i]);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Season = reader.ReadInt();
			Round = reader.ReadInt();
			State = reader.ReadInt();
			// Read length for array: Levels
			var Count = reader.ReadInt();
			// Read array: Levels
			Levels = new int[Math.Min((int)Count, CsprotoConstants.CS_TOURNAMENTS_LEVEVL_MAX_NUM)];
			for (var i = 0; i < Levels.Length; i++)
			{
				Levels[i] = reader.ReadInt();
			}
		}

    }
}