// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// XRank rank data response
    /// </summary>
    public class S2CXRankGetRank : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.S2C_CMD_XRANK_GETRANK;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Result, 0 is normal
		/// </summary>
		public int Result { get; set; }
		/// <summary>
		/// Region, corresponds to xrank service applied world id
		/// </summary>
		public int Zone { get; set; }
		/// <summary>
		/// Player's attached attribute, such as city. XRank will create multiple ranks based on this
		/// </summary>
		public int ScoreType { get; set; }
		/// <summary>
		/// Starting rank in topN rank
		/// </summary>
		public uint Offset { get; set; }
		/// <summary>
		/// Total players in topN rank
		/// </summary>
		public uint Total { get; set; }
		/// <summary>
		/// TopN rank limit, 0 means don't fetch topN, -1 fetches to the last
		/// </summary>
		public CSXRankUserInfo[] TopUsers { get; set; } = Array.Empty<CSXRankUserInfo>();
		/// <summary>
		/// Player's own rank info
		/// </summary>
		public CSXRankUserInfo SelfBlurRank { get; set; }
		/// <summary>
		/// Fuzzy rank player list
		/// </summary>
		public CSXRankUserInfo[] BlurUsers { get; set; } = Array.Empty<CSXRankUserInfo>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(Result);
			writer.WriteInt(Zone);
			writer.WriteInt(ScoreType);
			writer.WriteUInt(Offset);
			writer.WriteUInt(Total);
			// Write length for array: TopUsers
			var TopCount = (int)(TopUsers?.Length ?? 0);
			if (TopCount > CsprotoConstants.CS_XRANK_TOPN_USERS)
			{
				throw new InvalidOperationException($"Array length of 'TopUsers' exceeds maximum allowed length of {CsprotoConstants.CS_XRANK_TOPN_USERS} but was {TopCount}.");
			}

			writer.WriteInt(TopCount);
			for (var i = 0; i < TopCount; i++)
			{
				TopUsers[i]?.Serialize(writer);
			}
			SelfBlurRank?.Serialize(writer);
			// Write length for array: BlurUsers
			var BlurCount = (int)(BlurUsers?.Length ?? 0);
			if (BlurCount > CsprotoConstants.CS_XRANK_BLUR_USERS)
			{
				throw new InvalidOperationException($"Array length of 'BlurUsers' exceeds maximum allowed length of {CsprotoConstants.CS_XRANK_BLUR_USERS} but was {BlurCount}.");
			}

			writer.WriteInt(BlurCount);
			for (var i = 0; i < BlurCount; i++)
			{
				BlurUsers[i]?.Serialize(writer);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Result = reader.ReadInt();
			Zone = reader.ReadInt();
			ScoreType = reader.ReadInt();
			Offset = reader.ReadUInt();
			Total = reader.ReadUInt();
			// Read length for array: TopUsers
			var TopCount = reader.ReadInt();
			// Read array: TopUsers
			TopUsers = new CSXRankUserInfo[Math.Min((int)TopCount, CsprotoConstants.CS_XRANK_TOPN_USERS)];
			for (var i = 0; i < TopUsers.Length; i++)
			{
				TopUsers[i] = new CSXRankUserInfo();
				TopUsers[i].Deserialize(reader);
			}
			SelfBlurRank = new CSXRankUserInfo();
			SelfBlurRank.Deserialize(reader);
			// Read length for array: BlurUsers
			var BlurCount = reader.ReadInt();
			// Read array: BlurUsers
			BlurUsers = new CSXRankUserInfo[Math.Min((int)BlurCount, CsprotoConstants.CS_XRANK_BLUR_USERS)];
			for (var i = 0; i < BlurUsers.Length; i++)
			{
				BlurUsers[i] = new CSXRankUserInfo();
				BlurUsers[i].Deserialize(reader);
			}
		}

    }
}