// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Demon trial levels
    /// </summary>
    public class SCDemonTrialGetLevelsRsp : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.S2C_CMD_DEMON_TRIAL_GET_LEVELS_RSP;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Error code
		/// </summary>
		public int ErrCode { get; set; }
		/// <summary>
		/// Level id
		/// </summary>
		public int[] DemonTrialLevels { get; set; } = Array.Empty<int>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(ErrCode);
			// Write length for array: DemonTrialLevels
			var DemonTrialLevelsCount = (int)(DemonTrialLevels?.Length ?? 0);
			if (DemonTrialLevelsCount > CsprotoConstants.MAX_DEMON_TRIAL_LEN)
			{
				throw new InvalidOperationException($"Array length of 'DemonTrialLevels' exceeds maximum allowed length of {CsprotoConstants.MAX_DEMON_TRIAL_LEN} but was {DemonTrialLevelsCount}.");
			}

			writer.WriteInt(DemonTrialLevelsCount);
			for (var i = 0; i < DemonTrialLevelsCount; i++)
			{
				writer.WriteInt(DemonTrialLevels[i]);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			ErrCode = reader.ReadInt();
			// Read length for array: DemonTrialLevels
			var DemonTrialLevelsCount = reader.ReadInt();
			// Read array: DemonTrialLevels
			DemonTrialLevels = new int[Math.Min((int)DemonTrialLevelsCount, CsprotoConstants.MAX_DEMON_TRIAL_LEN)];
			for (var i = 0; i < DemonTrialLevels.Length; i++)
			{
				DemonTrialLevels[i] = reader.ReadInt();
			}
		}

    }
}