// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Get demon trial minimum clear time
    /// </summary>
    public class SCDemonTrialGetLevelPassTimeRsp : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.S2C_CMD_DEMON_TRIAL_GET_LEVELS_PASS_TIME_RSP;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// Error code
		/// </summary>
		public int ErrCode { get; set; }
		/// <summary>
		/// Level clear info
		/// </summary>
		public CSLevelPassMinTime[] PassLevelInfo { get; set; } = Array.Empty<CSLevelPassMinTime>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(ErrCode);
			// Write length for array: PassLevelInfo
			var LevelCount = (int)(PassLevelInfo?.Length ?? 0);
			if (LevelCount > CsprotoConstants.CS_MAX_RECORD_PASS_LEVEL_MIN_TIME_COUNT)
			{
				throw new InvalidOperationException($"Array length of 'PassLevelInfo' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_RECORD_PASS_LEVEL_MIN_TIME_COUNT} but was {LevelCount}.");
			}

			writer.WriteInt(LevelCount);
			for (var i = 0; i < LevelCount; i++)
			{
				PassLevelInfo[i]?.Serialize(writer);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			ErrCode = reader.ReadInt();
			// Read length for array: PassLevelInfo
			var LevelCount = reader.ReadInt();
			// Read array: PassLevelInfo
			PassLevelInfo = new CSLevelPassMinTime[Math.Min((int)LevelCount, CsprotoConstants.CS_MAX_RECORD_PASS_LEVEL_MIN_TIME_COUNT)];
			for (var i = 0; i < PassLevelInfo.Length; i++)
			{
				PassLevelInfo[i] = new CSLevelPassMinTime();
				PassLevelInfo[i].Deserialize(reader);
			}
		}

    }
}