// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    public class SCGuildWarAllInformationNtf : CSPkgBody
    {
		public const CS_CMD_ID ProtocolIdConst = CS_CMD_ID.CS_CMD_GUILD_WAR_ALL_INFORMATION_NTF;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Reconnaissance info
		/// </summary>
		public SCGuildWarInformationNtf[] Informations { get; set; } = Array.Empty<SCGuildWarInformationNtf>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			// Write length for array: Informations
			var Count = (int)(Informations?.Length ?? 0);
			if (Count > CsprotoConstants.CS_MAX_OTHER_GUILD_INFO_LEN)
			{
				throw new InvalidOperationException($"Array length of 'Informations' exceeds maximum allowed length of {CsprotoConstants.CS_MAX_OTHER_GUILD_INFO_LEN} but was {Count}.");
			}

			writer.WriteInt(Count);
			for (var i = 0; i < Count; i++)
			{
				Informations[i]?.Serialize(writer);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			// Read length for array: Informations
			var Count = reader.ReadInt();
			// Read array: Informations
			Informations = new SCGuildWarInformationNtf[Math.Min((int)Count, CsprotoConstants.CS_MAX_OTHER_GUILD_INFO_LEN)];
			for (var i = 0; i < Informations.Length; i++)
			{
				Informations[i] = new SCGuildWarInformationNtf();
				Informations[i].Deserialize(reader);
			}
		}

    }
}