// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    public class ScriptActivityDataHubHidden : ScriptActivityDataUnion
    {
		public const EScriptActivityDataType ProtocolIdConst = EScriptActivityDataType.KScriptActivityDataType_HubHidden;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Unique data ID, non-zero
		/// </summary>
		public byte Hub { get; set; }
		/// <summary>
		/// Page list
		/// </summary>
		public string Pages { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteByte(Hub);
			if (Pages.Length > (CsprotoConstants.CS_SACTIVITY_LEVEL_LENGTH - 1))
			{
				throw new InvalidOperationException($"String length of 'Pages' should be of length of {(CsprotoConstants.CS_SACTIVITY_LEVEL_LENGTH - 1)} but was {Pages.Length}.");
			}

			writer.WriteUTF(Pages);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Hub = reader.ReadByte();
			Pages = reader.ReadUTF();
		}

    }
}