// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// Script activity data structure
    /// </summary>
    public class ScriptActivityDataEntry
    {
		/// <summary>
		/// Unique data ID, non-zero
		/// </summary>
		public byte ID { get; set; }
		/// <summary>
		/// Type @EScriptActivityDataType
		/// </summary>
		public EScriptActivityDataType Type { get; set; }
		/// <summary>
		/// State @see EScriptActivityDataState
		/// </summary>
		public byte State { get; set; }
		/// <summary>
		/// Variable value
		/// </summary>
		public ScriptActivityDataUnion Data { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteByte(ID);
			writer.WriteByte((byte)Type);
			writer.WriteByte(State);
			// Selected by: Type
			Data?.Serialize(writer);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			ID = reader.ReadByte();
			Type = (EScriptActivityDataType)reader.ReadByte();
			State = reader.ReadByte();
			// Selected by: Type
			Data = ProtocolTypeManager.Get<ScriptActivityDataUnion>(Type);
			Data.Deserialize(reader);
		}

    }
}