// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    public class ScriptActivityDataButtonEnterLevel : ScriptActivityDataUnion
    {
		public const EScriptActivityDataType ProtocolIdConst = EScriptActivityDataType.KScriptActivityDataType_ButtonEnterLevel;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// Button text
		/// </summary>
		public string Label { get; set; }
		/// <summary>
		/// Level ID
		/// </summary>
		public uint LevelID { get; set; }
		/// <summary>
		/// Enter mode
		/// </summary>
		public byte EnterMode { get; set; }
		/// <summary>
		/// Counter ID
		/// </summary>
		public byte DataID { get; set; }
		/// <summary>
		/// Condition
		/// </summary>
		public string Condition { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			if (Label.Length > (CsprotoConstants.CS_SACTIVITY_BUTTON_LABEL_LENGTH - 1))
			{
				throw new InvalidOperationException($"String length of 'Label' should be of length of {(CsprotoConstants.CS_SACTIVITY_BUTTON_LABEL_LENGTH - 1)} but was {Label.Length}.");
			}

			writer.WriteUTF(Label);
			writer.WriteUInt(LevelID);
			writer.WriteByte(EnterMode);
			writer.WriteByte(DataID);
			if (Condition.Length > (CsprotoConstants.CS_SACTIVITY_PARAM_LENGTH - 1))
			{
				throw new InvalidOperationException($"String length of 'Condition' should be of length of {(CsprotoConstants.CS_SACTIVITY_PARAM_LENGTH - 1)} but was {Condition.Length}.");
			}

			writer.WriteUTF(Condition);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Label = reader.ReadUTF();
			LevelID = reader.ReadUInt();
			EnterMode = reader.ReadByte();
			DataID = reader.ReadByte();
			Condition = reader.ReadUTF();
		}

    }
}