// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    public class ScriptActivitySimple
    {
		public uint ID { get; set; }
		public byte State { get; set; }
		public byte Phase { get; set; }
		/// <summary>
		/// Attached data states @see EScriptActivityDataState
		/// </summary>
		public byte[] DataStates { get; set; } = Array.Empty<byte>();
		public int[] Vars { get; set; } = Array.Empty<int>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteUInt(ID);
			writer.WriteByte(State);
			writer.WriteByte(Phase);
			// Write length for array: DataStates
			var DataCount = (byte)(DataStates?.Length ?? 0);
			if (DataCount > CsprotoConstants.CS_SACTIVITY_MAX_DATA_COUNT)
			{
				throw new InvalidOperationException($"Array length of 'DataStates' exceeds maximum allowed length of {CsprotoConstants.CS_SACTIVITY_MAX_DATA_COUNT} but was {DataCount}.");
			}

			writer.WriteByte(DataCount);
			for (var i = 0; i < DataCount; i++)
			{
				writer.WriteByte(DataStates[i]);
			}
			if ((Vars?.Length ?? 0) != CsprotoConstants.CS_MAX_SCRIPTACTIVITY_DATA_VARS)
			{
				throw new InvalidOperationException($"Array length of 'Vars' should be of length of {CsprotoConstants.CS_MAX_SCRIPTACTIVITY_DATA_VARS} but was {(Vars?.Length ?? 0)}.");
			}

			for (var i = 0; i < CsprotoConstants.CS_MAX_SCRIPTACTIVITY_DATA_VARS; i++)
			{
				writer.WriteInt(Vars[i]);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			ID = reader.ReadUInt();
			State = reader.ReadByte();
			Phase = reader.ReadByte();
			// Read length for array: DataStates
			var DataCount = reader.ReadByte();
			// Read array: DataStates
			DataStates = new byte[Math.Min((int)DataCount, CsprotoConstants.CS_SACTIVITY_MAX_DATA_COUNT)];
			for (var i = 0; i < DataStates.Length; i++)
			{
				DataStates[i] = reader.ReadByte();
			}
			// Read array: Vars
			Vars = new int[CsprotoConstants.CS_MAX_SCRIPTACTIVITY_DATA_VARS];
			for (var i = 0; i < Vars.Length; i++)
			{
				Vars[i] = reader.ReadInt();
			}
		}

    }
}