// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    /// <summary>
    /// String
    /// </summary>
    public class StringCSAttrValue : CSAttrValue
    {
		public const CS_PROP_SYNC_TYPE ProtocolIdConst = CS_PROP_SYNC_TYPE.CS_PROP_SYNC_STRING;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public int ProtocolId => (int)ProtocolIdConst;
		/// <summary>
		/// String
		/// </summary>
		public string Value { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			if (Value.Length > (CsprotoConstants.CS_MAX_PROP_SYNC_STRING_VALUE_LEN - 1))
			{
				throw new InvalidOperationException($"String length of 'Value' should be of length of {(CsprotoConstants.CS_MAX_PROP_SYNC_STRING_VALUE_LEN - 1)} but was {Value.Length}.");
			}

			writer.WriteUTF(Value);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Value = reader.ReadUTF();
		}

    }
}