// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Csproto
{
    public class StringCSMsgParamValue : CSMsgParamValue
    {
		public string Value { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			if (Value.Length != CsprotoConstants.CS_MSG_PARAM_VALUE_STRING_MAX)
			{
				throw new InvalidOperationException($"Array length of 'Value' should be of length of {CsprotoConstants.CS_MSG_PARAM_VALUE_STRING_MAX} but was {Value.Length}.");
			}

			writer.WriteUTF(Value);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Value = reader.ReadUTF();
		}

    }
}