// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten

namespace Rathalos.Core.Protocol.Messages.Csproto
{

    public enum CS_ATTR_DATA_TYPE
    {
		CS_ATTR_DATA_BASE = 1,
		CS_ATTR_DATA_BONUS = 2
    }
}