// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten

namespace Rathalos.Core.Protocol.Messages.Csproto
{

    /// <summary>
    /// Instance type
    /// </summary>

    public enum CS_BATTLE_RULES_TYPE
    {
		/// <summary>
		/// default
		/// </summary>
		BATTLE_RULES_DEFAULT_INFO = 0,
		/// <summary>
		/// Indirect PVP
		/// </summary>
		BATTLE_RULES_PVP_INFO = 1
    }
}