// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten

namespace Rathalos.Core.Protocol.Messages.Csproto
{

    /// <summary>
    /// Client log reason
    /// </summary>

    public enum CS_CLIENTLOG_REASON
    {
		/// <summary>
		/// Initial timeout
		/// </summary>
		CS_PLAYINIT_INFO = 1,
		/// <summary>
		/// Server response
		/// </summary>
		CS_SVRTEST_RSP = 2,
		/// <summary>
		/// Region switch request
		/// </summary>
		CS_REGION_JUMP_REQ = 3,
		/// <summary>
		/// Newbie level debug log
		/// </summary>
		CS_NEWPLAYER_LEVEL = 4,
		/// <summary>
		/// Equipment plan preview
		/// </summary>
		CS_EQUIPPLAN_VIEW = 5,
		/// <summary>
		/// C1 state machine sync
		/// </summary>
		CS_FIFO_SYNC_C1 = 6,
		/// <summary>
		/// C2 state machine sync
		/// </summary>
		CS_FIFO_SYNC_C2 = 7,
		/// <summary>
		/// New player selection
		/// </summary>
		CS_ISNEW_PLAYER = 8,
		/// <summary>
		/// Role state machine reset
		/// </summary>
		CS_PLAYER_STATE_RESET = 9,
		/// <summary>
		/// Non-input state reset
		/// </summary>
		CS_PLAYER_STATE_UNINPUT_STATE_RESET = 10,
		/// <summary>
		/// Player chooses to continue storyline
		/// </summary>
		CS_PLAYER_SELECT_USE_STORYLINE = 11,
		/// <summary>
		/// Player chooses to open hunting board
		/// </summary>
		CS_PLAYER_SELECT_USE_TASKBOARD = 12
    }
}