// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten

namespace Rathalos.Core.Protocol.Messages.Csproto
{

    /// <summary>
    /// General data query type
    /// </summary>

    public enum CS_QUERY_TYPE
    {
		/// <summary>
		/// Query action points
		/// </summary>
		CS_QUERY_TYPE_ACTION_POINT = 0
    }
}