// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten

namespace Rathalos.Core.Protocol.Messages.Csproto
{

    public enum CS_SCENE_OBJECT_ACTION_TYPE
    {
		/// <summary>
		/// Play effect
		/// </summary>
		CS_ACTION_TYPE_PLAY_EFFECT = 0,
		/// <summary>
		/// Play animation
		/// </summary>
		CS_ACTION_TYPE_PLAY_ANIMATION = 1,
		/// <summary>
		/// State machine switch
		/// </summary>
		CS_ACTION_TYPE_GOTOSTATE = 2,
		/// <summary>
		/// Move to target point
		/// </summary>
		CS_ACTION_TYPE_GOTO_TARGETPOS = 3,
		/// <summary>
		/// Rotate around axis by angle
		/// </summary>
		CS_ACTION_TYPE_ROTATEAXIS = 4,
		/// <summary>
		/// Teleport to target point
		/// </summary>
		CS_ACTION_TYPE_TELEPORT = 5,
		/// <summary>
		/// Basic action, such as hide, enable, etc.
		/// </summary>
		CS_ACTION_TYPE_SIMPLE = 6,
		/// <summary>
		/// Physics collision, open, close, etc.
		/// </summary>
		CS_ACTION_TYPE_PYSICS_COLLISION = 7
    }
}