// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten

namespace Rathalos.Core.Protocol.Messages.Csproto
{

    /// <summary>
    /// Accessory type
    /// </summary>

    public enum EMailAccessoryType
    {
		/// <summary>
		/// Invalid
		/// </summary>
		EMailAccessoryType_None = 0,
		/// <summary>
		/// Gold
		/// </summary>
		EMailAccessoryType_Gold = 1,
		/// <summary>
		/// Bound points
		/// </summary>
		EMailAccessoryType_BindCredit = 2,
		/// <summary>
		/// Item
		/// </summary>
		EMailAccessoryType_Item = 3,
		/// <summary>
		/// Bound gold
		/// </summary>
		EMailAccessoryType_BindGold = 4
    }
}