// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten

namespace Rathalos.Core.Protocol.Messages.Csproto
{

    /// <summary>
    /// Script activity data type
    /// </summary>

    public enum EScriptActivityDataType
    {
		/// <summary>
		/// Invalid
		/// </summary>
		KScriptActivityDataType_NotAvalid = 0,
		/// <summary>
		/// Carousel
		/// </summary>
		KScriptActivityDataType_Marqueen = 16,
		/// <summary>
		/// Execute script
		/// </summary>
		KScriptActivityDataType_ButtonScript = 32,
		/// <summary>
		/// Recharge
		/// </summary>
		KScriptActivityDataType_ButtonCharge = 33,
		/// <summary>
		/// Embedded page
		/// </summary>
		KScriptActivityDataType_ButtonInternalWeb = 34,
		/// <summary>
		/// External page
		/// </summary>
		KScriptActivityDataType_ButtonExternalWeb = 35,
		/// <summary>
		/// Accept task
		/// </summary>
		KScriptActivityDataType_ButtonAcceptTask = 36,
		/// <summary>
		/// Enter level
		/// </summary>
		KScriptActivityDataType_ButtonEnterLevel = 37,
		/// <summary>
		/// General item
		/// </summary>
		KScriptActivityDataType_Item = 48,
		/// <summary>
		/// Parameter set
		/// </summary>
		KScriptActivityDataType_Param = 64,
		/// <summary>
		/// Level hidden
		/// </summary>
		KScriptActivityDataType_LevelHidden = 65,
		/// <summary>
		/// Hub hidden
		/// </summary>
		KScriptActivityDataType_HubHidden = 66,
		/// <summary>
		/// Level control
		/// </summary>
		KScriptActivityDataType_LevelControl = 67,
		/// <summary>
		/// Execute script - button independent
		/// </summary>
		KScriptActivityDataType_Script = 68,
		/// <summary>
		/// Execute script - supports client reporting two int values
		/// </summary>
		KScriptActivityDataType_ScriptAttachParam = 69,
		/// <summary>
		/// Hunt
		/// </summary>
		KScriptActivityDataType_Hunt = 70
    }
}