// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten

namespace Rathalos.Core.Protocol.Messages.Csproto
{

    /// <summary>
    /// Player interact type
    /// </summary>

    public enum INTERACT_REQUEST_TYPE
    {
		/// <summary>
		/// Interact begin
		/// </summary>
		INTERACT_REQUEST_TYPE_BEGIN = 1,
		/// <summary>
		/// Interact end
		/// </summary>
		INTERACT_REQUEST_TYPE_END = 2
    }
}