// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten

namespace Rathalos.Core.Protocol.Messages.Csproto
{

    /// <summary>
    /// TCONND and SVR message codes
    /// </summary>

    public enum ROMTE_DATA_TYPE
    {
		/// <summary>
		/// Item load data
		/// </summary>
		ITEMMGR_DATA_TYPE = 1,
		/// <summary>
		/// Level data type
		/// </summary>
		LEVELINFO_DATA_TYPE = 2,
		/// <summary>
		/// Hunter star data type
		/// </summary>
		HUNTERSTAR_DATA_TYPE = 3,
		/// <summary>
		/// Task data type
		/// </summary>
		TASKSYS_DATA_TYPE = 4,
		/// <summary>
		/// Normal limit data
		/// </summary>
		NORMAL_LIMIT_DATATYPE = 5,
		/// <summary>
		/// Supply plan data
		/// </summary>
		SUPPLY_PLAN_DATA_TYPE = 6
    }
}