// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten

namespace Rathalos.Core.Protocol.Messages.Csproto
{

    public enum TeamInviteConfirmRet
    {
		/// <summary>
		/// Team OK
		/// </summary>
		TeamInviteConfirmRet_Ok = 0,
		/// <summary>
		/// Team no longer exists
		/// </summary>
		TeamInviteConfirmRet_TeamNotExist = 1,
		/// <summary>
		/// Team not in safe area
		/// </summary>
		TeamInviteConfirmRet_TeamNotInSafeArea = 2,
		/// <summary>
		/// Team started level selection
		/// </summary>
		TeamInviteConfirmRet_TeamBeginBattle = 3,
		/// <summary>
		/// Team already full
		/// </summary>
		TeamInviteConfirmRet_TeamFull = 4,
		/// <summary>
		/// Self already has team
		/// </summary>
		TeamInviteConfirmRet_HasTeam = 5,
		/// <summary>
		/// Target started level selection
		/// </summary>
		TeamInviteConfirmRet_BeginBattle = 6
    }
}