


// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;


namespace Rathalos.Core.Protocol.Messages
{

    /// <summary>
    /// 客户端真实地址信息
    /// </summary>

    public class TPDUExtClientAddr : TPDUExt
    {

		public const TPDU_CMD ProtocolIdConst = TPDU_CMD.TPDU_CMD_CLIENT_ADDR;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;


		/// <summary>
		/// Uin
		/// </summary>
		public uint Uin { get; set; }


		/// <summary>
		/// IP地址
		/// </summary>
		public uint IP { get; set; }


		/// <summary>
		/// 端口
		/// </summary>
		public ushort Port { get; set; }


		/// <summary>
		/// 附加信息
		/// </summary>
		public char[] ExtInfo { get; set; } = Array.Empty<char>();


		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteUInt(Uin);
			writer.WriteUInt(IP);
			writer.WriteUShort(Port);
			// Write array: ExtInfo
			var ExtInfoCount = Math.Min(ExtInfo?.Length ?? 0, 128);
			for (var i = 0; i < ExtInfoCount; i++)
			{
				writer.WriteChar(ExtInfo[i]);
			}
		}


		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Uin = reader.ReadUInt();
			IP = reader.ReadUInt();
			Port = reader.ReadUShort();
			// Read array: ExtInfo
			ExtInfo = new char[128];
			for (var i = 0; i < ExtInfo.Length; i++)
			{
				ExtInfo[i] = reader.ReadChar();
			}
		}

    }
}