



// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using Rathalos.Core.Utils.IO;


namespace Rathalos.Core.Protocol.Messages
{

    /// <summary>
    /// Packet header extension information
    /// </summary>

    public interface TPDUExt
    {
        void Serialize(IDataWriter writer);
        void Deserialize(IDataReader reader);
    }
}