


// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten


using System;

using System.Collections.Generic;

using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages
{

    public class TPDUExtSyn : TPDUExt
    {

		public const TPDU_CMD ProtocolIdConst = TPDU_CMD.TPDU_CMD_SYN;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;


		/// <summary>
		/// 连接握手信息长度(密文)
		/// </summary>
		public byte Len { get; set; }


		public sbyte[] EncryptSynInfo { get; set; } = Array.Empty<sbyte>();


		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteByte(Len);
			// Write array: EncryptSynInfo
			var EncryptSynInfoCount = Math.Min(EncryptSynInfo?.Length ?? 0, TPDU_MAX_ENCRYPTSYN_LEN);
			for (var i = 0; i < EncryptSynInfoCount; i++)
			{
				writer.WriteSByte(EncryptSynInfo[i]);
			}
		}


		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Len = reader.ReadByte();
			// Read array: EncryptSynInfo
			EncryptSynInfo = new sbyte[Math.Min((int)Len, TPDU_MAX_ENCRYPTSYN_LEN)];
			for (var i = 0; i < EncryptSynInfo.Length; i++)
			{
				EncryptSynInfo[i] = reader.ReadSByte();
			}
		}

    }
}