// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages
{
    /// <summary>
    /// Base packet header before version 14
    /// </summary>
    public class TPDUBase_Old
    {
		/// <summary>
		/// Magic number
		/// </summary>
		public byte Magic { get; set; }
		/// <summary>
		/// Protocol version, refer to TPDU_VERSION
		/// </summary>
		public byte Version { get; set; }
		/// <summary>
		/// Packet type
		/// </summary>
		public byte Cmd { get; set; }
		/// <summary>
		/// Header length
		/// </summary>
		public byte HeadLen { get; set; }
		/// <summary>
		/// Valid for upstream packets, header additional info length, encrypted with body (version:11)
		/// </summary>
		public byte EncHeadLen { get; set; }
		/// <summary>
		/// Body length
		/// </summary>
		public int BodyLen { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteByte(Magic);
			writer.WriteByte(Version);
			writer.WriteByte(Cmd);
			writer.WriteByte(HeadLen);
			writer.WriteByte(EncHeadLen);
			writer.WriteInt(BodyLen);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Magic = reader.ReadByte();
			Version = reader.ReadByte();
			Cmd = reader.ReadByte();
			HeadLen = reader.ReadByte();
			EncHeadLen = reader.ReadByte();
			BodyLen = reader.ReadInt();
		}

    }
}