// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Tqqapi
{
    /// <summary>
    /// Packet header before version 14
    /// </summary>
    public class TPDUHead_Old
    {
		/// <summary>
		/// Base information
		/// </summary>
		public TPDUBase_Old Base { get; set; }
		/// <summary>
		/// Extension information
		/// </summary>
		public TPDUExt Ext { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			Base?.Serialize(writer);
			// Selected by: Base.Cmd
			Ext?.Serialize(writer);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Base = new TPDUBase_Old();
			Base.Deserialize(reader);
			// Selected by: Base.Cmd
			Ext = ProtocolTypeManager.Get<TPDUExt>(Base.Cmd);
			Ext.Deserialize(reader);
		}

    }
}