// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Tqqapi
{
    /// <summary>
    /// CS communication packet = Plaintext: Header (base info + extension info) + Ciphertext: Body (additional header info + application packet)
    /// </summary>
    public class TPDUFrame
    {
		public TPDUHead Head { get; set; }
		public byte[] Body { get; set; } = Array.Empty<byte>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			Head?.Serialize(writer);
			for (var i = 0; i < Head.Base.BodyLen; i++)
			{
				writer.WriteByte(Body[i]);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Head = new TPDUHead();
			Head.Deserialize(reader);
			// Read array: Body
			Body = new byte[Head.Base.BodyLen];
			for (var i = 0; i < Body.Length; i++)
			{
				Body[i] = reader.ReadByte();
			}
		}

    }
}