// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages
{
    /// <summary>
    /// 连接握手信息
    /// </summary>
    public class TPDUSynInfo
    {
		public char[] Randstr { get; set; } = Array.Empty<char>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			var RandstrCount = Math.Min((Randstr?.Length ?? 0), MetaLibConstants.TQQ_IDENT_LEN);
			if (RandstrCount != MetaLibConstants.TQQ_IDENT_LEN)
			{
				throw new InvalidOperationException($"Array length of 'Randstr' should be of length of {MetaLibConstants.TQQ_IDENT_LEN} but was {RandstrCount}.");
			}

			for (var i = 0; i < MetaLibConstants.TQQ_IDENT_LEN; i++)
			{
				writer.WriteChar(Randstr[i]);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			// Read array: Randstr
			Randstr = new char[MetaLibConstants.TQQ_IDENT_LEN];
			for (var i = 0; i < Randstr.Length; i++)
			{
				Randstr[i] = reader.ReadChar();
			}
		}

    }
}