


// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;


namespace Rathalos.Core.Protocol.Messages
{

    public class TPDUExtIdent : TPDUExt
    {

		public const TPDU_CMD ProtocolIdConst = TPDU_CMD.TPDU_CMD_IDENT;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;


		/// <summary>
		/// 连接建立包信息长度(密文)
		/// </summary>
		public int Len { get; set; }


		public sbyte[] EncryptIdent { get; set; } = Array.Empty<sbyte>();


		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(Len);
			// Write array: EncryptIdent
			if ((EncryptIdent?.Length ?? 0) > MetaLibConstants.TPDU_MAX_ENCRYPTIDENT_LEN)
			{
				throw new InvalidOperationException($"Array length of 'EncryptIdent' exceeds maximum allowed length of MetaLibConstants.TPDU_MAX_ENCRYPTIDENT_LEN.");
			}
			var EncryptIdentCount = Math.Min((long)Len, (long)MetaLibConstants.TPDU_MAX_ENCRYPTIDENT_LEN);
			for (var i = 0; i < EncryptIdentCount; i++)
			{
				writer.WriteSByte(EncryptIdent[i]);
			}
		}


		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Len = reader.ReadInt();
			// Read array: EncryptIdent
			EncryptIdent = new sbyte[Math.Min((int)Len, MetaLibConstants.TPDU_MAX_ENCRYPTIDENT_LEN)];
			for (var i = 0; i < EncryptIdent.Length; i++)
			{
				EncryptIdent[i] = reader.ReadSByte();
			}
		}

    }
}