// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages
{
    /// <summary>
    /// 排队信息
    /// </summary>
    public class TPDUExtQueInfo : TPDUExt
    {
		public const TPDU_CMD ProtocolIdConst = TPDU_CMD.TPDU_CMD_QUEINFO;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		/// <summary>
		/// 在队列中位置
		/// </summary>
		public int Pos { get; set; }
		/// <summary>
		/// 队列的长度
		/// </summary>
		public int Max { get; set; }
		/// <summary>
		/// 预计排队等待时间,单位秒 (version:13)
		/// </summary>
		public int WaitTime { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteInt(Pos);
			writer.WriteInt(Max);
			writer.WriteInt(WaitTime);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Pos = reader.ReadInt();
			Max = reader.ReadInt();
			WaitTime = reader.ReadInt();
		}

    }
}