


// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;


namespace Rathalos.Core.Protocol.Messages
{

    /// <summary>
    /// 0X82签名协议
    /// </summary>

    public class TQQAuthInfo : TPDUExtAuthData
    {

		public const TCONN_SEC_AUTH ProtocolIdConst = TCONN_SEC_AUTH.TCONN_SEC_AUTH_QQV1;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;


		public uint Uin { get; set; }


		public byte SignLen { get; set; }


		public byte[] SignData { get; set; } = Array.Empty<byte>();


		public byte Sign2Len { get; set; }


		/// <summary>
		/// 一般不用
		/// </summary>
		public byte[] Sign2Data { get; set; } = Array.Empty<byte>();


		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteUInt(Uin);
			writer.WriteByte(SignLen);
			// Write array: SignData
			if ((SignData?.Length ?? 0) > MetaLibConstants.TQQ_MAX_SIGN_LEN)
			{
				throw new InvalidOperationException($"Array length of 'SignData' exceeds maximum allowed length of MetaLibConstants.TQQ_MAX_SIGN_LEN.");
			}
			var SignDataCount = Math.Min((long)SignLen, (long)MetaLibConstants.TQQ_MAX_SIGN_LEN);
			for (var i = 0; i < SignDataCount; i++)
			{
				writer.WriteByte(SignData[i]);
			}
			writer.WriteByte(Sign2Len);
			// Write array: Sign2Data
			if ((Sign2Data?.Length ?? 0) > MetaLibConstants.TQQ_MAX_SIGN2_LEN)
			{
				throw new InvalidOperationException($"Array length of 'Sign2Data' exceeds maximum allowed length of MetaLibConstants.TQQ_MAX_SIGN2_LEN.");
			}
			var Sign2DataCount = Math.Min((long)Sign2Len, (long)MetaLibConstants.TQQ_MAX_SIGN2_LEN);
			for (var i = 0; i < Sign2DataCount; i++)
			{
				writer.WriteByte(Sign2Data[i]);
			}
		}


		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Uin = reader.ReadUInt();
			SignLen = reader.ReadByte();
			// Read array: SignData
			SignData = new byte[Math.Min((int)SignLen, MetaLibConstants.TQQ_MAX_SIGN_LEN)];
			for (var i = 0; i < SignData.Length; i++)
			{
				SignData[i] = reader.ReadByte();
			}
			Sign2Len = reader.ReadByte();
			// Read array: Sign2Data
			Sign2Data = new byte[Math.Min((int)Sign2Len, MetaLibConstants.TQQ_MAX_SIGN2_LEN)];
			for (var i = 0; i < Sign2Data.Length; i++)
			{
				Sign2Data[i] = reader.ReadByte();
			}
		}

    }
}