// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages.Tqqapi
{
    /// <summary>
    /// 0x82 signature first segment
    /// </summary>
    public class TQQGameSig
    {
		public char[] GameKey { get; set; } = Array.Empty<char>();
		public char[] SvcBitmap { get; set; } = Array.Empty<char>();
		public char[] SvcBitmapExt { get; set; } = Array.Empty<char>();
		public uint ValidateBitmap { get; set; }
		public uint Uin { get; set; }
		public uint Time { get; set; }
		public uint UinFlag { get; set; }
		/// <summary>
		/// Client IP address (version:12)
		/// </summary>
		public uint ClientIP { get; set; }

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			if ((GameKey?.Length ?? 0) != TqqapiConstants.TQQ_KEY_LEN)
			{
				throw new InvalidOperationException($"Array length of 'GameKey' should be of length of {TqqapiConstants.TQQ_KEY_LEN} but was {(GameKey?.Length ?? 0)}.");
			}

			for (var i = 0; i < TqqapiConstants.TQQ_KEY_LEN; i++)
			{
				writer.WriteChar(GameKey[i]);
			}
			if ((SvcBitmap?.Length ?? 0) != TqqapiConstants.TQQ_SVCBITMAP_LEN)
			{
				throw new InvalidOperationException($"Array length of 'SvcBitmap' should be of length of {TqqapiConstants.TQQ_SVCBITMAP_LEN} but was {(SvcBitmap?.Length ?? 0)}.");
			}

			for (var i = 0; i < TqqapiConstants.TQQ_SVCBITMAP_LEN; i++)
			{
				writer.WriteChar(SvcBitmap[i]);
			}
			if ((SvcBitmapExt?.Length ?? 0) != TqqapiConstants.TQQ_SVCBITMAP_EXT_LEN)
			{
				throw new InvalidOperationException($"Array length of 'SvcBitmapExt' should be of length of {TqqapiConstants.TQQ_SVCBITMAP_EXT_LEN} but was {(SvcBitmapExt?.Length ?? 0)}.");
			}

			for (var i = 0; i < TqqapiConstants.TQQ_SVCBITMAP_EXT_LEN; i++)
			{
				writer.WriteChar(SvcBitmapExt[i]);
			}
			writer.WriteUInt(ValidateBitmap);
			writer.WriteUInt(Uin);
			writer.WriteUInt(Time);
			writer.WriteUInt(UinFlag);
			writer.WriteUInt(ClientIP);
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			// Read array: GameKey
			GameKey = new char[TqqapiConstants.TQQ_KEY_LEN];
			for (var i = 0; i < GameKey.Length; i++)
			{
				GameKey[i] = reader.ReadChar();
			}
			// Read array: SvcBitmap
			SvcBitmap = new char[TqqapiConstants.TQQ_SVCBITMAP_LEN];
			for (var i = 0; i < SvcBitmap.Length; i++)
			{
				SvcBitmap[i] = reader.ReadChar();
			}
			// Read array: SvcBitmapExt
			SvcBitmapExt = new char[TqqapiConstants.TQQ_SVCBITMAP_EXT_LEN];
			for (var i = 0; i < SvcBitmapExt.Length; i++)
			{
				SvcBitmapExt[i] = reader.ReadChar();
			}
			ValidateBitmap = reader.ReadUInt();
			Uin = reader.ReadUInt();
			Time = reader.ReadUInt();
			UinFlag = reader.ReadUInt();
			ClientIP = reader.ReadUInt();
		}

    }
}