


// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;


namespace Rathalos.Core.Protocol.Messages
{

    /// <summary>
    /// 0x82签名第一段
    /// </summary>

    public class TQQGameSig
    {

		public char[] GameKey { get; set; } = Array.Empty<char>();


		public char[] SvcBitmap { get; set; } = Array.Empty<char>();


		public char[] SvcBitmapExt { get; set; } = Array.Empty<char>();


		public uint ValidateBitmap { get; set; }


		public uint Uin { get; set; }


		public uint Time { get; set; }


		public uint UinFlag { get; set; }


		/// <summary>
		/// 客户端IP (version:12)
		/// </summary>
		public uint ClientIP { get; set; }


		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			// Write array: GameKey
			var GameKeyCount = Math.Min(GameKey?.Length ?? 0, MetaLibConstants.TQQ_KEY_LEN);
			for (var i = 0; i < GameKeyCount; i++)
			{
				writer.WriteChar(GameKey[i]);
			}
			// Write array: SvcBitmap
			var SvcBitmapCount = Math.Min(SvcBitmap?.Length ?? 0, MetaLibConstants.TQQ_SVCBITMAP_LEN);
			for (var i = 0; i < SvcBitmapCount; i++)
			{
				writer.WriteChar(SvcBitmap[i]);
			}
			// Write array: SvcBitmapExt
			var SvcBitmapExtCount = Math.Min(SvcBitmapExt?.Length ?? 0, MetaLibConstants.TQQ_SVCBITMAP_EXT_LEN);
			for (var i = 0; i < SvcBitmapExtCount; i++)
			{
				writer.WriteChar(SvcBitmapExt[i]);
			}
			writer.WriteUInt(ValidateBitmap);
			writer.WriteUInt(Uin);
			writer.WriteUInt(Time);
			writer.WriteUInt(UinFlag);
			writer.WriteUInt(ClientIP);
		}


		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			// Read array: GameKey
			GameKey = new char[MetaLibConstants.TQQ_KEY_LEN];
			for (var i = 0; i < GameKey.Length; i++)
			{
				GameKey[i] = reader.ReadChar();
			}
			// Read array: SvcBitmap
			SvcBitmap = new char[MetaLibConstants.TQQ_SVCBITMAP_LEN];
			for (var i = 0; i < SvcBitmap.Length; i++)
			{
				SvcBitmap[i] = reader.ReadChar();
			}
			// Read array: SvcBitmapExt
			SvcBitmapExt = new char[MetaLibConstants.TQQ_SVCBITMAP_EXT_LEN];
			for (var i = 0; i < SvcBitmapExt.Length; i++)
			{
				SvcBitmapExt[i] = reader.ReadChar();
			}
			ValidateBitmap = reader.ReadUInt();
			Uin = reader.ReadUInt();
			Time = reader.ReadUInt();
			UinFlag = reader.ReadUInt();
			ClientIP = reader.ReadUInt();
		}

    }
}