// <auto-generated />
// This file was generated from XML metalib definition
// Do not modify this file manually as it will be overwritten
using System;
using System.Collections.Generic;
using Rathalos.Core.Utils.IO;

namespace Rathalos.Core.Protocol.Messages
{
    /// <summary>
    /// 0xDE signature protocol
    /// </summary>
    public class TQQUnifiedAuthInfo : TPDUExtAuthData
    {
		public const TCONN_SEC_AUTH ProtocolIdConst = TCONN_SEC_AUTH.TCONN_SEC_AUTH_QQUNIFIED;
		/// <summary>
		/// Protocol identifier for this message type
		/// </summary>
		public ushort ProtocolId => (ushort)ProtocolIdConst;
		public uint Uin { get; set; }
		public byte[] SigInfo { get; set; } = Array.Empty<byte>();

		/// <summary>
		/// Serializes this instance to the specified data writer.
		/// </summary>
		/// <param name="writer">The data writer to serialize to.</param>
		public void Serialize(IDataWriter writer)
		{
			writer.WriteUInt(Uin);
			// Write length for array: SigInfo
			var Len = (byte)(SigInfo?.Length ?? 0);
			if (Len > MetaLibConstants.TQQ_UNIFIED_MAX_SIGN_LEN)
			{
				throw new InvalidOperationException($"Array length of 'SigInfo' exceeds maximum allowed length of {MetaLibConstants.TQQ_UNIFIED_MAX_SIGN_LEN} but was {Len}.");
			}

			writer.WriteByte(Len);
			for (var i = 0; i < Len; i++)
			{
				writer.WriteByte(SigInfo[i]);
			}
		}

		/// <summary>
		/// Deserializes this instance from the specified data reader.
		/// </summary>
		/// <param name="reader">The data reader to deserialize from.</param>
		public void Deserialize(IDataReader reader)
		{
			Uin = reader.ReadUInt();
			// Read length for array: SigInfo
			var Len = reader.ReadByte();
			// Read array: SigInfo
			SigInfo = new byte[Math.Min((int)Len, MetaLibConstants.TQQ_UNIFIED_MAX_SIGN_LEN)];
			for (var i = 0; i < SigInfo.Length; i++)
			{
				SigInfo[i] = reader.ReadByte();
			}
		}

    }
}